### ISSUE TITLE
Would you consider migrating isOfType and isObjectOfType ?

### ISSUE THREAD

**Issue by thiagodp** [sindresorhus/type-fest#10]
The [sindresorhus/is](https://github.com/sindresorhus/is) library defines `isOfType` and `isObjectOfType` (as well as `TypedArray`, `ArrayLike`, `Primitive`, `ObservableLike`, ...)

Wouldn't be interesting to have all these types declared in `type-fest` (and make `is` to use them)?

**Comment by sindresorhus** [comment]
> The sindresorhus/is library defines isOfType and isObjectOfType

What's the benefit/point of moving these here? You can just use `@sindresorhus/is` if you need type-checking.

> (as well as TypedArray, ArrayLike, Primitive, ObservableLike, ...)

Yes, I plan to use `type-fest` in `@sindresorhus/is`.

**Comment by thiagodp** [comment]
At first I just thought that it would be useful to have all those types declared in `type-fest`.

Thinking better, it really doesn't make much sense using `isOfType` and `isObjectOfType` outside the scope of `is` because they don't provide the needed *sugar*. Thx
