### ISSUE TITLE
`SetOptional` remove properties of types with index signatures

### ISSUE THREAD

**Issue by OpportunityLiu** [sindresorhus/type-fest#1013]
### Bug description

After #1007, `SetOptional` remove properties of types with index signatures.

v4.30.1 works fine.

![image](https://github.com/user-attachments/assets/35376e3b-630b-47d9-941d-2cc6a89ede0f)

### Repro

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBDAnmApnA3nAyimB5MGYCAOwEMAbOAXzgDMoIQ4ByJVAWjpQGcYWA3ACghwEjBRQ6ZAMZoAYhAgYhcNfSUAuOHyhiA5sPVwA2gA9tugwF1tAVxIBrEhADuJYdRHs0BOAF5sXAIiUkoAHkUIABpWOiUWAD4jOAB6VLgAPQB+ETV0uABRM1QZCQATbR84P0DMeIhsyxg9En04AB84B3KUOjEUcoFTCx0Wm3snF3caISA

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/1013">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/1013/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/1013/pledge.svg">
</picture>
</a>

**Comment by svrnwnsch** [comment]
I found the same problem with `setRequired` as well.

**Comment by som-sm** [comment]
@OpportunityLiu / @svrnwnsch I've raised [a PR](https://github.com/sindresorhus/type-fest/pull/1014) to fix this issue, are there other cases that you think might cause trouble?
