### ISSUE TITLE
Proposal: `IsTuple<Type>` & `IsFixedLengthTuple<Type>`

### ISSUE THREAD

**Issue by Snowflyt** [sindresorhus/type-fest#1022]
### Type description + examples

I’m surprised that such a type hasn’t been added to type-fest yet. Handling tuple types is quite common in advanced type definitions, and patterns like `number extends T['length']` have already appeared multiple times in this project.

I propose adding two types for checking tuple characteristics: `IsTuple<Type>` and `IsFixedLengthTuple<Type>`. The former determines whether a type is a tuple, including those with rest elements, while the latter is potentially more useful. It checks whether a tuple is fixed-length by verifying if its `length` property is a numeric literal, excluding tuples with rest elements.

### Type source

I’ve attempted to implement these two types, but their type constraints and naming might still need further discussion. Perhaps these types would be better suited to take `ArrayType extends readonly unknown[]` as input. For `IsFixedLengthTuple`, there might also be other names that are more concise yet precise.

~~~typescript
/**
Returns a boolean for whether the given type is a tuple.

Note that a tuple can include rest elements. If you need to check whether a type is a fixed-length tuple (i.e., a tuple without rest elements but possibly containing optional elements), use {@link IsFixedLengthTuple} instead.

@example
```
import type {IsTuple} from 'type-fest';

type Simple = IsTuple<[string, number, boolean]>;
// => true

type Readonly = IsTuple<readonly [number, boolean]>;
// => true

type WithRest = IsTuple<[string, number, ...boolean[]]>;
// => true

type WithOptional1 = IsTuple<[string, number?]>;
// => true

type WithOptional2 = IsTuple<[foo: string, bar?: number]>;
// => true

type WithBoth1 = IsTuple<[string, number?, ...boolean[]]>;
// => true

type WithBoth2 = IsTuple<[string?, ...string[]]>;
// => true

type NonTuple = IsTuple<number[]>;
// => false
```

@category Type Guard
@category Utilities
*/
type IsTuple<Type> = Type extends unknown[]
	? IsEqual<Type, Type[number][]> extends true
		? false
		: true
	: Type extends readonly unknown[]
		? IsEqual<Type, readonly Type[number][]> extends true
			? false
			: true
		: false;

/**
Returns a boolean for whether the given type is a tuple with a fixed number of elements. 

A fixed-length tuple may include optional elements but does not include rest elements.

@example
```
import type {IsFixedLengthTuple} from 'type-fest';

type Simple = IsFixedLengthTuple<[string, number, boolean]>;
// => true

type Readonly = IsFixedLengthTuple<readonly [number, boolean]>;
// => true

type WithOptional1 = IsFixedLengthTuple<[string, number?]>;
// => true

type WithOptional2 = IsFixedLengthTuple<[foo: string, bar?: number]>;
// => true

type NonTuple = IsFixedLengthTuple<number[]>;
// => false

type NonFixedLength = IsFixedLengthTuple<[string, ...boolean[]]>;
// => false
```

@category Type Guard
@category Utilities
*/
type IsFixedLengthTuple<Type> = Type extends readonly unknown[]
	? number extends Type['length']
		? Type['length'] extends number
			? false // `any`
			: true
		: true
	: false;
~~~

### Search existing types and issues first

- [X] I tried my best to look for it

**Comment by som-sm** [comment]
@Snowflyt Yeah, makes sense to add this type.

The implementation for `IsTuple` can be simplified to this:
```ts
type IsTuple<Type> = Type extends readonly unknown[]
  ? IsEqual<Readonly<Type>, ReadonlyArray<Type[number]>> extends true
    ? false
    : true
  : false;
```

<br>

> I propose introducing two types for checking tuple characteristics: `IsTuple<Type>` and `IsFixedLengthTuple<Type>`.

IMO, instead of adding two separate types, a single type with configurable behaviour might be better. Like this:
```ts
type IsTuple<
  Type,
  Options extends {onlyFixedLength: boolean} = {onlyFixedLength: false},
> = Type extends readonly any[]
  ? number extends Type["length"]
    ? Options["onlyFixedLength"] extends true
      ? false
      : keyof Type & `${number}` extends never
        ? false
        : true
    : true
  : false;
```
The above snippet uses ``keyof Type & `${number}` extends never`` approach over the `IsEqual<Readonly<Type>, ReadonlyArray<Type[number]>> extends true` approach just because the former slightly simpler.

<br>

> Perhaps these types would be better suited to take `ArrayType extends readonly unknown[]` as input.

Yup, I agree!

<br>

Another point for discussion is whether `IsTuple` should return `boolean` or `false` when instantiated with a type like `[string] | string[]`.

[Playground](https://tsplay.dev/w1XBlW)

**Comment by Snowflyt** [comment]
@som-sm

> ```keyof Type & `${number}` extends never```

I love this concise trick!

> IMO, instead of adding two separate types, a single type with configurable behaviour might be better.

I think it's a great idea! Building on that, I think it would be nice to also handle optional elements, like with `IsTuple<Type, {allowRest: true, allowOptional: true}>`. Another idea I had is to offer a more concise syntax, such as `IsTuple<Type, Strategy extends 'default' | 'fixedLength' | 'exactLength' = 'default'>`, where the `default` strategy allows both rest and optional elements, `fixedLength` only allows optional elements, and `exactLength` disallows both rest and optional elements.

I believe that using `IsTuple<Type, 'fixedLength'> extends true` would be more appealing to users as a replacement for `number extends ArrayType['length']`, as it feels more concise and intuitive, whereas `IsTuple<Type, {onlyFixedLength: true}> extends true` might seem a bit longer and less straightforward.

> Another point for discussion is whether `IsTuple` should return `boolean` or `false` when instantiated with a type like `[string] | string[]`.

Regarding this point, I tend to prefer returning `boolean` for `IsTuple`, because we already have examples like `IsInteger<"foo" | 42>` returning `boolean`, so it's better to keep the behavior consistent. However, returning `boolean` might cause some issues, such as making `IsFixedLengthTuple<Type> extends true` behave differently from `number extends ArrayType['length']`, as they produce inconsistent results for types like `[string] | string[]`. This is something that still needs further discussion.

**Comment by som-sm** [comment]
@Snowflyt 
> Another idea I had is to offer a more concise syntax

I agree that this syntax is more concise, however IIRC we're currently only using objects for configuring types, so probably it'll be better to stick to that.

<br>

> where the `default` strategy allows both rest and optional elements, `fixedLength` only allows optional elements, and `exactLength` disallows both rest and optional elements.

Nice idea! Just not sure if providing three variants would make things confusing. Could probably just start with two variants initially and then iterate based on future requests. Do you see use cases where disallowing optional elements might be useful?

<br>

> However, returning boolean might cause some issues, such as making `IsFixedLengthTuple<Type> extends true` behave differently from `number extends ArrayType['length']`, as they produce inconsistent results for types like `[string] | string[]`. This is something that still needs further discussion.

Also, since `boolean` has the potential of distributing over conditionals, returning `boolean` could cause issues in scenarios like these:

```ts
import {IsInteger} from "type-fest";

type Test<T> = IsInteger<T> extends infer U ? (U extends true ? "A" : "B") : never;

type T = Test<1 | 1.5>;
//   ^? type T = "A" | "B"
```
[Playground](https://tsplay.dev/WKJaGm)

So, I think it's better to only return `true` or `false`.

**Comment by Snowflyt** [comment]
@som-sm

> Could probably just start with two variants initially and then iterate based on future requests.

I agree with the idea of starting with just two variants initially, as it's a more conservative approach. We can always iterate and add more variants based on future feedback and requests.

> Do you see use cases where disallowing optional elements might be useful?

A common pattern I see is `T extends readonly [infer Head, ...infer Tail]`, where this syntax can't handle optional elements because `[T]` is a subtype of `[T?]`. This pattern is quite common, and in such cases, disallowing optional elements makes sense.

**Comment by som-sm** [comment]
> A common pattern I see is T extends readonly [infer Head, ...infer Tail], where this syntax can't handle optional elements because [T] is a subtype of [T?]. This pattern is quite common, and in such cases, disallowing optional elements makes sense.

Umm...true that `T extends readonly [infer Head, ...infer Tail]` doesn't work when the _first_ element of `T` is optional, and you probably mean that we could wrap the conditional in `IsTuple` and that would be an use case, right?
```ts
type Tail<T> =
  IsTuple<T, "allowRestDisallowOptional"> extends true
    ? T extends [unknown, ...infer U]
      ? U
      : []
    : "Handle optional elements";
```
There's two thoughts on this:
1. We'd have to add a fourth strategy that allows rest elements but not optional elements, right? Because `Tail<[1, 2, ...number[]>` should still give me back `[2, ...number[]]`.
2. In most cases we'd anyways want to handle the optional case, so we can just check if it's a tuple and then add an optional modifier to the conditional itself, like `T extends readonly [unknown?, ...infer U]`, like:

    ```ts
    type Tail<T> =
      IsTuple<T> extends true
        ? T extends [unknown?, ...infer U]
          ? U
          : []
        : [];
    ```
    We have done something similar [here](https://github.com/sindresorhus/type-fest/pull/977#issuecomment-2509125871).
    
@Snowflyt WDYT?

**Comment by Snowflyt** [comment]
@som-sm Well, it looks like there's value in handling all four cases. I have to admit, once we bring rest elements and optional elements into consideration, many seemingly simple cases turn into edge cases that require careful thought.

Your example has convinced me. While intuitively considering optional elements does seem to have some potential use cases, in practice, we tend to handle optional elements directly within the `IsTuple<T> extends true` branch instead.

I think it’s best for now to stick with just the two variants we initially mentioned, and we can add more scenarios in future versions.

**Comment by som-sm** [comment]
@Snowflyt Cool, I'll probably open up a PR for this sometime next week.

**Comment by som-sm** [comment]
@Snowflyt Cool, do you want to pick this up? Or else, I'll probably open up a PR for this sometime next week.

**Comment by Snowflyt** [comment]
> Cool, do you want to pick this up? Or else, I'll probably open up a PR for this sometime next week.

Great, it looks like we’ve reached a consensus! I’d really appreciate it if you could take the lead on implementing this type. I’ve been quite busy with some academic work recently, so I’m a bit tied up at the moment. :)
