### ISSUE TITLE
`Opaque` forces lookup to `any` type because it cannot be used to index `Record` type

### ISSUE THREAD

**Issue by risk1996** [sindresorhus/type-fest#108]
I use `Opaque` type extensively to reduce type errors for `string`s, but I found out that it has an unexpected behaviour that it cannot be used as a `Record`'s index type.
Please see the example below for a typical setup.

```ts
import { Opaque } from 'type-fest';

type UUID = Opaque<string, 'UUID'>
type NormalizedDictionary<T> = Record<UUID, T>

type Foo = { bar: string }

const userEntities: NormalizedDictionary<Foo> = {
  '7dd4a16e-d5ee-454c-b1d0-71e23d9fa70b': { bar: 'John' },
  '6ce31270-31eb-4a72-a9bf-43192d4ab436': { bar: 'Doe' },
}

const johnsId = '7dd4a16e-d5ee-454c-b1d0-71e23d9fa70b' as UUID

const userJohn = userEntities[johnsId]
// the type of userJohn is `any`
```

Can anyone provide me a way to use an `Opaque` type to index a `Record` without sacrificing the type of the value becoming any?

**Comment by sindresorhus** [comment]
This is really a limitation of TypeScript. You may want to open a TypeScript issue about it and link to here.

The workaround for this would be https://github.com/sindresorhus/type-fest/issues/165.
