### ISSUE TITLE
Question: is there any way to get the advantages of opaque and other options at the same time?

### ISSUE THREAD

**Issue by xenoterracide** [sindresorhus/type-fest#113]
given
```ts
export type OrderPart = SetRequired<Except<Partial<OrderEntity>, 'id'>, 'orderId'>;
export type OrderOnly = Opaque<OrderPart>;

export class OrderAggregateFactory {
  constructor(private readonly em: EntityManager) {}

  order(part: OrderOnly): Promise<OrderEntity> {
```
if I use it like this... I get the benefits of both

```ts
      const orderPart: OrderPart = {
        status: OrderStatus.Open,
        orderId,
      };
      return new OrderAggregateFactory(em).order(orderPart as OrderOnly);
```

but if I write like the latter, I lose the benefits of `SetRequired`, and probably other things (this compies)

```ts
      return new OrderAggregateFactory(em).order({
        status: OrderStatus.Open,
      } as OrderOnly);
```

is their a way to write it "like" the latter example? but still have Required and other things cause compile errors?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/113">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/113/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/113/pledge.svg">
</picture>
</a>

**Comment by fregante** [comment]
I think this is the answer, but it's not here yet:

- https://github.com/sindresorhus/type-fest/issues/702
