### ISSUE TITLE
@ReadonlyDeep generic type 

### ISSUE THREAD

**Issue by carpben** [sindresorhus/type-fest#116]
[PR #34](https://github.com/sindresorhus/type-fest/pull/34#discussion_r325303311) defines ReadonlyDeep as follows. 
```ts
export type ReadonlyDeep<T> = T extends Primitive | ((...arguments: any[]) => unknown)
	? T
	: T extends ReadonlyMap<infer KeyType, infer ValueType>
	? ReadonlyMapDeep<KeyType, ValueType>
	: T extends ReadonlySet<infer ItemType>
	? ReadonlySetDeep<ItemType>
	: T extends object
	? ReadonlyObjectDeep<T>
	: unknown;
```

Is there any case in which a type would be mapped to "unknown"? Don't the queries cover all possible types? If so, can't the definition be simplified? 

In the discussion which I linked to above, I suggested moving the Primitive test to the last clause. However, since then I was told that such an implementation is worth for typechecking performance, as every property will first be checked for all other types, and that those type queries aren't neglected in terms of performance. Out of these considerations, if Set and Map don't extend object, I suggest moving the object query above. 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/116">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/116/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/116/pledge.svg">
</picture>
</a>

**Comment by fregante** [comment]
Now outdated, the source is different: https://github.com/sindresorhus/type-fest/blob/main/source/readonly-deep.d.ts

Closing
