### ISSUE TITLE
Proposal: `Must` 

### ISSUE THREAD

**Issue by LucienLee** [sindresorhus/type-fest#117]
Like `Required` make all properties in T required.

I want to propose adding `Must`, which makes all properties in T NonNullable. 

```typescript
type Must<T> = {
  [P in keyof T]-?: NonNullable<T[P]>;
};
```

If it makes sense, I can make a PR.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/117">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/117/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/117/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
What's the use-case and how does it differ from `Required`?

**Comment by LucienLee** [comment]
`Required` only make the property not optional, but keeping null. 
I think that we need a way to strip `null` too. 

See related discussion [here](https://github.com/microsoft/TypeScript/issues/28374)

**Comment by sindresorhus** [comment]
Ah, that makes sense. I think this could be useful. However, I don't think the name is clear enough.

How about `NonNullableDeep`?

**Comment by papb** [comment]
Interesting, something that makes the value:

* Required
* Not `null`
* Not `undefined`

I would suggest `StrictlyRequired`, what do you think?

**Comment by kainiedziela** [comment]
Is this type supossed to nest within object properties? If so, then a `Deep` suffix is valid, because thats the naming pattern used throughout the project. Since the type would deeply apply `NonNullable` I think `NonNullableDeep` is the name that makes the underlying logic obvious.

**Comment by papb** [comment]
@kainiedziela You're very right, the `Deep` suffix is very valid! Let me change my suggestion to `StrictlyRequiredDeep`.

I don't think `NonNullableDeep` is the best because it seems to imply that the only thing happening is `NonNullable` being applied recursively. I'd even prefer `RequiredAndNonNullableDeep` or `NonNullableAndRequiredDeep` over `NonNullableDeep`, but `StrictlyRequiredDeep` seems to fit it well and is shorter.

**Comment by LucienLee** [comment]
I didn't think that applying `NonNullable` recursively at initial, but it's a good idea too. 
So how do you guys think about adding two types:
1.  A single level NonNullable types, name as  `StrictlyRequired` or something else
2.  A recursively `deep` one,  name as `NonNullableDeep` or `StrictlyRequiredDeep`

**Comment by papb** [comment]
@LucienLee That looks great to me.

**Comment by tjx666** [comment]
need NonNullableDeep, current version is not recursive.


![image](https://user-images.githubusercontent.com/41773861/208601321-e6298386-6467-41ad-a5e4-6695e906f4af.png)

**Comment by fregante** [comment]
Added as SetNonNullable: https://github.com/sindresorhus/type-fest/blob/main/source/set-non-nullable.d.ts
