### ISSUE TITLE
Proposal: ArrayItem

### ISSUE THREAD

**Issue by scvnathan** [sindresorhus/type-fest#118]
We've found this type handy in our codebase and thought this would be useful in `type-fest` too.

## Proposal
`ArrayItem` extracts the type of the item(s) in the array:

```ts
type ArrayItem<TArray extends any[]> = TArray extends (infer E)[] ? E : TArray;
```

Possibly could be improved by replacing the fallback conditional with `unknown` instead of `TArray`.

playground example: https://www.typescriptlang.org/play/#code/C4TwDgpgBAggTnAhiAksCBbAPAFXkkKCAD3QDsATAZykTJAG0BdAPigF4o8FkjSJKNABQBLMgDMIcKAFEAlMygB+WVABcXfMgDcAKF2hIUNJhqcA3lHEB7axqrA4YgObaoAI0RwNZAK4Z3KSgAX2Y9Q2gAWRFiCAoTDDMoIUsbOygHJzJXDy8ff0DpYKgAMihLTwAvDQAhEWcUMnRnIOCFJj0DcGgRdAwOWB5UPqwEqhZw7qgMGLiEga1hzCxo2Pi+8cmjMQA3RAAbEQoFoYSsPwCpCaA

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/118">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/118/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/118/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
> We've found this type handy in our codebase

I'm curious what *exactly* you use it for? Maybe you could provide an example of how you use it in your codebase?

**Comment by scvnathan** [comment]
> > We've found this type handy in our codebase
> 
> I'm curious what _exactly_ you use it for? Maybe you could provide an example of how you use it in your codebase?

Sure, I'll provide some examples as soon as I can

**Comment by scvnathan** [comment]
The use initially arose while adding TS typings for an in-house Redux library. It's used as part of conditional type that gets all the return types of an array of functions and turns them into a union.  I've tried to simplify everything down to its core type usage here:
https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=20&pc=2#code/C4TwDgpgBAggTnAhiAksCBbAPAFXkkAPigF4o8FkoIAPdAOwBMBnKACgEt6AzCOKAKIBKANoBdKAH5BUAFzl8yANwAoFdwCu9AMbAOAe3pREjRjn2N9bdHXnNgcLgHMhUAN4qoUOBGAa4Rh5eXqCQ8gDkMAAiUQD6OADyUQnhxqzahvYANJ7BNsC5AL4qxepaugZGwPpOTgA2EOaWnEy08vQaGABGfK5B3r7+gVChEBGJAOITADIC8UkpaVAZ9NlQXIy0UMWlK-bGFZmkUCImZhb6WSM19Y0XYqoqo1AACsh1+ibMuDCHq8RkRSodDYNwnADS6yMAGsICB9NwFH9mGJ5HhkSJwRJaAwWOwAHSExBwJzMeSIeggVwkYgUkBSKAAJUGARw4AgPwxWOI8i00Po+gA7vQlNtCI9NDo9IYoAALCmMBpsRB-N4gD5feRqjUsLAiUYI4ymJqXEbsw3VWoNE1iQh9XIAegdUEsUGY+gwvllziggo4wFlB2lRjA70+LBKQA

Another use case is dealing with third party types. Sometimes we aren't provided with every type we want to reference. For example, there's a team using `@octokit/rest`  and they wanted to reference the type that comes from the teams list API response. Since there wasn't a built-in type for that so that team chose to do something like this:

```ts

import { RestEndpointMethodTypes } from '@octokit/rest';

export type GithubTeam = ArrayItem<RestEndpointMethodTypes['teams']['list']['response']['data']>;

// ... other exported functions that reference `GithubTeam` when transforming response data, etc
```

**Comment by sindresorhus** [comment]
Why not just `type mixedItem = MixedItems[number]`?

From: https://stackoverflow.com/questions/41253310/typescript-retrieve-element-type-information-from-array-type

**Comment by Yhozen** [comment]
> Why not just `type mixedItem = MixedItems[number]`?
> 
> From: https://stackoverflow.com/questions/41253310/typescript-retrieve-element-type-information-from-array-type

IMHO it is easier to read something like ArrayItem<type> than type[number], I feel like it is more explicit
