### ISSUE TITLE
 ConditionalKeys<Base, Condition> fails when used on Arrays

### ISSUE THREAD

**Issue by KilianKilmister** [sindresorhus/type-fest#119]
There is a bug in Typescript related to ```keyof Array``` that affects ```ConditionalKeys<Base, Condition>``` and the Types using it. (reporting the bug itself to typescript, aswell)
It can be fixed adHoc without affecting any non.bugged existing uses

case:

[Playground Link](https://www.typescriptlang.org/play?strictPropertyInitialization=false&useDefineForClassFields=true&allowUnusedLabels=true&noEmitHelpers=true&noUnusedLocals=true&noUnusedParameters=true&esModuleInterop=false&preserveConstEnums=true&declaration=false&target=99&jsx=0&ts=4.0.0-beta#code/C4TwDgpgBAggTnKBeKcIEMAmB7AdgGxCgG0AGAGigEZKAmSgZkoBZKBWSgNkoHZKAOSgE4AugFgAUJNCQoAdQAW2bGACyIeHHQgA+gDF0AV3ygAPACF0AZ2gQAHsAi5MV2Am0AZAJYBrCKfRcEAA+SgBhPEwvYC88YOQoAG8oKEkASDTiAGkIIi9cKD8QbAAzKEsbEQAudIyKiGzckSh7R2dXCOdo2NxajIB+KAByRWUwKGihvrSq8usGnJBm1qcXOZtiXEMAWwAjCDhmwfWFpqhZ3AgANwP0gF9JSQB6J6h0AGMYvAnXSDgS7BwbYQTBQb7odxECD4CDA3DAVy7QzACa4d74QyYCCudD4fBQK64wzYsFlTTaAB0YDg2GAtPAEGkDPkShUIPJIEWrhQoxU6g5+iMJhApk0vCgAB8oGxJVBaMFiEVSm5DkA)

```ts
type Arr = readonly [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

type WhoopMyArray_Faulty<Base extends ArrayLike<any>, Condition> = {  
		[Key in keyof Base]:
			Base[Key] extends Condition
				? 'Whoop it'
				: Base[Key] extends Base[number] ?  Base[Key] : never
	}

// action is performed on array elements but includes all values of Array.prototype
type WhoopedArrayKeys = WhoopMyArray_Faulty<Arr, 7 | 5 | 2>[keyof Arr]
```

So using ```ConditionalKeys<Base, Condition>``` 

[Playground Link](https://www.typescriptlang.org/play?strictPropertyInitialization=false&useDefineForClassFields=true&allowUnusedLabels=true&noEmitHelpers=true&noUnusedLocals=true&noUnusedParameters=true&esModuleInterop=false&preserveConstEnums=true&declaration=false&target=99&jsx=0&ts=4.0.0-beta#code/JYWwDg9gTgLgBAbzgYQgOwCbBsdBDAGwGkBTATwGc4BfOAMyghDgHIYywSBaOkimFgFgAUCPac4AdQAWECJwwBBKFDxk4AXjhQSeDOgLqA2gAYANHACMFljLlg42FhYDMNu-McCLAVnezPJwsAdgsADgsATgBdMQ4SKQCFZVUyUkpNFHQsHHxicgoAHg9klTV-ey8WAD4gA)

```ts
import { ConditionalKeys } from 'type-fest'

type WhoopedArray = readonly [0, 1, 'Whoop it', 3, 'Whoop it', 5, 'Whoop it', 7, 8, 9]
type WhoopedArrayKeys = ConditionalKeys<WhoopedArray, 'Whoop it'>
```

results in ``` "2" | "4" | "6"```  and all Array.prototype-values

this can be fixed by adding a temporary dummy key to the UtilityType:

[Playground Link](https://www.typescriptlang.org/play?strictPropertyInitialization=false&useDefineForClassFields=true&allowUnusedLabels=true&noEmitHelpers=true&noUnusedLocals=true&noUnusedParameters=true&esModuleInterop=false&preserveConstEnums=true&declaration=false&target=99&jsx=0&ts=4.0.0-beta#code/C4TwDgpgBA6gFgewZAJgQQE4YIYigXigG0AGAGigEYKByeJMKAS2BooGZb7lnWKBWLoh4s2UAOwUAHBQCcAXQCwAKBUQAHmAQZgUUJCgBhBADsULJqewAbANIQQAZwA8AIWyOIFY2YumAfARQAHKmwQCu1tbYAEbWEM5QAPRJUAAqAPIAIhkAXFAYEFo6UDHhAObMJnqOUB564BAAtABmEI7AKgCQKbA4jEzVAAahJhFRsfFDeghQHRhMjNgA7rh6cNBD4WYQLYMQKNP60C0YCAC269BgZyjhAMYHUNuWJgB03QDe3T2pALLYRjAOBnCpwOpRK5QADWDlqCBaUPKTAAbhBqjEPNBjm8Qhk0gBRfJ3c7nEBNG4iWomCAHJ4tbRQTA4Jw-Ij2PCDGEOBFQdyeKAAHygNAA+qKmOcmtgmiSyRSzmBxTR5Lkfr8oAAFJj3aFQUzWPCwpxQZYscHHWoaYDo8wmSrA6DItHDHzmYCvI6ND7KLp+-kQIgE9T3azhFAJDm0cWS6Wy8Kk8mUpWimj+eRQa222puvwmdUagBKEGA2C5wKYtWNc0Gjyh91M7teUDAHk8jh9fr9AH4oByC70spX7tgMCh1pXuXhHLXsRsoA3fB7TFAWmXrB2C-kaWiMN1ej5d7pHS3bg8nggYgArCD3XSDYCzbDPEzN476xEn421ZZwHXg1tHE8ccT0XJsrGsPR2mATsAF8iGNXkAyUZR-AAbhUFR324VBmVwDlakIXNlxMGwCOcHCDjwkAhAYXg0xUXomkCGgACYaCFEUABYOM4kUADYaCAA)

```ts
type WhoopedArray = [0, 1, 'Whoop it', 3, 'Whoop it', 5, 'Whoop it', 7, 8, 9]

export type ConditionalKeys<Base, Condition> = NonNullable< // TODO: report bug in ts as type-fest
	// Wrap in `NonNullable` to strip away the `undefined` type from the produced union.
	{
		// Map through all the keys of the given base type. NOTE: dummy-prop is needed for Arrays
		[Key in keyof Base | '__im-a-dummy-prop__']:
			// Pick only keys with types extending the given `Condition` type.
			Base[Exclude<Key, '__im-a-dummy-prop__'>] extends Condition
				// Retain this key since the condition passes.
				? Key
				// Discard this key since the condition fails.
				: never
	// Convert the produced object into a union type of the keys which passed the conditional test.
	}[keyof Base]
>;

type WhoopedArrayKeys = ConditionalKeys<WhoopedArray, 'Whoop it'>
// -> '2' | '4'  |  '6'
```

Took me ages to find out why my stuff isn't working

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/119">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/119/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/119/pledge.svg">
</picture>
</a>

**Comment by 0f-0b** [comment]
This fix does not involve an arbitrary dummy key.

```ts
export type ConditionalKeys<Base, Condition> = {
	// Map through all the keys of the given base type.
	[Key in Exclude<keyof Base, never>]:
	// Pick only keys with types extending the given `Condition` type.
	Base[Key] extends Condition
	// Retain this key since the condition passes.
		? Key
	// Discard this key since the condition fails.
		: never;

	// Convert the produced object into a union type of the keys which passed the conditional test.
}[keyof Base];
```

**Comment by fregante** [comment]
As pointed out in the TS repo issue, `keyof` shouldn't be used on arrays, and I don't understand why you'd want to use ConditionalKeys on an array either as arrays don't have "keys" but "indexes"
