### ISSUE TITLE
A range of numbers

### ISSUE THREAD

**Issue by DanMossa** [sindresorhus/type-fest#123]
Something built in like this
https://stackoverflow.com/questions/39494689/is-it-possible-to-restrict-number-to-a-certain-range

Instead of 

```ts
interface Car {
  model: string,
  year: 1999|2000|2001|2002
}
```

It would be nice to be able to do

```ts
interface Car {
  model: string,
  year: NumberRange<1999, 2002>
}
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/123">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/123/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/123/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
I think we could do something like what's done here: https://github.com/microsoft/TypeScript/issues/15480#issuecomment-601714262 But it would be limited to a range of 40. That should be enough for many use-cases though.

**Comment by henryruhs** [comment]
What about this, stolen from [stackoverflow](https://stackoverflow.com/questions/39494689/is-it-possible-to-restrict-number-to-a-certain-range) and modified to work properly:

```
type Enumerate<NUMBER extends number, ARRAY extends number[] = []> = ARRAY['length'] extends NUMBER
    ? ARRAY[number] : Enumerate<NUMBER, [ ...ARRAY, ARRAY['length'] ]>
export type Range<FROM extends number, TO extends number> = Exclude<Enumerate<TO>, Enumerate<FROM>> | TO;
```

Some testing:

```
const validOne: Range<0, 100> = 0;
const validTwo: Range<0, 100> = 100;
const invalidOne: Range<0, 100> = 101;
const invalidTwo: Range<0, 100> = -1;
```

**Comment by sindresorhus** [comment]
Seems like it's now possible with TypeScript 4.8: https://twitter.com/anuraghazru/status/1573328100246822917

Nice work, @anuraghazra

**Comment by souporserious** [comment]
I came across this problem on [reddit](https://www.reddit.com/r/typescript/comments/k49fmr/comment/ih63lng/?utm_source=share&utm_medium=web2x&context=3) and then checked this library to see if there was a utility yet. Not sure if this can be expanded further, but it seems there's a way to bypass the excessive iterations error after 1000 using template literals, see [here](https://www.typescriptlang.org/play?#code/PTAEFsHsBMEsDNYFNqngJ0uUALJ6kAuXAFxIAcBnQkAd3oDoDo4SGBjLYdYEgT3JJK7dLHIlgncOCQA7EpWABrACwBOeOB5SZ84LBwA2AMwAbWQHNgAfgCuJcAH1KkW+nZIAvJRwBDAgBk9k4ycLbgnrRIAEYATAAeAZzySPEknsYAUPyCoABKvpZIjgCMpQAMleWgnqAABiVV5XWgAD71jZUt7Q1dbfUAJADeBUWljmpqAL512QJI+YUWxWWTNYMjSysTU8Ojy47lO3tbh8ebY0fT3Rv729Mnl+d3Z9f9dY8Hq7sXB1cz-ReqzmuReV3WdWa7xKNzqsVhxlhKlhAFZYYZYQB2WEADlhalmOQWQImEJh73h70R72R7zR7wx72x7zx7wJIIWADlwtF8HcADwAFW52FSJDk0EooFkPPwAD51gAKD5DYXhAFiiVSkmdSqgaygNXYYiyJAAN3wAEpMplkpQSGhbLJ2OshSLQJrZJLpbL0HLFf4LMQRbz0AKjXLLTUFYGANw2+BO9iKxqW2OgECgADyAGlMonnYrJpM0xmwLn80mU1USqXMwBRdCYdBAA).

**Comment by tommy-mitchell** [comment]
I’ve started working on implementing a solution similar to https://github.com/microsoft/TypeScript/issues/15480#issuecomment-1382814026, with options to control the step size, if the range is inclusive, and if the range should be a union instead of a tuple (using `UnionToTuple`). Should the name be `Range`, as in `Range<Start, End, Options`>?

Still trying to figure out how to infer `End` if only `Start` is set:

```ts
type FiveNumbers = Range<5>;
//=> [0, 1, 2, 3, 4]
```

I also think it would be worth adding a `RangeUnion` wrapper that is just a `Range` with the `{asUnion: true}` option set. It should probably be inclusive as well, as that seems to be a common use for the union type.

**Comment by sindresorhus** [comment]
> Should the name be Range, as in Range<Start, End, Options>?

👍

**Comment by jd-solanki** [comment]
Another solution: https://stackoverflow.com/a/39495173/10796681
