### ISSUE TITLE
Can't resolve type-fest

### ISSUE THREAD

**Issue by ar53n** [sindresorhus/type-fest#124]
There is a problem when we have a type of import in the file. After the code is transported, the import of the form remains. And then during the build, we see the message: `Can't resolve type-fest module`. I suggest adding an empty `index.js` file in the root of the module. Thank you.

before transpile in *.ts file
```
import {ReadonlyDeep} from 'type-fest'
```

after transpile in .js file
```
import {ReadonlyDeep} from 'type-fest'
```

**Comment by sindresorhus** [comment]
That sounds more like a problem with the build tool you're using than `type-fest`.

Just FYI, you can use `import type {ReadonlyDeep} from 'type-fest'`.

**Comment by ar53n** [comment]
@sindresorhus After writing that issue, I found this solution. Thank you

**Comment by mathiasose** [comment]
I also encountered a message like this when running eslint after installing type-fest.

For future reference: the solution for me was to add `plugin:import/typescript` to `.eslintrc`, as described on https://github.com/benmosher/eslint-plugin-import#typescript.

**Comment by airtonix** [comment]
> That sounds more like a problem with the build tool you're using than `type-fest`.
> 
> Just FYI, you can use `import type {ReadonlyDeep} from 'type-fest'`.

This should be in the documentation
