### ISSUE TITLE
Proposal: `ReplaceReturnType`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/type-fest#125]
A type where you can change the return type of a function type. This makes it possible to reuse a function type definition where you need slightly different return values. For example, a Node.js package that has both an async and sync API, and the only difference is that the async API returns the value wrapped in a `Promise` type.

Implementation and example use-case: https://github.com/sindresorhus/make-synchronous/blob/6796cca6109a5e5068c5f1cadc99ef7e0d9b8e6a/index.d.ts

Thoughts?

**Comment by sindresorhus** [comment]
I just realized that this is the same as https://github.com/sindresorhus/type-fest/issues/88, but I think the implementation here is slightly better.

// @pluma

**Comment by pluma** [comment]
I'm okay with this. 👍

**Comment by papb** [comment]
Funny thing, I thought about this two days ago, I was about to come here suggest it as well :grin: 

The name I thought of was `SetReturnType`
