### ISSUE TITLE
Simplify `PromiseValue` type when TS 4.1 can be targeted

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/type-fest#131]
It can then simply be:

```ts
type PromiseValue<T> = T extends PromiseLike<infer U> ? PromiseValue<U> : T;
```

https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/

**Comment by JounQin** [comment]
Should this be removed in favor of [`Awaited`](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#the-awaited-type-and-promise-improvements)?

**Comment by voxpelli** [comment]
@JounQin See https://github.com/sindresorhus/type-fest/issues/275
