### ISSUE TITLE
Proposal: A version of Pick that distributes over union types

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/type-fest#132]
See https://github.com/microsoft/TypeScript/issues/28791#issuecomment-443520161:

> The issue is that `Pick` doesn't distribute over union types, and therefore your `Omit` type doesn't either. Here's a simplified version of your example:
> 
> ```ts
> type A = { name?: string, variant: 'a' };
> type B = { name?: string, variant: 'b' };
> type C = A | B;
> type X = Omit<C, 'name'>;  // { variant: 'a' | 'b' }
> ```
> Because `Pick` isn't distributive over union types, when the input type is a union it is effectively treated as a single object type with only the common properties, each having a union of the respective property types. So, `Pick` sees `C` as equivalent to `{ name?: string, variant: 'a' | 'b' }` and `X` therefore is `{ variant: 'a' | 'b' }`, which isn't assignable back to `C`.
> 
> There are two ways you can fix the issue. The simplest is to declare `C` as a single object type (and this would be my recommendation):
> 
> ```ts
> type C = { name?: string, variant: 'a' | 'b' };
> ```
> The other is to make `Omit` be distributive over union types:
> 
> ```ts
> export type AllKeys<T> = T extends T ? keyof T : never;
> export type Omit<T, K extends AllKeys<T>> = T extends T ? Pick<T, Exclude<keyof T, K>> : never;
> ```
> This may look a bit odd, but the `T extends T ? XXX : never` pattern simply means "when `T` is a union type, distribute `XXX` over each constituent of `T` and union together the results".
> 
> When you use the distributive form of Omit you now get
> 
> ```ts
> type A = { name?: string, variant: 'a' };
> type B = { name?: string, variant: 'b' };
> type C = A | B;
> type X = Omit<C, 'name'>;  // { variant: 'a' } | { variant: 'b' }
> ```
> and `X` now is assignable back to `C`.

The solution I came up with is:

```ts
type AllKeys<T> = T extends T ? keyof T : never;
type Select<T, K extends AllKeys<T>> = T extends T
  ? Pick<T, Exclude<keyof T, Exclude<keyof T, K>>>
  : never;
```

Note that here I want a `Pick` that is distributive, and the above was about `Omit`. I suppose we'd want both?

Not sure what to name this though.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/132">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/132/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/132/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see the initial attempt in https://github.com/sindresorhus/type-fest/pull/710

**Comment by sindresorhus** [comment]
Thank you @henriqueinonhe for contributing to close this issue! ⭐

The rewards from this issue, totalling $100, has been shared with you.

**What now?**

1. Create a [Polar](https://polar.sh) account
2. See incoming rewards & setup Stripe to receive them
3. Get payouts as backers finalize their payments

_If you already have a Polar account setup, you don't need to do anything._
