### ISSUE TITLE
Template literal type ideas

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/type-fest#134]
TypeScript 4.1 will bring a lot of cool abilities: https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/

Let's brainstorm some ideas.

---

For example, some ideas from [this playground](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200920#code/C4TwDgpgBAymA2BLYAeGUIA9gQHYBMBnKQ4AJ0VwHMAaKAEQ2zyJPMqoD4oBeWJnAWIADACQBvSgDMIZKABUAvhPrLJuGXICqi4VAD8UANry6AOgtwkqLXXqcAulABcxmA4DcAKFCQFAQwBrCAAZf1IUADVuPkiBFmIjJ0NcCAA3WRcoOKxBViNSCmpk7KMABidXHOYhY0KOcwtpTIAlEvkg0PDUFu5XVIyyb19oeQoAWxCIKVRqvOJ66hjs+Nq9CWa5Ft0DBQmpmZRerMjh8FGJlsQqAAtZ1dZFrl4V3ISoMXVNKG2P3bHEOMrrcen1smc-ADxlEHgt2EsXlCDqgocC7lFOJwIdAYOwwABZAD2+EQUkQshhb1qTzo+NhbCKz1i9M+mygITU+LUbIAgjtDCETtjYHiiSSybJCJSao94UyRRQCcTSeSyGhRcqJWrcYqxSqKTrEErxaqonQAORmc2cC0AYmtFqMDqg5uc1uFHWCYVIPJmsnkhOCuGl8wZDQU9Key0Nxv1ZClnq6ESsyBQUIxdHkmKxPnOUAA4hBgN7gABReAQcZ4YAAOX8VZD7yjiM6Jd9ODIAaDadb3Xb-sDeDNLpdNtH7tzfkLZf8AGMbuXK9W6w3InRBVTZYyki8kssvFBD68ZYknAejxeBVBzxfD1V6QU5Wfb0fDEYLGYQnRpyXF1XcLW9YQFE5QOI414vnex6ho+jKNGYbJtBBkGGNOpZzguFb-oBDYtHQ74WF+BZFr+WHLkBIEVI43A3rerhJMKaFkQBK4QFKcxNnKyxoRhf7kQ2KazBaNDWjmIxQHxAEAEIgKxjbUlxLy0RxtTBCAhJSFAAAS8j4iEknAB0VCsfi-hgMhL6GDpekGUZJlmUYkTPpB96bsQakabAkT5rZ-jGUBpnmbRl5eT5zGGX59lgI5zkvq4BnCqZwDzuhKXhcOG4nhJ4VQAAPlAuAAK7wPALxFSV+4Xip+SxbeV7BUerlZbBHC1SFgr5QZMlyZEoE0ZBJwPjSUAfohbWvlASUpbx6V4eyeXZUu0myRRvVUf1Lnst4k7QAAioVsggC0bHFSikaKXwU0LjNS2oExt2sQmmLbQA9AAVG9B5vRJmD1ggEBfS9Xj4BAs7wP4ZDQFIhW4LOwCIISuBQAAjgdZAgDAEAVnDhJqvI52MpwAAUqOHa48gAJSuPth3HYQp1pjmXizojpBQP4Lyk+jmPY8AuNE+aJJpGYABG-i4KkcjcP4Zizv4JUALR8wrc7w4j5oU1AL0vQr3DWSEPKwzcuMGczrPAFAIuc2jGNY6DfNkALlBgIVwB0ELGtazreu6SEACSuAu2WOX5fr9CIGkpss7gbOztbh08-b-PmrOiBkGDEBGLOmA8AARAAjAArGUucOJ72u66FADCacZ1H5tQPg8fc3bOOO+aIuu3zuC2p3IAK7ghIAO7l972m+1JXeI-XMcW9AfBc7bvPJ4Q9sI0jYDOGS8bAArGlK+cGseF7lf6wAChDflkGZmG3V4QA);

```ts
type Split<S extends string, D extends string> = S extends `${infer T}${D}${infer U}` ? [T, ...Split<U, D>] : [S];
type TakeLast<V> = V extends [] ? never : V extends [string] ? V[0] : V extends [string, ...infer R] ? TakeLast<R> : never;
type TrimLeft<V extends string> = V extends ` ${infer R}` ? TrimLeft<R> : V;
type TrimRight<V extends string> = V extends `${infer R} ` ? TrimRight<R> : V;
type Trim<V extends string> = TrimLeft<TrimRight<V>>;
````

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/134">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/134/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/134/pledge.svg">
</picture>
</a>

**Comment by voxpelli** [comment]
Some additional ideas from [this other playground](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201029#code/C4TwDgpgBAymA2BLYAeGUIA9gQHYBMBnKQ4AJ0VwHMAaKAEQ2zyJPMqoD4oBeAKCiC2FakxwFi6APzCOAbQC6UAFwCh6LONYBybVBmKVawRuYSoAAwAkAb0oAzCGSgAVAL636Hu7kfOAqm4W+lByLnQAdFFwSKj+dPScSqpCoTAKANx8fKCQUPYA9gW8sAjIKABEhQUAtABGAIZkFXQVNRWcOeDQMcgA8rgA6gVk+DAQYE0NwCMoLmIsxKQiXCW9qOFQbRUAPhUA+rsVW5xZudD+BBD2lBD4LgUAogC2YKAw7NRzC+bLHNw8Vw-VgAVyuN1wdxCFWOylcZ26UAAwg1nhB4CjCBAPisAIJkMgNEAoADSwKWnyoigBllsJLkAAYFN4UWBkA0kAAvCAoS74a63e5PV7vSmkuQARgUnE4QQReRRaIxDSxpJpZM0i1kohkivRmOxlPxhOJ6wGw1G40mhJmZDV3DhJPl0GqAGYSnrlaqqkV6k0OhkoAB6INQABCEAAxgU0cQfQUw-6unlqgBWD2o-UqnnxqCNZqnYOhiPR2NbaqJ5rJl1FABsGaVBsq1X2+YDRfDUZjEDjFaT53yRQALA2s97qm3CyHO6We+Wim3sgPPQb8AAFMgFMCEOY0mzGUJkyhQADWEBABXsQJVyMzXp5JKScJcchJCj4biyfEoODI9gakbQCSECNHUq5QPuqTxn6zRwn81BZKk1RwrgILPHUThZG42TTiW3aEHw077tOQh9mQcGUlkJGCMhUCoehmGEaG2HLne4GAiu2brpu26kiBDRgVxpx8EAA):

```typescript
type UndefinedToEmptyString<T extends string> = T extends undefined ? "" : T; // This one can probably be done better
type CamelCaseStringArray<K extends string[]> = `${K[0]}${Capitalize<UndefinedToEmptyString<K[1]>>}`;
type CamelCase<K> = K extends string ? CamelCaseStringArray<Split<K, "-"|"_"|" ">> : K;
type CamelCasedProps<T> = { [K in keyof T as CamelCase<K>]: T[K] };
```

**Comment by voxpelli** [comment]
`Trim<>` suggested for an intrinsic implementation here: https://github.com/microsoft/TypeScript/issues/41283

**Comment by voxpelli** [comment]
Even more ideas from [this updated playground](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201029#code/C4TwDgpgBAymA2BLYBJAdgY3gVwCaLQHMARCJAW2QHsAnAHhiggA9gI1cBnKT4GgwgBooxJq3ZcefAQD4oAXgBQUFVP5ExbDt0YB+NQIDaAXSgAuZasYstkgOR2o+k+csrr47VAAGAEgDeBABmEDRQACoAvgHE0YFoIWEAqpHeTm5QABSwmhLcfv5RAcGhUABacSlpzuHCZcIAdE1wSMB0ScLEMqZmUGgQAG6lAJSuqlCGMMYA3IqKoJCwCMgMuV686kIia5IbsgoZexo2eTn6R4QuFuMettwOThM9GbenBSVhRf6xxQmlVY9DLUoE0Gi0Vh0RN0xqpJjM5gtoAApKgEVYnLwAQzQIBMnR23AuciU4wuLgxkj0Bg01ysBIm7z+n1SjSaHygSVMugySUMAAZTBTuNgOBAggQILhHuFzD4Al8fv4UWjIV1UjCVA5ZvNwNAkqLxf1cOEqABRchgUAwaREOgyoXUwjEiL0kW4MUSqX6ABE3tl4W1iI5YEgNAAwpjOBAwwALTE0bjyKB2ACCjgAPsmAEIZ5Nh3N2YgF00FgBiBYA4gWABIFlAFpEFgDSBYAMgWALIFgByBYA8gWAAoFgCKBYASgWYAXwgWkgWAGoFgAaBYAmgWynZZkGAOq0XAwCBgeOY4C0RNQb0AWm96e9AH0737vYHdbAbYQUzQaJiQCaI3IMgIyjOgm3pMljGdAom35Yw4gjMBkExJAAC8IHaA1PRNc1LRAa1NjAwwAEYoJkVId3fQDgMjDCm2dcCHQuR4CIEb9f3-KhqPgECMPBNom2EfcaEPY9T3PBMZDkXomzfRZWKIQd42AE0mwgAAjTF1N4sCIM-YRXnWfSoFbPTNmJDJGM8SlHjsa9HFpFQrLuEzHm8a8AlbKgAHdQgwWiwPItJHKgWSdXkz92L-VSNK0nTnNObFcWMAyzIEYRTKYz8LPGBKvEMRlEgiFkQTZJkOS5OV-AUwglJoFSqDUzTtIC4EYAy8iAhqqLOKauKAshdqTKCjVk23cLoD6lrQPohRQrSjR9G6n9osa2Lpr45ZUEwHB8CIUgKGoehBKgYTRJPX8JO4TMkhDUJeNjeNOBkISDyPC6zwvYRbtDB640k2UwomqAgioKg+Tm7idO9UGqCzeNvRkaYVAAehRqAswgDAqCA7gYbB+GaG9YHYYAZkhzEgJ4gL8aoa9NKJpGoDRjGsZxiA8dhwniaDWGAFYKap6HYagBnEeRlnMex3Gry5hGSbBgA2QWaNA2mHzFpnJbZmXae5hWqAAFhV6m1dhzXkeZ9GpfZzmwbFhF31hgB2OapuFgmEaZ1HrZ1jnZbB+n5d5sHiOIt31o9umLat1npf92mg6Jg2AA4I+aqPRa9y3tfju3o+Dp2wYATnT-qzbBjXs59uPbYDgvk5DqhiIhpN3Zp83q9jm3dc75Pgah2jcEHGgqDATg7WdfwMkMcCCCgABrCAQCoIIXUjKBB5m7penCWfjEUSJtQINgaCCTEMEmyOh6gafxkTsXeguWZxlh3o0Gwch1NCWZIjmXPbaKBZtPFmqg5Y0Cfp+WYoCVBvz6J-b+NBoHoz-kGLekoTa8WHqPceYFr5RlwEjRQQA):

```typescript
type Join<S extends any[], D extends string> = string[] extends S ? string : S extends [`${infer T}`, ...infer U] ? U[0] extends undefined ? T : `${T}${D}${Join<U, D>}` : '';
```

As well as a somewhat convoluted `KebabCase<>` which can turn camel case to kebab case.

**Comment by sindresorhus** [comment]
These are super cool and useful. PRs welcome for at least camelcase, kebabcase, and trim. We can expose the helper utilities later on after more discussion.

**Comment by sindresorhus** [comment]
@voxpelli Do you happen to know whether TS 4.1 will make it possible to correctly get types for key paths? For example, `get(object, 'foo.bar')`, like https://github.com/sindresorhus/dot-prop.

**Comment by sindresorhus** [comment]
Actually, I found an example of how to do it. Moving this to a new issue: https://github.com/sindresorhus/type-fest/issues/147

**Comment by knpwrs** [comment]
I commented over at https://github.com/microsoft/TypeScript/issues/40710#issuecomment-732229720, but I figure I'll put this here as well.

The latest iteration of the `CamelCase` type proposed here cannot properly handle strings which start with a separator or have multiple separators side by side. Example:

```ts
interface KebabCased {
    "-webkit-animation": string;
    "--main-bg-color": string;
    "something--else": string;
}

// Becomes
// {
//    Webkit: string;
//    '': number;
//    something: string;
// }
type CamelCased = CamelCasedProps<KebabCased>;
```

See [this updated playground](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201029#code/C4TwDgpgBAymA2BLYAeGUIA9gQHYBMBnKQ4AJ0VwHMAaKAEQ2zyJPMqoD4oBeAKCiC2FakxwFi6APzCOAbQC6UAFwCh6LONYBybVBmKVawRuYSoAAwAkAb0oAzCGSgAVAL636Hu7kfOAqm4W+lByLnQAdFFwSKj+dPScSqpCoTAKANx8fKCQUPYA9gW8sAjIKABEhQUAtABGAIZkFXQVNRWcOeDQMcgA8rgA6gVk+DAQYE0NwCMoLmIsxKQiXCW9qOFQbRUAPhUA+rsVW5xZudD+BBD2lBD4LgUAogC2YKAw7NRzC+bLHNw8Vw-VgAVyuN1wdxCFWOylcZ26UAAwg1nhB4CjCBAPisAIJkMgNEAoADSwKWnyoigBllsJLkAAYFN4UWBkA0kAAvCAoS74a63e5PV7vSmkuQARgUnE4QQReRRaIxDSxpJpZM0i1kohkivRmOxlPxhOJ6wGw1G40mhJmZDV3DhJPl0GqAGYSnrlaqqkV6k0OhkoAB6INQABCEAAxgU0cQfQUw-6unlqgBWD2o-UqnnxqCNZqnYOhiPR2NbaqJ5rJl1FABsGaVBsq1X2+YDRfDUZjEDjFaT53yRQALA2s97qm3CyHO6We+Wim3sgPPQb8AAFMgFMCEOY0mzGUJkyhQADWEBABXsQJVyMzXp5JKScJcchJCj4biyfEoODI9gakbQCSECNHUq5QPuqRtAA7iBJ7IDUDS4IgzzTIgBS4BUcJ-NQWRQTUNSoZQ9RUDU0bwCMWHalQeFCBUhDdsAAAWHAEeiWJUThNEftk04lt2hB8NO+7TkIgxwcg2GUlkomCLocK4CCzx1E4MmhkIDFosxHBSSsalQG41a3o22b4KO97rpu26kiBDRgaZpx8EAA).

I was working on my own `CamelCase` utility type as well. It handles those cases, but it's far less generic than what you've come up with.

```ts
type Separator = ' ' | '-' | '_';

type CamelCase<T extends string> =
  T extends `${Separator}${infer Suffix}`
  ? CamelCase<Suffix>
  : T extends `${infer Prefix}${Separator}`
  ? CamelCase<Prefix>
  : T extends `${infer Prefix}${Separator}${infer Suffix}`
  ? CamelCase<`${Prefix}${Capitalize<Suffix>}`>
  : T;

type CamelCasedProps<T> = { [K in keyof T as `${CamelCase<string & K>}`]: T[K] }

type SnakeObject = {
  '-webkit-animation': string;
  '--main-bg-color': string;
  'something--else': string;
}

// Becomes
// {
//    webkitAnimation: string;
//    mainBgColor: number;
//    somethingElse: string;
// }
type CamelObject = CamelCasedProps<SnakeObject>;
```

See [this playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAyhYEMBODgHslQLxQOR6gB88BafY3AfVwG4AoO0SKAYQQFsIAbNgZwgA8AFSgQAHsAgA7ACa8ovYEgCWUgOYA+bHShQR4ybPkADACQBvOIhTokAXwuqAZhEwwArk6fKxd4zqgAflYObj5BDy8fDQCALj1RCWk5KDNzZ1coAAUkCG9fCytkVAw-AOC2Th4EfgEcvOi4hINkk0cpF0x6-IdLeGLbXoy3Tx7-XQrQ6tq07p9etjBlYAQuZQAvCNHovxjdeKF6RnBoSrCaiBkctDBeYS0ccygAbQBpKFUoAGsIEDQnBI1VIWM7TQSKFTqKAAMigrw0fgAugc3oioHYGExoDApAgfgB5ABGACsIABjYDYKDmAK4EgAdwghK+yxICCkynYqGUaCkuHiENUanoujpJC5qhIhLUJDJaC4GH5CiUQpFeF4aE4wAAFkKSCRuPwlYL1PQMXQAPQWqAAIXJmogvEt1ppVt0ukZzOWAEEOVzgDypAKVabne6oBKpDa1Cx5Rh4lJ3OxCa56G73Rqtbr1ABRLj8YOQ4VhjFYkJVImkilU0HhK5IG53HF4iCV8nADQ0IA).

**Comment by voxpelli** [comment]
@knpwrs I have an updated version that I’ll upload to https://github.com/sindresorhus/type-fest/pull/138, hopefully later today

**Comment by kdmadej** [comment]
I ran into an issue with the current (`v0.20.2` at the time of writing) implementation used by this project: when feeding in some strings into the `CamelCase` utility type I end up with a union of possible results, i.e.:
![image](https://user-images.githubusercontent.com/2098250/107793060-2e84c400-6d56-11eb-98ea-fc34b21373d4.png)
`CamelCaseTF` is just a renamed import of `type-fest`'s `CamelCase`

I came up with my own [implementation](https://gist.github.com/kdmadej/c3e016bcc17f7803abe32d3923ed84f1) but it results in:
```
Type instantiation is excessively deep and possibly infinite.ts(2589)
```
error for strings that are longer than 15 characters 😞 

Not sure which is worse but I can make a PR if you guys would be interested in the other approach 😅

**Comment by sindresorhus** [comment]
@kdmadej Would you be able to submit a pull request with one or more [failing tests](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests)? That would help getting this fixed faster.

**Comment by mikestopcontinues** [comment]
IsoDate, IsoDateTime, IsoDateTimeUTC, etc.

```ts
type Int = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 0;
type Month = `0${Int}` | `1${0 | 1 | 2}`;
type Day = `${0 | 1 | 2}${Int}` | `3${0 | 1}`;

type IsoDate = `${Int}${Int}${Int}${Int}-${Month}-${Day}`;
```

This can clearly get pretty hardcore. Maybe just limit it to `ParsableDateString` and `ParsableDateArray`?

**Comment by danielo515** [comment]
Where do you get such great knowledge about TS types?

**Comment by mikestopcontinues** [comment]
@danielo515 The TS docs, but especially the release notes. That's where the cutting edge stuff happens, and a lot of it never actually makes it into the docs themselves.

**Comment by vicary** [comment]
Not sure if this is possible with released types, but I would really love to see `OmitPrefix` here.

```typescript
export type ExcludePrefix<T, U extends string> = T extends `${U}${infer _K}` ? never : T;
export type OmitPrefix<T, K extends string> = Pick<T, ExcludePrefix<keyof T, K>>;
```

**Comment by fregante** [comment]
It seems that a lot of these have been implemented. If some haven't, it's best to open dedicated issues for each.
