### ISSUE TITLE
Proposal: `ArrayTail`

### ISSUE THREAD

**Issue by rifler** [sindresorhus/type-fest#135]
```ts
type Tail<T extends any[]> = ((...args: T) => any) extends ((_: any, ...args: infer P) => any) ? P : [];

Tail<[1, 2, 3]> // [2, 3]
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/135">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/135/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/135/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
What's the real-world use-case?

**Comment by rifler** [comment]
for example some of latest release of got brokes many of our types, changed type of `context` field
lets patch some of the types

```(ts)
import { BeforeRedirectHook as GotBeforeRedirectHook, NormalizedOptions } from 'got';

type PatchedNormalizedOptions = Omit<NormalizedOptions, 'context'> & {
    context?: YourType;
};

type BeforeRedirectHook = (options: PatchedNormalizedOptions, ...args: Tail<Parameters<GotBeforeRedirectHook>>) => ReturnType<GotBeforeRedirectHook>;
```

here I overrite first argument and use Tail to add original arguments to the end

**Comment by sweetliquid** [comment]
```ts
type Tail<T extends any[]> = T extends [any, ...infer P] ? P : []
```
I like this.

**Comment by Narretz** [comment]
I've used tail to create a function signature without the first argument for curried functions.

**Comment by sindresorhus** [comment]
This is accepted. I think `Tail` is too ambigious. Should be `ArrayTail`.

We actually already use this internally: https://github.com/sindresorhus/type-fest/blob/7950542f8fd001cae65a8fe76f467edd30cdd937/source/internal.d.ts#L109-L112
