### ISSUE TITLE
Can I just install with devDependencies instead of dependencies?

### ISSUE THREAD

**Issue by lvdang** [sindresorhus/type-fest#136]
Can I just install with devDependencies instead of dependencies? 

e.g.
 npm install type-fest --save-dev

**Comment by papb** [comment]
If you're not authoring a module that ships its own typescript typings, then yes. Are you? How are you using `type-fest`?

**Comment by lvdang** [comment]
I am using in development, but using webpack bundle 'ts-loader' to convert to .js files on production.

**Comment by papb** [comment]
Since you're not creating a library for other developers to use, you can use it as a dev dependency :+1:

**Comment by lvdang** [comment]
thanks
