### ISSUE TITLE
xo currently fails when installed with yarn 1.x

### ISSUE THREAD

**Issue by voxpelli** [sindresorhus/type-fest#137]
**Error:**

`Error: Failed to load config "xo-typescript" to extend from.`

**Likely reason:**

`eslint-config-xo-typescript` gets installed by yarn as a sub-dependency to `xo`, but `eslint-config-xo` gets hoisted to the top, so when `eslint-config-xo` looks for `eslint-config-xo-typescript` it can't find it, because it is only to be found within `xo`.

It works well with npm.

**Possible fix:**

I guess peerDependencies? Not really sure why it hoists one and not the other though, it should really be hoisting both 🤔 Was the solution suggested in eg. #454 as well.

**Comment by sindresorhus** [comment]
> so when eslint-config-xo looks for eslint-config-xo-typescript it can't find it, because it is only to be found within xo.

`eslint-config-xo` doesn't require / look for `eslint-config-xo-typescript`.

> It works well with npm.

Sounds more like a Yarn bug then.

**Comment by voxpelli** [comment]
> `eslint-config-xo` doesn't require / look for `eslint-config-xo-typescript`.

Right, where is it included then?

> Sounds more like a Yarn bug then.

Maybe, but I have never run into this in any other repo, so it's something about how the dependency tree is set up versus how it is used that makes it fail. Right now I don't know enough about `xo` to say, what I do know is that it made it unnecessarily hard to try to contribute, so I would love to help fix it so that the bar to contributions gets lower.

**Comment by sindresorhus** [comment]
> Right, where is it included then?

XO have both of them as dependencies: https://github.com/xojs/xo/blob/33b769ec71498f4c788fe01e17c043908ad0205d/package.json#L61-L62

And XO uses both of them as `extends`: https://github.com/xojs/xo/blob/33b769ec71498f4c788fe01e17c043908ad0205d/lib/options-manager.js#L435

**Comment by sindresorhus** [comment]
Actually, looks like this is https://github.com/xojs/xo/issues/483

**Comment by voxpelli** [comment]
Great, added a lengthy explanation of why this happens after doing some debugging: https://github.com/xojs/xo/issues/483#issuecomment-722618023

Closing this as it duplicates that, better to keep it collected in one place.
