### ISSUE TITLE
[Proposal] SetNonNullable

### ISSUE THREAD

**Issue by xenoterracide** [sindresorhus/type-fest#144]
I honestly thought `SetRequired` did this. example of expected behavior

```ts
type Optional<T> = T | undefined | null;
type Foo = {
   bar: Optional<string>;
   foo?: string | null;
   baz?: string;
};

type NonNullableFoo = SetNonNullable<Foo, 'bar' | 'foo'>;

// would be equivalent to

type ManualNonNullableFoo = {
   bar: string;
   foo: string;
   baz?: string;
};
```

**Comment by sindresorhus** [comment]
> I honestly thought SetRequired did this.

⬇️ 

> Create a type that makes the given **keys** required.

**Comment by sindresorhus** [comment]
This seems useful though. I wonder if we could just overwrite the built-in `NonNullable` version with a more powerful one that also accepts which keys to apply to, as discussed in https://github.com/sindresorhus/type-fest/issues/171.

**Comment by papb** [comment]
@sindresorhus However, note that `SetRequired` does more than just mark the given keys as required - [it also strips `undefined` from them](https://github.com/sindresorhus/type-fest/issues/171#issuecomment-747824197).

**Comment by joealden** [comment]
I believe this can be closed now that https://github.com/sindresorhus/type-fest/pull/431 has been merged?
