### ISSUE TITLE
How to use `JsonObject`?

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/type-fest#15]
```ts
const json: JsonObject = await fetchJson(...);
console.log(json.a.b.c);

// => error TS2339: Property 'b' does not exist on type 'string | number | boolean | JsonObject | JsonArray'.
  Property 'b' does not exist on type 'string'.
```

It seems to be useful for one-level JSON, but after that you'll have to use `as JsonObject` at every level, if you want to access a deep property (e.g. GraphQL response)

**Comment by sindresorhus** [comment]
It types the response as strict as it possibly can without knowing anything about it other than that it's JSON. For example, `json.a` could be `null`, in which case, `json.a.b` would not exist.

**Comment by bfred-it** [comment]
> `json.a` could be `null`, in which case, `json.a.b` would not exist

GraphQL guarantees that already, if you check for `json.errors` first. How am I gonna type this? 😰

```ts
let authors: Author[] = json.repository.pullRequest.commits.nodes.map(node => node.commit.author); // from Refined GitHub
```

**Comment by BendingBender** [comment]
I think this type is useful for APIs that want to accept only JSON-like structures, it is not really useful as a response type. There you usually have an idea of how a response is structured.

For your specific example, how should TS know something about the semantics of GraphQL? If you already know the shape of your response, why do you want to use `JSONObject`?

**Comment by bfred-it** [comment]
It seemed to make sense that a `fetchApi` would return a `JsonObject`, but it's hard to even cast that as something else (see `as UserInfo` in the commit above) because each level "could be string or null", so in most cases you'd have to cast `as unknown as UserInfo` at best, which means `JsonObject` is lost instantly.

In the specific case I'm ok with the code throwing if a level isn't there, so the error isn't swallowed by some `if levelX !== undefined`

**Comment by BendingBender** [comment]
I think it just doesn't meant to be used like this. This is only useful for APIs like `JSON.stringify` and the like.

**Comment by sindresorhus** [comment]
I think we should document in the type that it's not meant as a response type, but rather to make certain input strict.

It could maybe also be useful as a super-type for response types. So you do `CustomResponseType extends JsonObject { … }` to ensure you don't accidentally use non-JSON compatible types. Thoughts?
