### ISSUE TITLE
Proposal: `MergeDeep` type

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/type-fest#150]
See https://github.com/sindresorhus/type-fest/pull/94 for the initial attempt.

**Comment by Isabellarossi** [comment]
Uppercase
Lowercase
Capitalize
_Uncapitalize****_

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see https://github.com/sindresorhus/type-fest/pull/164 and the feedback given there.

**Comment by sindresorhus** [comment]
We have this now: https://github.com/sindresorhus/type-fest/blob/main/source/merge-deep.d.ts
