### ISSUE TITLE
Bug: 0.20.0 fails to compile under yarn2 pnp

### ISSUE THREAD

**Issue by leaumar** [sindresorhus/type-fest#151]
Renovate-bot attempted to upgrade type-fest to 0.20.0 during the night. The CI build fails with the following:

> tsc -b 
> .yarn/cache/type-fest-npm-0.20.0-9c17c80bf4-420f4bc536.zip/node_modules/type-fest/ts41/camel-case.d.ts(1,30): error TS2307: Cannot find module './utilities' or its corresponding type declarations.
> .yarn/cache/type-fest-npm-0.20.0-9c17c80bf4-420f4bc536.zip/node_modules/type-fest/ts41/delimiter-case.d.ts(1,51): error TS2307: Cannot find module './utilities' or its corresponding type declarations.

Typescript 4.1.2
```json
{
    "compilerOptions": {
        "incremental": true,
        "module": "commonjs",
        "noUncheckedIndexedAccess": true,
        "strict": true,
        "target": "es2020"
    }
}
```

**Comment by sindresorhus** [comment]
Can you try out https://github.com/sindresorhus/type-fest/releases/tag/v0.20.1 ?

**Comment by sindresorhus** [comment]
@voxpelli Any idea why the `tsc` run didn't catch this?

**Comment by leaumar** [comment]
Build passes with 0.20.1, thank you

**Comment by voxpelli** [comment]
@sindresorhus The `tsc` isn't run on the ts41 folder as then it would fail on all the older TS versions, but the `tsd` should have caught it as its run on all files 🤔

**Comment by sindresorhus** [comment]
@voxpelli Ah yeah, my bad. I disabled `tsd` because it was failing on the normal tests. `tsd` will soon support TS 4.1. So I think we can just leave it until then.
