### ISSUE TITLE
Is the `Class` type misnamed?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/type-fest#155]
https://github.com/sindresorhus/type-fest/blob/951a21130bfbd3b605a0b28f9677fe1874653b5b/source/basic.d.ts#L20

Should it be named `Constructor` instead?

See: https://github.com/microsoft/TypeScript/issues/20256

**Comment by kainiedziela** [comment]
It should! But maybe `Class` type should be added as well.

**Comment by sindresorhus** [comment]
Yes, I think that would be useful too.
