### ISSUE TITLE
PackageJson - recommendation for extending the interface

### ISSUE THREAD

**Issue by dylang** [sindresorhus/type-fest#16]
The package.json definition is a great start, but going to be impossible to include everything.

We can make PR's for every field that is missing (yarn is missing `workspaces`, for example), but this could become never-ending, such as supporting `package.json`-based config for `jest`.

Instead, maybe it would be useful to document how we recommend developers extend the existing definition to add types they need for their code.

I'm still learning TypeScript, so I'm not sure if the best practice is for developers to provide extended properties in a global PackageJson namespace in a `d.ts` file, or use generics to pass in someting like `PackageJson<extraFields>`.

Thoughts?

**Comment by BendingBender** [comment]
If I want to extend a type I would usually use `extends` as the canonical way of extending an interface:
```ts
interface MyPackageJson extends PackageJson {
	foo: string;
}
```
You could achieve the same with intersection types:
```ts
type MyPackageJson = PackageJson & {
	foo: string;
}
```
Generics are usually used when there is a known filed of varying type, not to extend interfaces.

Not sure whether this is something we should document, this is a very basic TS beginner topic. When you start using type-fest I'd assert some basic knowledge of TS.

**Comment by BendingBender** [comment]
> We can make PR's for every field that is missing (yarn is missing `workspaces`, for example), but this could become never-ending, such as supporting `package.json`-based config for `jest`.

I think there is a value adding this kind of types when there is some need in the community. I wouldn't add every single extension to `package.json` out there but common ones would surely make sense.

**Comment by sindresorhus** [comment]
> Not sure whether this is something we should document, this is a very basic TS beginner topic.

Better leave that for the TS docs.

> We can make PR's for every field that is missing (yarn is missing workspaces, for example), but this could become never-ending

@dylang Can you check what other Yarn fields we're missing? We should at least be complete with that.
