### ISSUE TITLE
Add Transparent to reverse Opaque

### ISSUE THREAD

**Issue by willium** [sindresorhus/type-fest#165]
Opaque nominal types are incredibly useful, but there are times where you need to un-opaque a type ignorer to use it (e.g. as a key in an object).

I propose the addition of
```ts
export type Transparent<T> = T extends Opaque<infer O, any> ? O : T
```

fails now:
```ts
type MyId = Opaque<string, "MyId">
type Nums = Record<MyId, number>
```
> Element implicitly has an 'any' type because expression of type 'Opaque<string, "MyId">' can't be used to index type 'Record<Opaque<string, "MyId">, number>'

but this would fix that error without completely making Opaque types useless or overly compromising their contract:
```ts
type MyId = Opaque<string, "MyId">
type Nums = Record<Transparent<MyId>, number>
```

**Comment by sindresorhus** [comment]
Yeah, this sounds like a useful type to me.

---

Note that generalized index types are planned for TS 4.2, which *might* (did not test, just looked relevant) solve your specific problem: https://github.com/microsoft/TypeScript/pull/26797

**Comment by sindresorhus** [comment]
// @voxpelli @kainiedziela Thoughts?

**Comment by voxpelli** [comment]
Makes sense to me 👍 Seems like a good addition, to be able to go both ways.

Is the name “Transparent” the best or would “DeOpaque”, “UnOpaque” or similar maybe show a clearer connection between the two and make it easier to find and understand + “pollute” the overall exports list a bit less? Even though such a wording might be linguistically less than ideal

**Comment by sindresorhus** [comment]
I was thinking about `DeOpaque` too for the same reason. Not as pretty as `Transparent`, but definitely clearer.

**Comment by willium** [comment]
could do `Translucent` 😉 

excited to see this land! and didn't know about the generalized type update in 4.2, looking forward to that!

**Comment by sindresorhus** [comment]
Some other alternatives:

- OpaqueValue
- OpaqueRawValue
- UnwrapOpaque
- OpaqueUnwrapped

**Comment by kainiedziela** [comment]
I'm a fan of `UnwrapOpaque`, less of a tongue-twister than Un- or DeOpaque

**Comment by ulken** [comment]
If it ends up standing between `Un` or `De`, this might be worth considering: https://english.stackexchange.com/questions/25941/is-there-a-general-rule-for-the-prefixation-of-un-and-de-to-words

**Comment by willium** [comment]
IMO the best naming convention would be to deprecate `Opaque`
and use one of the following:
- Tag<U> and Untag<U>
- Brand<U> and Unbrand<U>

**Comment by ulken** [comment]
I got it!

_Unpaque™_

As in _unpacking an Opaque value_.

**Comment by ulken** [comment]
On a related note: https://spin.atomicobject.com/2018/01/15/typescript-flexible-nominal-typing

**Comment by sindresorhus** [comment]
Then I suggest we go with `Brand` and `Unbrand`.

**Comment by voxpelli** [comment]
And maybe keep Opaque as an alias for a version or two? Adding `@deprecated` to it?

**Comment by sindresorhus** [comment]
Yup

**Comment by sindresorhus** [comment]
Actually, maybe we could make the `Opaque` type actually opaque? And the existing implementation could be `Brand`.

I found this in some random TS playground:

```ts
declare const USERID_SYMBOL: unique symbol;
declare const ITEMID_SYMBOL: unique symbol;
declare const TAG_SYMBOL: unique symbol;

type Opaque<T, U extends symbol> = T & { [TAG_SYMBOL]: U };
type UserId = Opaque<number, typeof USERID_SYMBOL>;
type ItemId = Opaque<number, typeof ITEMID_SYMBOL>;
```

Any thoughts on this approach?

Since it uses a unique symbol, it should be completely opaque as long as the symbol is not exposed.

**Comment by ulken** [comment]
Is there any difference between _nominal_ and _opaque_ types? https://github.com/microsoft/TypeScript/issues/202

**Comment by ulken** [comment]
> Actually, maybe we could make the `Opaque` type actually opaque? And the existing implementation could be `Brand`.
> 
> 
> 
> I found this in some random TS playground:
> 
> 
> 
> ```ts
> 
> declare const USERID_SYMBOL: unique symbol;
> 
> declare const ITEMID_SYMBOL: unique symbol;
> 
> declare const TAG_SYMBOL: unique symbol;
> 
> 
> 
> type Opaque<T, U extends symbol> = T & { [TAG_SYMBOL]: U };
> 
> type UserId = Opaque<number, typeof USERID_SYMBOL>;
> 
> type ItemId = Opaque<number, typeof ITEMID_SYMBOL>;
> 
> ```
> 
> 
> 
> Any thoughts on this approach?
> 
> 
> 
> Since it uses a unique symbol, it should be completely opaque as long as the symbol is not exposed. The `TAG_SYMBOL` part will require https://github.com/microsoft/TypeScript/pull/26797, but we can just use `__opaque__` for now.

Here's a discussion around all that: https://stackoverflow.com/a/56749647

Throw in a `readonly` also?

**Comment by sindresorhus** [comment]
Through https://github.com/microsoft/TypeScript/issues/202, I also discovered another [apporach](https://github.com/andnp/SimplyTyped/blob/85fb9cdb7655ac921f38f6e21027dc27d76dcf80/src/types/utils.ts#L30-L41) for `Brand` (our current `Opaque`):

```ts
declare class Tagged<N> {
	protected readonly __opaque__: N;
}

export type Brand<Type, Token = unknown> = Type & Tagged<Token>;
```

The benefit here over our current approach is that the `.__opaque__` property cannot be accessed here.

Not sure if we could make `protected` => `private`.

**Comment by sindresorhus** [comment]
> Throw in a readonly also?

Sure
