### ISSUE TITLE
ConditionalKeys didn't work fine as expected

### ISSUE THREAD

**Issue by iakoug** [sindresorhus/type-fest#166]
```
import {ConditionalKeys} from 'type-fest';
interface Example {
	a: string;
	b: string | number;
	c?: string;
	d: {};
}
type StringKeysOnly = ConditionalKeys<Example, string>;

```
## Expect to be `'a'` but get `'a' | 'c'` actually 

```
export type ConditionalKeys<Base, Condition> = NonNullable<
	// Wrap in `NonNullable` to strip away the `undefined` type from the produced union.
	{
		// Map through all the keys of the given base type.
		[Key in keyof Base]:
			// Pick only keys with types extending the given `Condition` type.
			Base[Key] extends Condition
				// Retain this key since the condition passes.
				? Key
				// Discard this key since the condition fails.
				: never;

	// Convert the produced object into a union type of the keys which passed the conditional test.
	}[keyof Base]
>;
```
ts version: 4.0.3

why...
![image](https://user-images.githubusercontent.com/24563265/101586238-79afed00-3a1c-11eb-9527-69ea7ea02812.png)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/166">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/166/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/166/pledge.svg">
</picture>
</a>

**Comment by ClickerMonkey** [comment]
Is your project configured for strict null checking?

**Comment by justwink** [comment]
> Is your project configured for strict null checking?

... The project was forked from the repo. There was no other configuration. 
Is it still possible to be configured somewhere?

**Comment by sindresorhus** [comment]
This project uses strict null checking. I have confirmed the findings.

**Comment by sindresorhus** [comment]
This is really weird.

```ts
interface Example {
	a: string;
	b?: string | number;
	c?: string;
	d: Record<string, unknown>;
}

declare const exampleConditionalKeys: ConditionalKeys<Example, string>;
expectType<'a'>(exampleConditionalKeys);
```

Correctly results in `'a'`, but going through a `type` does not:

```ts
interface Example {
	a: string;
	b: string | number;
	c?: string;
	d: {};
}
type S = ConditionalKeys<Example, string>;
declare const exampleConditionalKeys: S;
expectType<'a'>(exampleConditionalKeys);
```

// @kainiedziela Any ideas?

**Comment by sindresorhus** [comment]
// @ifiokjr

**Comment by justwink** [comment]
> This project uses strict null checking. I have confirmed the findings.

There has no `"strictNullChecks": true,` in tsconfig.json and  `"extends": "@sindresorhus/tsconfig"` either. How can I confirm that.

**Comment by sindresorhus** [comment]
`@sindresorhus/tsconfig` has `strict: true` which sets `strictNullChecks: true`.

**Comment by justwink** [comment]
Thanks, got it.
