### ISSUE TITLE
[Proposal] Adding in my types

### ISSUE THREAD

**Issue by ClickerMonkey** [sindresorhus/type-fest#168]
Howdy!

I've accumulated a few useful types while I've been working on TS libraries. If you find any of them useful, feel free to integrating them into your library. 

https://gist.github.com/ClickerMonkey/a081b990b9b14215141fb6248cef4dc4

I don't have the bandwidth to contribute further, but I hope you might consider some of these.

Thanks

Phil

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/168">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/168/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/168/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
Thanks for sharing. I'll take a closer look when I have some time.

Anyone else reading this, feel free to open a new issue to propose any of those types if you find any of them useful.
