### ISSUE TITLE
Fix Union type with DeepMap?

### ISSUE THREAD

**Issue by rnnyrk** [sindresorhus/type-fest#169]
Hi there,

I'm nt sure if I do understand your examples correctly. But I have the following types:

```typescript
export type StartEndType = {
  start_date: string;
  end_date: string;
};

export type PayrollContract = StartEndType & {
  type: 'ON_PAYROLL';
  yearly_holidays: number;
};

export type FreelanceContract = StartEndType & {
  type: 'FREELANCE';
  hourly_rate: number;
};

export type Contract = PayrollContract | FreelanceContract;
```

Is it possible to fix this DeepMap issue which isn't supported by TypeScript out of the box?

```
Property 'yearly_holidays' does not exist on type 'DeepMap<PayrollContract, FieldError> | DeepMap<FreelanceContract, FieldError>'.
  Property 'yearly_holidays' does not exist on type 'DeepMap<FreelanceContract, FieldError>'.
```

I was looking at `ValueOf` or `LiteralUnion`, but not sure if I do understand it correctly. 

In my component it looks like:

```javascript
{contractType === 'ON_PAYROLL' ? (
  <Number name="yearly_holidays"  />
) : contractType === 'FREELANCE' && (
  <Number name="hourly_rate" />
)}
```

When I hover contract, it knows that it's one of `ON_PAYROLL` or `FREELANCE`.

Thanks in advance.

**Comment by sindresorhus** [comment]
We don't have a `DeepMap` type. Are you sure you opened this issue in the correct repo?
