### ISSUE TITLE
Asyncify lost the general return type

### ISSUE THREAD

**Issue by linonetwo** [sindresorhus/type-fest#178]
I have a 'get' method like this:

![Screen Shot 2021-01-23 at 23 33 11](https://user-images.githubusercontent.com/3746270/105606278-5e821c80-5dd3-11eb-9fc0-4c0c65c83700.png)

And I Asyncify it through this:

```ts
/**
 * To call services that is located in main process, from the renderer process, we use IPC.invoke, so all method should now promisify
 * Note this type only promisify methods that return things, not methods that returns observable.
 */
type AsyncifyProxy<OriginalProxy, K extends ConditionalKeys<OriginalProxy, Function> = ConditionalKeys<OriginalProxy, Function>> = {
  [P in K]: Asyncify<OriginalProxy[P]>;
};
```

Then the result lost the type:
![Screen Shot 2021-01-23 at 23 34 06](https://user-images.githubusercontent.com/3746270/105606302-7eb1db80-5dd3-11eb-8cb6-f3d0f8545748.png)

I can see it don't allow the general type now:

![Screen Shot 2021-01-23 at 23 38 15](https://user-images.githubusercontent.com/3746270/105606401-216a5a00-5dd4-11eb-9267-f94169d99d75.png)

it used to know the return type based on the input...

![Screen Shot 2021-01-23 at 23 35 13](https://user-images.githubusercontent.com/3746270/105606328-a7d26c00-5dd3-11eb-927a-8e01ab566f5a.png)

Is it possible to solve this?

https://github.com/sindresorhus/type-fest/blob/main/source/asyncify.d.ts

**Comment by sindresorhus** [comment]
// @papb

**Comment by linonetwo** [comment]
Playground here:

[Playground Link](https://www.typescriptlang.org/play?#code/FASwdgLgpgTgZgQwMZQAQAUYHsUGdcBqsuIWYuqA3sKqgBYQQAOA+kwjLrAFyq4QxwAcwDcNVGCwATKL36Cwo8QDcAHHIHCxtDlFwaFS2gFdlBreIBeAGxAAjc4u2oAttOPW9jo6ixMo5LjW3mIAvsDAUAAeTFgwEKjg0PDIaACS6AgQdBTUtABKAKIAggDCACos6MXlABIh4uVpACLNADIAmgDqaQDSaSzlhQCy6G01hSwAYgDybc2F+VU19XyaTo0t7YsAyst1DbRppTMAcvur8ha0pbX5M8OTi-dL1Qdrhs4LO73lM+gXQ6oNozADi0zmC3yQJBpWKbTSAC0amkzhD5osGuEAPQAKlxNFxqGKygQIGsCDsnlQpOsxj0qEpWGMCRgxjAYGEqACyhA2DALgCEEJ2MiMTiCSSsEQKFQxzI-AQkFy4hAuGaUGUUGsfkFkF4diwWE8SucTApEDgcRcQIQTCYRE4pDAtvtpwQgqBWB2jpIZCBPL5ZD1EF9zv0GGweEIxHDYQi0Vi8USkGlqTlpTI0CiCWi0DAUgoGSyOQANBmFRAlRBcqhwsA8QTUEThkqEEI0EhK9WaQg6WhbABrNAAAzVGq1OqYIZHjILriVAE9udYuOXcFhUIvmagkErUIPJAB3RmGlmn5ms9mcxTcsC8-khlML8BzqSoGABGSfmCoJhRvQKCgBASGsRcADoRTFJNJVTFJZXlVMcx2WBeVlPJUA7CAAB5em5HMvwoYdtzgCskIgAA+AAKYjeF6ABKXhEOzCAAG1egAXXjCIIkbYBChzGBkASbI0GIig4GwFxGVQCBF38VAjzoWA0FE3t+1k+S0CwUi1OI-D80LWTlMwkAtTAVAR0zAsQAgZ0R0g4A0jgsA+zA4y1USChjC4d8rV-NSrLIKRbOdPt0BAJBB1nJV3yCmy7LIPsBJQJgIFnOT-FwRyAAFog9c0oGAEcStAFwYKoayQsS1zrF6KBF1wUJUEkrBpIAckyqAAFo4D0CB2rEUA4JlNABIK6kMIQIEHA+LkAB8JGMFw7FgZwkAAfiBKReEoUJuK61AdnWIR6samYwHcgBeVAqtCpK6oa3BsPG8rPHXE6KLEbFsSuijUHahB2uK0rgHKTdcGMe0JT-Dg7L7TSsvLFwEGHPhjE-LdmV-eLqvsryZPZZ1fFI9kZDgcAoHfKj-PwiaoHLEcrlvRayagCmwCpkd6MZCgZDccgBCyKnUFWnUj1y-K3qKkqR2AQ7jsMM7cGKAsAFUC3Zyn3xuu6ar7ZWXqiemPsMVBWc1jmqa+htfv+wH2vNgGkGB2XgFxUVExhw69bCx7GuwgAhECGdu4L7rAf6btOMhTg8CkqSgbDxB+1AuiEphnxHGOwDj6wE88DKIc0TOECPBBl0CtmrakDKtJaqTjLQf93BQd8ibISDaAw2hU9bTPsmwYwhDoRl86bg8npJiehDMgJRZDxGoC72hUHYhrn2InTUGDrgOO4cRe+xDBIsHXxLuXcTFNs0euqAgibNvNTZ-MyzfbIOv-BX2hd6gdfFw4gZQiYcErOkPqgVO+QoBVlfNkTy+kSBgFlGpLsoCyCw3wHob+qANqoDOuA1OzQ1R7hgO+OBREN6IOQSZVBeN0GIHJNlcBvBOZahgENVeEDj7WTYSJEyLcpDGDbr4OwAArKASBYIQE3AgVAHcLKHW3npKeSlIqj3YJgshNDw762sLJfqK9QisS3qRX+HFgA2z4qUT8ws5y80XEgmksZ0FKJMi-eecB2SSOJl1csdhlyGiiFyNSn4IAYwUfXV8I5MBtTVFAWcqjqTDigEwYJJlcAembhwTJyQl5MOAGrLg3U9xcF4B0HcdAEBalkkeTcnikE1VwOWMgaBcAOKQHQfkzIKCxXPmgEC7TOlkG6cZLIqApCbjUhkwUHlFDgTlILYC75t6VN5E-TcgjzSRVsWpQ65NwAR3LNuYwu59w+VHMUNpSCQBwEXEXD8UBzkTyuR0rpPkl6S2NtLEGcsQDlRhpQS57SbmLmaq1DqXVer9UGrxY+OxBlvIkl4mqkF6nePQVhKYRp4VIKohuQUxQYBCF4DsNqUByhaUYqgLFm4MKp0AGQEwB6yHSBdcimVMaWgmgbkm6rKkAguwl1bemLsXtMsXbJexIXk3JAByo0XLGCwFQDdPFZLCXEqOmSil-geZ-UjLErg2EaU21tkdTJvNLIiu9O02cdhzwDKQUMyQPlIKoP4JhaBNK+W8D5TKuVWAFU8tQKqglRLdX-TpcfbVUAdhIEEGlCQWATyHiTRQbIYymZqqJbOTyI5SWCmjTFFkbUsjbPzhBFOx80gJD7BuA8x402VL4Z5NFNVXA+VZNA8JlkYkuDiUao0FEHKVrlKRY59AqmjhynfONIA0rdT0LYSA2IW59qKa2503UHVIFnEu3JbJqQBEpJ4KQ5ZbLX3Hpqeen4KrpoSAAIimMi8MozO1hJgBZVdcSKAuA7aLfpLzwL3sckfVAjLwhuw9tBb29dfW3KNRZPMwCqLgVQxwIQEYlysQ4uGuci4o5HWgVA99YBo0IfLL2-tlGuAED7PSbCxHwlkamJHCibGxCHTSCrMAi5sLlAIwABiAQWCgVEACMqAABkqByg81wQIekqBeCIFXFAEQXD6CMCYPoH6ioopYDYXAcW4EuwuGxAgbEAAWAAnNZgATKoAAzAANgE9iRzlmBPOes85xz8t65cdOFemAfGCOsXKIApDIm16sNgIA+TbI0DKdrWp-zCkuMaxTUeMAoXlVylwEFthuWotGRU1wHBMnhNGXZFliyuCavHkQw-Iy5QKtcdVrx-jVWJIpYqwppLLVevJdU0pwbI3htcCGlYmx0AZIbvQYdI8N8ZKhO7Yosd2Ndx0CwJFfp84pnmvYEJQUyQemNrQO4iy82IlfwiIUnqJTZCoHKSc8ukBZIbK1pzGSR4M7+D8s+hbTaHkkYoPi6BdAuQhTgH1T873EloE-CgMyaTWmHeySd4g8ysW-iloVI5O4+0jwSG9kSm5ft2jm4DhRwO9w0+wCefcsBsC-iSJuFpr6L16NWx+yy1dtY5sWQgKQnz6Y-LKhVSgKEICMY-dGsFjdOpaShfwGFaW0DDEXE+hpzpyhNtKEqPXDO8s0yNCSrVWk-EcF4A1pNYBcP5qgDMUSMBo1DUOpr9Odp-va-RRZG60vZeka0thTXvuap66yAb0jQyjzlkd875Srv64W32ZzKQ4q9Ue8XF7+0HLqcm6tFgc3BbLcLxgDbsAtWHdksT7AaNTt+fp7EJBz24pkwKyI12uXIeWPdeDah8C6HMM8ew7hpc5Zo3gyD1HEdAApP9PkuTRIx9A4gCGh1eTAJ1RIMgEarT3E889Ey9Db4SJUgs1JArkNnIgNGR2cmwBXn3kronyG8HALDmTkOVZEvLIP4fD-MAL-dVZaIUXAcfHjCrKiAhKtUiWRa7cZEAd8SQBIXAfwflW5CeEcG-Qbe-VfZIM9EnckPRVaFMWHT8MhTcEcW3bLYdThVOLoNAUnD7cZNfSRDyMHWyYwUtdBURP9aRJA9AikZcBAwQL8WwJVQ6KGdBbbNhLkdBfcZyaAfOEAFCcgHqWII8FSd8FoQobBDLKvRrPjH-dVf6V-WSRLaAgAolCMUAkMCA5Vf6KfLAIPUbKid-b-NUdVf-NDWwn1IlMA5UXDFwoPcQHmXgGAhgqNH-WGZMXAbbDwd8Mg9kGxDpY9UOO1EnNAFGNGc9QUJUYQTxPRfg91V8R7RlThFDPwjDXgTIY7NfTgDfEIrSafbvMAcI76fEYAIPc7SVO9AmCnPPd8cAEgGQGSaJKSOJT+ZeJyXSEyQ6TyWRTmfgEWajUOc9TydkIY-7B5JADGEgScZcdkOyPRZYsgbqdYyVTyLAOwGBdPSCNIeY1SSJCgVAiY9YkccsXZSJGsbUUiTyHnB4iIPKL5QqcXP5SXdY2jfsBXNqAGSFPqVXd3WDF5ZoLIWRG6dY7CZmIQG2TwGtNEjEuoqYmjOjJOPldEqsAjdY8CT8DcawLUKidqYoQOUodqeiFEhSKkzE-VNdKAGE+jSkjE-E6BcZYk1AHkvLMuMkQk9pHkqbY+WoFSdqHpJremTnBI1NegJNTgyVNImsVgyQMAS40kl4rKSCBWeUjEvLaE8knEz6MQAkvga0qsElV03krCHFJAHkqiTk2FVAZUz8VUuxPHK-YHLUo8CgbbE8chfU4CSRNNTcJHA4uePkuJPJS0+uKBfYp0LUYUqsW0s07CbE3E-6UUztXMw4qAAs6adMsk-sBjCRVM-Mok6kosg1Zeek40Jk2k7sxkqAZk1k9k+if01vaDDveuO0xs9Y6NcsOvGAJbcrLEs06NGk1c+uCw7Ez-JVQUqACicQXBSgVAATEkzsvc7CPcr6VAMTXgPcusViWczc5rCgbE2gyOCrITXgMTcxWgXgBcpc1LBMdvESeuQPdo6NOzI1anFgfvaoofQIhwlgXgJcSAxcSfVo1w9ogjeC9DIImsZCjAAg9fcPZ0FgCiFo-wNokjMQL2SchSODRcKC0isgWCiw3CxC8Awi1CpwvDAjcCkjSC6CnXViijYsoPZjGCtjG2Oi0Chi6VW5RzYSv3Nil8gfGo-C3AbinjNC-irvQSrSZimC8sCS3vKSk1PiZsGTTcPcceLgGANCBkAYzyHUPcaAEYiyFGV8FuaMcscFCeOHb8JVHywCcsbQuRcrDIUocCcAZQLAYcdcGRceE7bbd8LUpIxNE8L9EgW5QkVAGOWbOMxRC+P8UkkFVwCHaQRtMZIE2ZDDcsd4lKqqznIEigW4+y0kROLuKDFlBSxcGJKIXjGYQQWeWqAa9CvBfvd+WqQ2YakAUa8KbAQa8sFij83WHRP2Waka8ARarAZa6lanNjPLDCR858TiH1Pq7COaha6wcax8jiG2faCIXq4FW5caqC66na26paiavCCw6ag2J6K67asan6law6vLAG-2Z6T60Gvaia1ao6m6E69AM6-eVAWG3awa+6sIDjVE16-qn6pSzG76+G8sP6tSqGra+ar68a8GkStakBOhGaoGkmumg6hmpGqgcQU618c6qVAmj6kGrGxce6x6vG+Sgm8ayzYGmmuG-aimwyCgKm1m4W0m-axGyGjah6amm69mxGgjFGtGi6gm4mtWu69AB63GiIN1GtBAXkvaC1ZiPMFCBy3bMQW20WOwWaGJaMMMBUaU+28CLCZkwMR8IUf28gDkj2ysXcJAJAM8-kksgCfASO3AHCx2kCAWtlQm+G7CZ25CVCXbCi4O6BUO+8IMAUCO5xKO-0z2qQBus8v2muigFVTOigRi96-O6yFiV2xykukO9qMO4Maup0BUaO4AT2qAaexOqjFOmMMe8gDO5qLOzuom7urMF2oulAAesuoeiu8OyANOiez2mHOAWew1X2wCNO5ei1Ne+GmWguiAPu4u+iUuiAcuh8Eeo+luieoAA)

**Comment by papb** [comment]
Oops, sorry for the delay, I missed this notification.

Hmm... This is a TypeScript limitation, unfortunately. The simple act of writing `(...args: Parameters<F>): ReturnType<F>` already "settles" all generics into their widest type (usually `unknown`).

I tried for some time to find another workaround to keep at least the most common generic usages but I couldn't.

Here are some related TS issues: #39594, #10247, #37835.

This problem also happens with `SetReturnType`.

Should we add a note to the docs that it does not work with functions with generic types?

**Comment by linonetwo** [comment]
Confirmed today, this is a design limintation https://github.com/microsoft/TypeScript/issues/42706

Seems there is no workaround currently.
