### ISSUE TITLE
Proposal: DeepPartial

### ISSUE THREAD

**Issue by UYEONG** [sindresorhus/type-fest#18]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/type-fest/issues/18)

```ts
interface Child {
  id: string;
  name: string;
  state: string;
  mother: {
    name: string;
    some: string;
  }
}

function fn(child: Partial<Child>) { }

fn({ name: '' }); // OK
fn({ mother: { name: '' }}); // NO, Property 'some' is missing
```

But.

```ts
type DeepPartial<T> = { [P in keyof T]?: DeepPartial<T[P]> };

function fn(child: DeepPartial<Child>) { }

fn({ name: '' }); // OK
fn({ mother: { name: '' }}); // OK
```

How about this?

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/type-fest/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by fabiospampinato** [comment]
I'm not sure what's about that `patch` function, but [here](https://gist.github.com/navix/6c25c15e0a2d3cd0e5bce999e0086fc9) there's an implement of DeepPartial:

```ts
type DeepPartial<T> = {
  [P in keyof T]?: T[P] extends Array<infer U>
    ? Array<DeepPartial<U>>
    : T[P] extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : DeepPartial<T[P]>
};
```

**Comment by UYEONG** [comment]
`patch` is just an example. I changed the name to `fn`.  thanks for letting me know.

I actually opened this issue because I think type-fest should include the DeepPartial type.

**Comment by dylang** [comment]
@fabiospampinato Does that handle promises?

Seems like it should have 

```typescript
T[P] extends Promise<infer U>
 ? Promise<Partial<U>>
 : ...
```

**Comment by fabiospampinato** [comment]
@dylang Yeas I don't think it handles promises that way. I'm not sure if you'd necessarily want that though 🤔

**Comment by dylang** [comment]
@fabiospampinato Thanks for the feedback. It was useful for a deep partial `ReturnValue<T>` wrapper when mocking functions for our tests, but makes sense that it's not always what developers would expect.

**Comment by Psidium** [comment]
Does `DeepPartial` support arrays?

```ts
interface Inter {
	prop: string;
	children: string[];
}
```

turns into the equivalent of

```ts
interface Inter {
	prop?: string;
	children?: Array<string | undefined>;
}

**Comment by sindresorhus** [comment]
@UYEONG Do you have any real-world uses of it that you can link to? It seems useful in theory, but I haven't encountered a situation where I would need it personally.

**Comment by fabiospampinato** [comment]
@sindresorhus I think it could be useful when merging a default settings object with another object, the second object would be a deep partial of the default object.

**Comment by sindresorhus** [comment]
@fabiospampinato Do you have any actual code using that pattern? I'm asking because it's easy to suggest things that look useful, but I'm trying very hard to only add things to type-fest that people would actually use, or are already using in production.

**Comment by fabiospampinato** [comment]
@sindresorhus Yes, I do that all the time, here there some examples: [1](https://github.com/fabiospampinato/autogit-plugin-rollback/blob/master/src%2Findex.ts/#L27), [2](https://github.com/fabiospampinato/enex-dump/blob/master/src%2Findex.js/#L13), [3](https://github.com/notable/notable/blob/961303308f419e763e60500bba34f94486ad6640/src/renderer/components/main/mainbar/monaco.tsx#L316), [4](https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src%2Fcommands.ts/#L33).

Often though I try to keep the options object flat, in those cases I don't really need `DeepPartial`.

**Comment by sindresorhus** [comment]
Alright. I'm gonna accept this. It seems it's quite common: https://github.com/search?l=TypeScript&q=DeepPartial&type=Code

It should be named `PartialDeep` since we already have `ReadonlyDeep`.

For anyone that wants to tackle this, please read [guide for adding a type](https://github.com/sindresorhus/type-fest/blob/master/.github/contributing.md) and also see how `ReadonlyDeep` was added: https://github.com/sindresorhus/type-fest/commit/22c3a99f3005605d91feedcf667fda2bac279013 (Note the extensive docs and comments).
