### ISSUE TITLE
argument dynamically optional

### ISSUE THREAD

**Issue by WORMSS** [sindresorhus/type-fest#182]
```ts
interface PropMap {
    a: {
        b: string | number;
    };
    c: never | undefined;
}

function func<K extends keyof PropMap, P extends PropMap[K]>(k: K, p: P) {}
function func2<K extends keyof PropMap, P extends PropMap[K]>(k: K, p?: P) {}

/* ✅ */ func('a');            // should error, needs prop.
/* ✅ */ func('a', { b: '' }); // should be fine
/* ✅ */ func('a', { c: '' }); // should error, wrong prop.
/* ❌ */ func('c');            // should be fine, I don't want to pass in props for never|undefined.
/* ✅ */ func('c', undefined); // should be fine
/* ✅ */ func('c', { c: '' }); // should error, should be given no prop 


/* ❌ */ func2('a');            // should error, needs prop.
/* ✅ */ func2('a', { b: '' }); // should be fine
/* ✅ */ func2('a', { c: '' }); // should error, wrong prop.
/* ✅ */ func2('c');            // should be fine, I don't want to pass in props for never|undefined.
/* ✅ */ func2('c', undefined); // should be fine
/* ✅ */ func2('c', { c: '' }); // should error, should be given no prop 
```

[Playground](https://www.typescriptlang.org/play?ssl=16&ssc=72&pln=16&pc=31#code/JYOwLgpgTgZghgYwgAgApQPYAcCycvIDeAsAFDIXJwBcRZlDyARrQM5hSgDmyAPsiACuAWybQA3PUoBfSeUoJaICADdofZIJAATCDFARtc6WTIwtCMMAwhk5kAgA8AaWQQAHpB2tkAawgAnhgwaJi4+AA0aG6eEN6h2HhYANrOALoAfAAUvrTOUVi0qACURCak9pbWtpUATC4xXto+-kEh6ImR0R5NPh3hKenZucj5yFgA-EWlhOVkAPQAVMiAoOTIi-N2FlkA5HA7xeKMx8jzm6wAFhiCADbablCYUFHKhj5YYQB0C8trG1sOXb7KKEZi0HY7ZDSQ6nc5XW73MR2Aw-VbrTaVIE7EHIRTICFQmFnZCXa53B5PKIAd0wIB4H2w31IS2QgBlydEAhC7BAHI4nBjE0kI5gofTKKIASWQ2hsOzAyCpcHAyDAGHGcFYPlA4zCPhgGCgAlU0F4Wl0YsMTJZfwx2x2PKiZr0Bm0RLhZMRopRzN+HMx9uxRFx4Mh0KOgvh5OglJJkc9yC4wDUthAaoZBFMpFR7P+dSxMP5lAjHopBpeEDeOsZqJtnNqWJxLHxobdsZLSItNb9Fnre0DoLxBLDsLbwujZYVtPpXy7uZ73N5haL7uFHYMkulsvliuVqvVmuQ2vTeoNRrUUFNOmdym0Vt9c4cvYdmivFtd4ZX5LXylntsfC5xQcWw-Uco0eCchS-FBE2TAQ0zCIA)

I hope the above makes sense, but I can't seem to make this act nicely. There is a use case where it breaks.
(I would love to split it into 2 functions, but sadly, it's not my call.)

With `func` the `func('c')` breaks because it is saying I NEED to supply a property
so I thought, simple fix.. make p optional.
but as you can see from `func2` this makes `func('a')` not throw an error, when I WANT it to, because it has a P that is not never.

other things I tried was 
```ts
interface PropMap {
    a: {
        b: string | number;
    };
    c: never;
}
```
which means I can't pass 'undefined' as the 2nd parameter, which is perfectly fine, I can live with that..

**Comment by sindresorhus** [comment]
How is this related to `type-fest`?

**Comment by WORMSS** [comment]
Is it not a type?

**Comment by sindresorhus** [comment]
I don't understand your question.
