### ISSUE TITLE
Need some help to understand `string extends S`

### ISSUE THREAD

**Issue by PaGury** [sindresorhus/type-fest#183]
Hi !

First of all, thanks a lot for this library, it opened my eyes to the capacities and power of "String literal types".

I'm currently building a bunch of types to enable SQL query type extracting.
The main goal of my implementation will be to enable something like this : 
```typescript
const query = `
SELECT u.email as u_email, p.role as p_role
FROM users as u
INNER JOIN profiles as p on p.id = u.id`;
type ResultQueryType = GetQueryResultType<typeof query>;
// ResultQueryType = { u_email: any; p_role: any; }`
```

Actually, I have a working prototype deeply inspired by type-fest, but I ask myself a question and I didn't find anything concrete about the use of the condition `string extends S` in some of the library types ([Here](https://github.com/sindresorhus/type-fest/blob/main/ts41/utilities.d.ts#L5)).
If I remove the condition `string extends S` the type is still working as expected.

Can someone explain to me the intention behind this ?

Thank you!

**Comment by papb** [comment]
`string extends S` is a good way to check if the type `S` is exactly `string`, since by definition `S extends string` is already true.

(note: sometimes `A extends B` and `B extends A` can be both true at the sime time while still `A` and `B` not being the same, but for `string` this is valid)

**Comment by PaGury** [comment]
Thanks,

I see, but I still don't understand why it's necessary to check this kind of assertion is the utility type `Split`.
```typescript
export type Split<S extends string, D extends string> =
	string extends S ? string[] :
	S extends '' ? [] :
	S extends `${infer T}${D}${infer U}` ? [T, ...Split<U, D>] :
	[S];
```

In fact, if I remove the condition `string extends S` and if I pass an exact `string` as `S`, I still want to "Split" the string if it match the last condition `${infer T}${D}${infer U}`. No ?
Why would we want to return a `string[]` instead of `[S]` in the case where `S` is a simple `string` ?

Sorry if I'm not clear, but it's kind of bug me 🤪 ! haha

**Comment by papb** [comment]
> Why would we want to return a `string[]` instead of `[S]` in the case where `S` is a simple `string` ?

Because if all you know about a value is that it is `string`, you have zero information about how many times whatever delimiter appears on it, so you cannot say anything more specific about the result other than `string[]`. If the result was `[string]` as you seem to suggest then you would be essentially saying something like

> *if you give me a variable of type `string` and ask me to split it with a delimiter `'foobar'` then I am sure the result will be an array of length 1 (which is what `[string]` says)*

Which is incorrect.

**Comment by PaGury** [comment]
Ok I see !

Thanks a lot for your clear answers !
