### ISSUE TITLE
Can't install `type-fest`

### ISSUE THREAD

**Issue by gh4n** [sindresorhus/type-fest#184]
I was trying to install the dependencies for https://github.com/kubernetes-client/javascript and ran into an error pulling the `type-fest` package from npm. Could the maintainer check this out? Cheers ☺️

<img width="567" alt="Screen Shot 2021-03-02 at 10 14 42 pm" src="https://user-images.githubusercontent.com/28796511/109640510-b109e200-7ba4-11eb-85c7-c0b8c3d38506.png">

**Comment by sindresorhus** [comment]
This is not the place to ask for `npm` support.

https://www.npmjs.com/support
