### ISSUE TITLE
[snowpack] Unable to find any entrypoint for "type-fest". It could be a typo, or this package might not have a main entrypoint.

### ISSUE THREAD

**Issue by popuguytheparrot** [sindresorhus/type-fest#193]
[snowpack] Unable to find any entrypoint for "type-fest". It could be a typo, or this package might not have a main entrypoint.

**Comment by papb** [comment]
There is no reason to believe from your issue so far that `type-fest` is the culprit. This seems an issue with `snowpack` or your own code. Please open an issue on `snowpack`.
