### ISSUE TITLE
Behavior of `PascalCase`

### ISSUE THREAD

**Issue by ulken** [sindresorhus/type-fest#198]
I'm using [`pascal-case`](https://github.com/blakeembrey/change-case/tree/master/packages/pascal-case) (as part of [`change-case`](https://github.com/blakeembrey/change-case)) which seems to take a slightly different specification route than `type-fest`'s `PascalCase` type. As a result, they don't play well together.

The difference comes down to how numbers are treated. `pascal-case` prefixes delimited numbers with `_`. `PascalCase` simply merges it with the preceding word.

**Examples**
`pascalCase("foo-1") // "Foo_1"` vs. `PascalCase<"foo-1"> // "foo1`

Personally, I prefer `pascal-case`'s take on this one, but I would like to hear if there has been any explicit reasoning around the current behavior or if it just hasn't been thought of.

The main reason is being to able to convert to and fro two casings:

`paramCase(pascalCase("foo-1")) // "foo-1"`

Which just isn't possible with `PascalCase`:

`KebabCase<PascalCase<"foo-1">> // "foo1"`

**Comment by ulken** [comment]
Or rather, if it somehow could be configurable (as is the case with `param-case`). I had a look at rolling my own version using `DelimeterCase`, but as far as I understand, it's currently not possible.

**Comment by sindresorhus** [comment]
I think `Foo1` is the correct output. `Foo_1` is not pascal case. Pascal case doesn't have any underscores. Also, an underscore would fail linting in most projects.

One of the most popular camelcase/pascalcase packages on npm also has this behavior: https://github.com/sindresorhus/camelcase/blob/a83fd06fc15538d92deacbdfdcb397d9dbec68ed/test.js#L81

**Comment by sindresorhus** [comment]
> The main reason is being to able to convert to and fro two casings:

Two-way conversion is a non-goal.

**Comment by ulken** [comment]
I hear you. Thank you for givning your view on the matter.
