### ISSUE TITLE
Proposal: ExcludeProps

### ISSUE THREAD

**Issue by fabiospampinato** [sindresorhus/type-fest#20]
@webstrand came up with this pretty cool type which I modified a bit,  basically it's useful when you want to ensure that some properties are not set in an object.

In this real case scenario we want to extend a class instance with an object, but the properties set in said object mustn't override any already known properties, in order to avoid conflicts, so we use `ExcludeProps` for enforcing this:

```ts
// ExcludeProps definition

type ExcludeProps<T> = { [P in keyof T]?: 'Error: You cannot use this particular property name' & number } & { [prop: string]: any; };

// Usage 

class Foo {
  myProp: number = 123;
  protected myProtectedProp: number = 123;
  constructor ( extraProps: ExcludeProps<Foo> ) {
    Object.assign ( this, extraProps );
  }
}

new Foo ({ foo: 123 }); // It works, `foo` is not an excluded property

new Foo ({ myProp: 123 }); // We get an error, `myProp` is not allowed as it conflicts with the already known `myProp` property of Foo

new Foo ({ myProtectedProp: 123 }); // Unfortunately private e protected props aren't properly supported
```

I thought maybe it could be a decent addition to this repo, or maybe it's not general/useful enough, what do you think?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/20">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/20/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/20/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
I could see something like this being useful, but I think the type needs a better name and refinement.

I would make it something like this for flexibility (not tested):

```ts
type ExcludeProps<T, U = {[key: string]: unknown}> = {[P in keyof T]?: never} & U;
```

Basically, the type should wrap an existing type, but exclude keys that are found in the given type.

**Comment by fnky** [comment]
Some ideas for names:

- `ForbidProps`
- `DisallowProps`
- `RefuseProps`
- `RejectProps`
- `PrecludeProps`

I personally like `PrecludeProps`.

> **preclude**
> _verb (used with object)_, **pre·clud·ed**, **pre·clud·ing**
>   1. to prevent the presence, existence, or occurrence of; make impossible".
>   2. to exclude or debar from something.
>
> – [Dictionary.com](https://www.dictionary.com/browse/preclude)

**Comment by fregante** [comment]
I think this was added as `Except`: https://github.com/sindresorhus/type-fest/blob/main/source/except.d.ts
