### ISSUE TITLE
PackageJson type does not contain known properties for "publishConfig"

### ISSUE THREAD

**Issue by ryansonshine** [sindresorhus/type-fest#204]
publishConfig is set to:
https://github.com/sindresorhus/type-fest/blob/532e1da01650382e6989c407fc83918ab5e72fff/source/package-json.d.ts#L574

I believe the publishConfig should have `access`, `registry`, and `tag`.

**Comment by sindresorhus** [comment]
Yeah, I agree, we should make it stricter.
