### ISSUE TITLE
PartialDeep does not work with `Date` type

### ISSUE THREAD

**Issue by ChromeQ** [sindresorhus/type-fest#207]
Hi,
I am having trouble making my deep partial type setting dates correctly.

Example (including it working with Partial<T>):
```typescript
import { PartialDeep } from 'type-fest';

type Foo = {
    a: Date;
    b: {
        c: Date;
    };
};

type Bar = Partial<Foo>;
const bar1: Bar = { a: 123 }; // Does error
const bar2: Bar = { b: { c: 123 } }; // Does error

type Baz = PartialDeep<Foo>;
const baz1: Baz = { a: 123 }; // Should error
const baz2: Baz = { a: new Date() }; // Only this should be allowed

const baz3: Baz = { b: { c: 123 } }; // Should error
const baz4: Baz = { b: { c: new Date() } }; // Only this should be allowed
```

I think the fix is easy enough so I will open a pull request.

**Comment by Nr9** [comment]
Same issue here

**Comment by voxpelli** [comment]
Have you figured out why it behaves like this?

Seems almost as if the `Date` after a `PartialDeep<Foo>` has been replaced with an `any`? Have you inspected what the resulting type looks like?

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see the feedback given in https://github.com/sindresorhus/type-fest/pull/208.

**Comment by sdotson** [comment]
I'm giving this a try in https://github.com/sindresorhus/type-fest/pull/342. Happy to address any feedback.
