### ISSUE TITLE
Add `SetNonNullable` type

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/type-fest#228]
https://github.com/sindresorhus/type-fest/pull/199

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/228">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/228/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/228/pledge.svg">
</picture>
</a>

**Comment by falkenhawk** [comment]
looking forward to this to be included 👍

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/type-fest/pull/245

**Comment by sindresorhus** [comment]
@joealden It should work like `NonNullable`, so not deal with property optionality.

**Comment by joealden** [comment]
I believe this can be closed now that https://github.com/sindresorhus/type-fest/pull/431 has been merged?

**Comment by kachkaev** [comment]
yeah this can be closed I guess
