### ISSUE TITLE
The `noImplicitOverride` and other options are missing

### ISSUE THREAD

**Issue by manuth** [sindresorhus/type-fest#229]
In the `CompilerOptions`-interface, the option [`noImplicitOverride`](https://www.typescriptlang.org/tsconfig#noImplicitOverride) is missing:
https://github.com/sindresorhus/type-fest/blob/6b8bee7d0df2bfce9cab4ae59bb6b14f81d7a633/source/tsconfig-json.d.ts#L159-L769

**Comment by sindresorhus** [comment]
Yeah. We also need to add:

- `useUnknownInCatchVariables`
- `exactOptionalPropertyTypes`
- `noPropertyAccessFromIndexSignature`
- `explainFiles`

**Comment by sindresorhus** [comment]
// @ifiokjr
