### ISSUE TITLE
Except is broken when used with generic property

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/type-fest#232]
```ts
class Example {
    foo: number;
    bar: string;

    constructor() {
        this.foo = 1;
        this.bar = '';
    }

    [key: string]: unknown;
}

type Except<ObjectType, KeysType extends keyof ObjectType> = Pick<ObjectType, Exclude<keyof ObjectType, KeysType>>;
const test: Except<Example, 'bar'> = new Example();

// `foo` is now `unknown`
console.log(test.foo + 5);
```

[Playground link](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/MYGwhgzhAECiAeYC2AHEBTaBvAUNf0AZgPbEBc0AdgK5IBG6ATgNx4F1iMUQAujAlpQDmrNvmDFKvRtWA9ijABQBKbGIL4eAC34QAdCWLQAvNACMrDRu269HRiegByJ5YIBfHOoDaAa3QAntx8gkIAuhTUlL6UxADulKyeODwBKJgIwOgoPAA8APJ0AFbocgAqaegANNAA0oEQFenQ6PA86JQAJjD+AcSE0IUl5ZUAfI4ACvzAvgXFpTxN1XDwoNSd6Lm9-YPzI+k19QGNY6OsElI80O28FJnZeQjIaMtO9k7jppTocSvPGCpRAB6IHQAAGhjB0F0VHi4KiMXilDBOAuEGIGD0IGIQkUNx4BlI0AA1NAAKzKZhAA)

**Comment by szmarczak** [comment]
I just noticed `Omit` is broken as well 🤦🏼

**Comment by sindresorhus** [comment]
This sounds like a TS bug/limitation. Maybe open an issue about `Omit` and see what they say?

**Comment by szmarczak** [comment]
https://github.com/microsoft/TypeScript/issues/45177

**Comment by szmarczak** [comment]
```ts
type EqualsTest<T> = <A>() => A extends T ? 1 : 0;
type Equals<A1, A2> = EqualsTest<A2> extends EqualsTest<A1> ? 1 : 0;

type Filter<K, I> = Equals<K, I> extends 1 ? never : K;

type OmitIndex<T, I extends string | number> = {
  [K in keyof T as Filter<K, I>]: T[K];
};
```

**Comment by szmarczak** [comment]
I just wanted to note that is `Except` breaks everything that uses it, including `Merge`.

**Comment by sindresorhus** [comment]
Can we make a better `Except` type here?

**Comment by szmarczak** [comment]
We can, but under a different name. Some people want `Except<Example, string>` to remove all string keys and some will want to remove only generic string keys.

**Comment by szmarczak** [comment]
I'll do a PR.

**Comment by sindresorhus** [comment]
What would you name such a type?

**Comment by szmarczak** [comment]
Maybe `ExceptStrict`?

**Comment by nghiepit** [comment]
The problem reappeared in `2.5.2`.

**Comment by sindresorhus** [comment]
I don't see how that's possible. Nothing related to `Except` was touched in 2.5.2.
