### ISSUE TITLE
Error using type-fest with TypeScript version lower than 3.8.0

### ISSUE THREAD

**Issue by adrianbrs** [sindresorhus/type-fest#240]
When I try to use `type-fest@1.3.0` in my Angular project with `typescript@3.7.7` I get an error:
```bash
ERROR in node_modules/type-fest/source/typed-array.d.ts:1:21 - error TS2726: Cannot find lib definition for 'es2020.bigint'.

1 /// <reference lib="es2020.bigint"/>
```

As far as I can see, the `es2020.bigint` was introduced only in `typescript@3.8.0`.
https://github.com/microsoft/TypeScript/issues/33871

I don't know if this error is expected, or if there is a workaround for this, because in the readme I saw that the minimum required version for TypeScript is 3.4.

Thanks.

**Comment by sindresorhus** [comment]
It's just a mistake in the readme.
