### ISSUE TITLE
Add `isObject`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/type-fest#253]
Type guards are hard:

```ts
interface Message {
	text: string;
}
function isMessage(value: unknown): value is Message {
  return value !== null && typeof value === 'object' && typeof value.type === 'string';
}
```

On the surface this is pretty straightforward and how you'd normally do type guards in any language, but:

> ```ts
> error TS2531: Object is possibly 'null'.
> 
> 19   return value !== null && typeof value === 'object' && typeof value.type === 'string';
>                                                                   ~~~~~
> 
> TS2339: Property 'type' does not exist on type 'object'.
> 
> 19   return value !== null && typeof value === 'object' && typeof value.type === 'string';
>                                                                         ~~~~
> ```

Fun facts:

1. Moving the `null` check _after_ the `'object'` type check, fixes the first error, even if that shouldn't change anything.
2. If you use an intermediary `Record<string, unknown>` type, you can access that `type` without errors

```ts
interface Message {
	text: string;
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function isMessage(value: unknown): value is Message {
  return isObject(value) && typeof value["type"] === 'string';
}
```

I think this `isObject` type guard is necessary in every type guard until TypeScript decides that `object` is actually `Record<string, unknown> | null` like one would expect.

Related:

- https://github.com/sindresorhus/type-fest/issues/107

**Comment by sindresorhus** [comment]
What type are you proposing? It sounds like you want: https://github.com/sindresorhus/is#objectvalue

Also, it seems like this will be fixed soon: https://github.com/microsoft/TypeScript/issues/28131#issuecomment-905663987

**Comment by fregante** [comment]
D'oh, you may be right. I'm not proposing a plain type.
