### ISSUE TITLE
Add `WritableDeep<T>` - The inverse of `ReadonlyDeep<T>`

### ISSUE THREAD

**Issue by futpib** [sindresorhus/type-fest#260]

**Comment by sindresorhus** [comment]
Sounds useful 👍

**Comment by einarpersson** [comment]
Is it possible to "resolve" / "flatten" the resulting type?

I just tried this and the resulting type is hard to read since it is a "Writable wrapping a Readonly"

![image](https://user-images.githubusercontent.com/6043691/220605728-e48ebe2d-5f9e-4d9e-8e32-421783c44c3f.png)

I had hoped this would "reverse" and remove the `ReadonlyDeep`

**Comment by sindresorhus** [comment]
You could use our `Simplify` type. Maybe the type should do it too.

// @TomerAberbach

**Comment by TomerAberbach** [comment]
Not opposed to using `Simplify` in `WritableDeep`, but curious how we usually decide whether to use `Simplify` in types within `type-fest` versus telling users to use `Simplify` themselves (and whether that reasoning applies here).

Also, if we use `Simplify` in `WritableDeep` we should probably do the same in `ReadonlyDeep` for consistency.

**Comment by einarpersson** [comment]
> Not opposed to using `Simplify` in `WritableDeep`, but curious how we usually decide whether to use `Simplify` in types within `type-fest` versus telling users to use `Simplify` themselves (and whether that reasoning applies here).
> 
> Also, if we use `Simplify` in `WritableDeep` we should probably do the same in `ReadonlyDeep` for consistency.

Well, I for one expected it to be "undone" rather than prepended =) But good to be consistent, as you say

**Comment by futpib** [comment]
> Well, I for one expected it to be "undone" rather than prepended =) But good to be consistent, as you say

"Undoing" and "prepending" could give different results here if the inner parameter type had a readonly field in it: "undoing" would keep it readonly, "prepending" would make it writable. So an "undoing" version of `WritableDeep` would have to be a different type with a different name and documentation.

**Comment by TomerAberbach** [comment]
Yeah, `WritableDeep` is only a true inverse of `ReadonlyDeep` if the innermost type parameter is fully writable.

I don't think there's really an ergonomic way to create a true inverse because "remembering" the original type is hard.

**Comment by TomerAberbach** [comment]
Anyway, I guess that's tangential to whether we should apply `Simplify` here.
