### ISSUE TITLE
Meta: Add validation check to ensure all files in `source` directory use `.d.ts` extension

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/type-fest#261]
It's easy to forget the `.d` and make it `.ts`.

Should be a Node.js script that is run when testing: https://github.com/sindresorhus/type-fest/blob/b7e1c26c36f28a7a36f7f1e9d5fb7c07c438619a/package.json#L17

**Comment by wafuwafu13** [comment]
I'm trying this :)
