### ISSUE TITLE
Rename `Omit`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/type-fest#27]
We managed to convince the TS team to add `Omit` as a built-in type, unfortunately, they added a loose version, not what we suggested, and [they insist on staying with it](https://github.com/Microsoft/TypeScript/issues/30825).

The great thing about user-land code is that we can fix their dumb decisions.

However, that does mean our `Omit` type will conflict with the native one... But I guess that gives us the opportunity to come up with a better name for it.

I never really found `Omit` that clear. How about `ExcludeProperty` or `ExcludeKey`? I prefer the former. Open to other suggestions.

**Comment by BendingBender** [comment]
I find `ExcludeProperty` very appealing.

**Comment by CvX** [comment]
The another option is `StrictOmit`, to highlight both similarity to the built-in and its main difference. But I'm ok with any of suggested names.

**Comment by sindresorhus** [comment]
@CvX I don't like having to prefix types with `Strict`. They should IMHO be strict by default. In this case, it's not up to us, so I would rather have a different name.

**Comment by sindresorhus** [comment]
Alright. We'll go with `ExcludeProperty`. But let's defer doing anything until it's 100% certain that TS 3.5 will ship with a loose `Omit` type.

**Comment by sindresorhus** [comment]
Relevant discussion: https://github.com/microsoft/TypeScript/pull/31205

**Comment by sindresorhus** [comment]
Since we're renaming this anyway, maybe we should name it `ExcludeProperties` and add support for excluding multiple properties?

**Comment by BendingBender** [comment]
As far as I understand the type, it will already exclude multiple properties when used with a union type:
```
Omit<SomeType, 'foo' | 'bar'>
```
will omit properties `foo` and `bar`.

**Comment by andyfleming** [comment]
While I wish they would have stayed consistent with what the community already understands as the behavior of `Omit`, I do actually like having an omit-key-if-exists AND a omit-key form of the type helper.

**Comment by andyfleming** [comment]
I think I like `ExcludeKey` over `ExcludeProperty` since it matches the language they use with syntax types like `keyof`.

**Comment by andyfleming** [comment]
I'm also not convinced we need a second word in the type name.

Something like `Exclude`, `Remove`, or `Without` could be viable.

**Comment by sindresorhus** [comment]
> As far as I understand the type, it will already exclude multiple properties when used with a union type:

I did not realize that. We should definitely document that better.

**Comment by sindresorhus** [comment]
@andyfleming Yeah, I like your argument about consistency. But shouldn't it be `ExcludeKeys` since it supports multiple keys?

**Comment by andyfleming** [comment]
@sindresorhus I think the verbalized version of it makes sense as singular, specifically because of the union type.



```typescript
let obj: ExcludeKey<ObjectType, "a" | "b">
```

> Exclude key "a" or "b"

**Comment by andyfleming** [comment]
We may also want to consider if we should avoid using the word `Exclude` since it's already in typescript as a type helper.

**Comment by kainiedziela** [comment]
How about reducing it to a single word 'Except'? Then it's readable, understandable and I believe has no conflicts with wording. `Skip` and `Bypass` are viable as well but I have to say - `Omit` is by far the most clear one.
```TypeScript
let obj: Except<ObjectType, 'a' | 'b'>
```

**Comment by sindresorhus** [comment]
Alright. Let's go with `Except`.
