### ISSUE TITLE
Like `Promisable<X>` but for arrays: `X | X[]`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/type-fest#270]
I remember seeing this type somewhere, but I can't find it. Does it exist? Is it native?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/270">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/270/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/270/pledge.svg">
</picture>
</a>

**Comment by voxpelli** [comment]
Like a `MaybeArray<X>`?

```typescript
type MaybeArray<X> = X|Array<X>;
```

Can't remember seeing it somewhere, but I do believe I have created such helpers in some projects.

**Comment by fregante** [comment]
I'd also add the opposite of this: [cast array](https://lodash.com/docs/#castArray)

```ts
type CastArray<X | X[]> = X[]
```

**Comment by fratzinger** [comment]
+1. 
What about calling it `Arrayable<T>`? This would follow `Promisable<T>`.
