### ISSUE TITLE
ArrayValue<T>

### ISSUE THREAD

**Issue by alita-moore** [sindresorhus/type-fest#271]
This is a very basic type but is useful. I don't see it being easily available.

```ts
type ArrayValue<Array> = Array extends (infer Value)[] ? Value : never
```

```ts
const array = ["string"]
typeof array => string[]

type Value = ArrayValue<typeof array> 
Value => string
```

Is this worth including?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/271">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/271/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/271/pledge.svg">
</picture>
</a>

**Comment by alita-moore** [comment]
also in extension with this

```ts
type NonNullableArray<Array> = NonNullable<ArrayValue<Array>>[]
```

**Comment by voxpelli** [comment]
There's actually a neat little trick for doing this in TS:

```typescript
type Foo = string[];
type Value = Foo[number]; // => string
```

Also works for array literals:

```typescript
type Foo2 = ['foo', 'bar'];
type Value2 = Foo2[number]; // => "foo"|"bar"
```

So `ArrayValue<typeof array>` would be equal to `typeof array[number]`, considering that I think we're better of suggesting that people use `[number]`.

Would you want the `ArrayValue<>` anyway @alita-moore?

**Comment by alita-moore** [comment]
Hmm, that's very interesting but less intuitive I think. So I still think there's value in having ArrayValue (we can leave a doc strong suggesting the other way?)

Essentially, when I want to do something I tend to use the intellisense and search for it and if I'm lucky type fest has something similar to what I need.

So it would streamline things, but I'm okay with both options.

**Comment by voxpelli** [comment]
I'll leave it to @sindresorhus to ultimately decide then

**Comment by sindresorhus** [comment]
I think it's worth adding this for readability (and same argument as https://github.com/sindresorhus/type-fest/issues/227#issuecomment-926674935), but it should come with good docs.

**Comment by andsheterliak** [comment]
Have you tried [IterableElement](https://github.com/sindresorhus/type-fest/blob/main/source/iterable-element.d.ts) utility? It works great with 'Iterable' and 'AsyncIterable' types like arrays, maps, sets, generators...

Example:

```javascript
type Foo = ['foo', 'bar'];
type Value = IterableElement<Foo>; // => "foo" | "bar"
```
or

```javascript
type Foo2 = (string | number)[];
type Value2 = IterableElement<Foo2>; // => string | number
```

**Comment by fregante** [comment]
I think `IterableElement` already solved this issue

**Comment by alita-moore** [comment]
I'm okay with IterableElement, and I've also been primarily using the built-in 
```
type A = ["apple"]
type B = A[number]
```
So I agree that this issue can be closed

**Comment by Emiyaaaaa** [comment]
use `ArrayValues` on type-fest@4.6.0
