### ISSUE TITLE
Proposal: `RequiredDeep`

### ISSUE THREAD

**Issue by osdiab** [sindresorhus/type-fest#273]
similar to PartialDeep but the inverse, where all KV pairs are required.

**Comment by sindresorhus** [comment]
What's the use-case?

**Comment by osdiab** [comment]
In my application I have the concept of an "in progress" form which is stored in one DB table, and then the "completed and finalized" form data which is stored in another DB table. The schemas are expressed as Zod schemas and saved in the database as JSON blobs (since the schema is still in flux and we wanted flexibility).

Some data is nested, some are optional in that in-progress form and some are not, but the thing that's definitely true is that all leaves need to be there in the finalized version of the form data. So it's more ergonomic for me to express that type as a deeply required version of the in-progress form.

There are other ways around it but yeah figured that I'm not the only person who might have some usecase for this kind of type.

**Comment by sindresorhus** [comment]
Makes sense. Accepted.

**Comment by andersonba** [comment]
Up

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see the initial attempt and feedback: https://github.com/sindresorhus/type-fest/pull/401

**Comment by moltar** [comment]
https://github.com/ts-essentials/ts-essentials/tree/master/lib/deep-required
