### ISSUE TITLE
`PromiseValue` will no longer be needed in TypeScript 4.5

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/type-fest#275]
[TypeScript `4.5.0-beta` contains a built-in `Awaited` type](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#the-awaited-type-and-promise-improvements) which has the same functionality as the `PromiseValue` type in type-fest. It should be swapped out when TypeScript 4.5 has a stable release.

**Comment by fregante** [comment]
lol I was just about to open an issue!

**Comment by fregante** [comment]
> It should be swapped out when TypeScript 4.5 has a stable release.

Should it just be deprecated? Or dropped in a major update? Or aliased?

**Comment by sindresorhus** [comment]
Deprecated for now.

**Comment by voxpelli** [comment]
Deprecated + be made into an alias of `Awaited` eventually?

**Comment by fregante** [comment]
> be made into an alias of `Awaited` eventually?

Only if they're exactly equivalent. But if you do a breaking release maybe there's no need to alias, also because even the aliasing would be breaking (TS 4.5 would be required)

**Comment by sindresorhus** [comment]
> be made into an alias of Awaited eventually?

No. I don't see the point in risking that.

**Comment by voxpelli** [comment]
Right, let’s have people manually migrate of it then, just deprecating it

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/type-fest/commit/28f3e481eb6c5d7fba465fa9fed23889c9a6685b
