### ISSUE TITLE
Proposal: `Overwrite<Obj, Props>`

### ISSUE THREAD

**Issue by rattrayalex** [sindresorhus/type-fest#276]
Roughly this:

```ts
type Overwrite<Obj extends {}, Props extends {}> = Omit<Obj, keyof Props> & Props;
```

To be used like so:

```ts
type Foo = {
  a: string,
  b: number,
}
type Bar = Overwrite<Foo, {
  b: string,
}>
// Bar == { a: string, b: string }
```

[This exists in `utility-types`](https://github.com/piotrwitek/utility-types#overwritet-u).

**Comment by sindresorhus** [comment]
Isn't this the same as [`Merge`](https://github.com/sindresorhus/type-fest/blob/main/source/merge.d.ts)?
