### ISSUE TITLE
Difference with other libs?

### ISSUE THREAD

**Issue by rifler** [sindresorhus/type-fest#28]
For example https://github.com/piotrwitek/utility-types
It is worth to develop one tool, I suppose

**Comment by CvX** [comment]
See #3

**Comment by rifler** [comment]
It doesn't answer my questions. Types are not presented in runtime, so you shouldn't worry about types that `would never use in practice`

**Comment by BendingBender** [comment]
> would never use in practice

This is not about runtime. This is about maintenance burden.

**Comment by sindresorhus** [comment]
Duplicate of #3

**Comment by sindresorhus** [comment]
Let's continue the discussion in #3.
