### ISSUE TITLE
Proposal: `InvariantOf`

### ISSUE THREAD

**Issue by younho9** [sindresorhus/type-fest#288]
Inspired by [InvariantOf](https://flow.org/en/docs/lang/variance/#toc-invariance).

It could be useful to make object invariant. It is similar `opaque` type without brand or tag.

```typescript
import {Opaque} from './opaque';

export type InvariantOf<Type> = Opaque<Type, keyof Type>;
```

I published this utility type as [package](https://github.com/younho9/invariant-of), but I wish to add it to this project.

[Here](https://github.com/younho9/invariant-of/blob/main/index.test-d.ts) are some test cases.

I'm willing to do PR. 😃

**Comment by sindresorhus** [comment]
What's the practical use-case? I'm not sure when I would need this.

**Comment by younho9** [comment]
In structural typing, Object can have more properties at run-time, so `Object.keys` returning `(keyof T)[]` is quite dangerous.

https://github.com/microsoft/TypeScript/pull/12253#issuecomment-263132208

If use `invariantOf`, because it requires exactly the same type, typescript warn at the type level when the structure of the object changes.

[TypeScript Playground](https://www.typescriptlang.org/play?#code/PTAEEkDtQZwFwE4FcDGckIIYBtRwJ4AOAlpAOYA0okmCCA9gO6lmgICm6C0Bh7o9AGagA8gCMAVuzQA6ANbt8oYjFAATTOXYMkMGQCh9gpJDTF60BfhGCAggCEAFPUnS4AfQBcoBwEpQAN76oGycGNDiUrJWMM6uaO7+mKqOVkI+9r4A2gC6+gC+hqRw2oKYKPwOgcGgmN6QSAC2YtoA3DVi3vAILAVFkCUIZRUZAMKg7AAeJZBqqlVBISjeYvT02Oyaffpq0ti0-CgW8LWdGTt7B6BHkCeYYstjhlY2Do73-iCgqYrpfrn6F52Jz3FCfMA-fB-TK5GR4IjsGAoHqEODqeiIyAAcjRjFokAM+i+AFUYCwIJAAG60YiaOA2Qy7FD7DjXY5ouCYMjeEzEACOSH4MHwzXW7X0vH4UGpPTpAAUGHwEAQADwAFQRAD5QABeb60bmgDV8fw67XG9jiyUUmW0gYAZWIZBoXHY6q1uuqIQ4mDUFmwSiynLIOW80pp8sV2lVFs17Xy4qmhHoyvhfBtEYGNndfG1notoAAZBnZQ6nS6MG7Y4nJsnU8ZTHBzNBSLa6dnY45qdhBd4Lb4w1TM-TBDn2NrFqEuNBu4Laqpw6WR2O49sG2YLKAgYu7XA3i4oh5B22s6OHJr-JOONPRPE4PJFLED25EvPvmlhP88oV9DcTq3hyqPUAKXGx3jEXx2j-NEQN3BxxmAodQMEcCwXFbckLgpxYLpPxWlAL5IWhbI8gwk892wzDcPsUZIIIsBJSRFFcXxAwgA)

This has a tricky side, but there are rare use cases to accurately distinguish the type according to the structure.

**Comment by sindresorhus** [comment]
This is accepted.

For anyone submitting a pull request for this, it should come with a clear description, use-cases, and a practical example.
