### ISSUE TITLE
Proposed paradigm (functional assertions)

### ISSUE THREAD

**Issue by alita-moore** [sindresorhus/type-fest#289]
I made this issue in the typescript a while ago https://github.com/microsoft/TypeScript/issues/45618

and I'm realizing now that the suggestion provided is something that may be useful for a library like type-fest to provide

i.e. offer utilities for each type. Taking directly from the issue...
```ts
function asMutable<T>(value: T): Mutable<T> { return value; }

const context = asMutable(await import("github")).context);
```

In addition you could also offer types such as
```ts
const assertsDefined = <T>(maybeDefined: T | null | undefined): asserts maybeDefined is T => {
   if (!maybeDefined) {
     throw "a defined invariant was validated"
  }
}

// or
const isDefined = <T>(maybeDefined: T | null | undefined): maybeDefined is T => {
   if (!maybeDefined) {
     return false
  }
  return true
}
```

Which you could add other variants to this as well, but I've found a lot of use of having these defined because some built in methods don't properly account for all types. For example `filter(Boolean)` will filter out non-defined but it doesn't make the type NonNullable. But `filter(isDefined)` would.

This would at the very least clean up my code and remove the need for these type utilities

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/289">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/289/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/289/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
I did not add `assertsDefined` yet as I'm not sure what error message to use that would work for everyone. Maybe we should have a good default message, but also let users pass in their own?

**Comment by alita-moore** [comment]
Actually Boolean never does typing correctly at least not in node 14. `NonNullable<string | undefined | null> = string` so to say this is returning `true` for NonNullable` and `false` for `null | undefined` is an accurate statement.

**Comment by sindresorhus** [comment]
It's not just a helper for type-fest though. I welcome other commonly needed TS-specific utilities too.

**Comment by fregante** [comment]
Out of scope, see https://github.com/sindresorhus/ts-extras instead
