### ISSUE TITLE
Feature: add PartialBy<T, K>

### ISSUE THREAD

**Issue by luukvhoudt** [sindresorhus/type-fest#306]
Please add something similar as [this stackoverflow](https://stackoverflow.com/a/54178819/3157038) answer suggests.

Would make this wonderful library a bit more complete <3

**Comment by liuhanqu** [comment]
maybe u can see [this](https://github.com/sindresorhus/type-fest/blob/main/source/set-optional.d.ts) ?

**Comment by luukvhoudt** [comment]
Aah that's exactly it!

Thanks for searching for me :baby:
