### ISSUE TITLE
Deprecate `PromiseValue`

### ISSUE THREAD

**Issue by remcohaszing** [sindresorhus/type-fest#308]
https://github.com/microsoft/TypeScript/pull/45350 introduces the `Awaited` type, which does the same thing (but more advanced).

This is part of TypeScript 4.5.

[TypeScript blog](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-rc/#awaited-type)

**Comment by sindresorhus** [comment]
Yup. We should add a deprecation doc comment tag to the type and deprecate it in the docs. We will not remove it for a long time though.

**Comment by remcohaszing** [comment]
My bad, `Awaited` is similar to `PromiseValue`, not `Promisable`.

**Comment by liuhanqu** [comment]
#322
