### ISSUE TITLE
Proposal: Strict `Get`

### ISSUE THREAD

**Issue by asbjornh** [sindresorhus/type-fest#313]
The `Get` type is incredibly helpful, so thank you for that!

There is, however, one thing that I wish for. I'm a big fan of defensive typing, and in that regard the `Get` type has the same shortcoming as native `Object[Key]` type expressions do: the resulting type doesn't encode failure when dealing with arrays/dictionaries, even when `noUncheckedIndexedAccess` is enabled. F ex. `Get<string[], "[1000000000000000000000000]">` has the type `string` instead of the more defensive `string | undefined`.

In general this is easy to get around in userland, but looking at the implementation for `Get` it doesn't seem like a local proxy type is a feasible way of solving this.

Would you be open to changing the `Get` type or to adding something like a `GetStrict`? If so then I'd be happy to do the actual work

**Comment by sindresorhus** [comment]
Yes, I'm open to making the existing `Get` type stricter.

**Comment by asbjornh** [comment]
Cool! I guess changing the existing type could be handled in one of three ways:
- Enforce strictness for all consumers
- Opt in (type argument)
- Opt out (type argument)

Do you have a preference?

**Comment by sindresorhus** [comment]
Opt-in through a type-argument for now and we can make it opt-out in the next major release.

**Comment by danielo515** [comment]
What is wrong about GetStrict?

**Comment by asbjornh** [comment]
@danielo515 Nothing in principle I guess, but I suspect it could easily lead to a lot of stuff having to be duplicated
