### ISSUE TITLE
option interface field

### ISSUE THREAD

**Issue by shaoqiwang-fe** [sindresorhus/type-fest#324]
type PartialFild<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;

**Comment by sindresorhus** [comment]
Please better describe what you are requesting and what problems it solves.

**Comment by shaoqiwang-fe** [comment]
> 

Some fields are optional，and Partial only support all fields optional

**Comment by byr-gdp** [comment]
You can refer to [SetOptional](https://github.com/sindresorhus/type-fest/blob/main/source/set-optional.d.ts) :)
