### ISSUE TITLE
Proposal: Dictionary

### ISSUE THREAD

**Issue by s97712** [sindresorhus/type-fest#33]
### Define
```ts
interface Dictionary<T> {
    [key: string]: T;
}
```
### Usage
```ts
let v1: Dictionary<number>;
let v2: Dictionary<string>;
let v3: Dictionary<any>;
```

This is a very common and useful definition, also mentioned in the [official documentation.](http://www.typescriptlang.org/docs/handbook/advanced-types.html
)

**Comment by unional** [comment]
IMO that is not much difference than `Record`.

```ts
let v1: Record<string, number>;
let v2:Record<string, string>;
let v3:Record<string, any>;
```

**Comment by fabiospampinato** [comment]
I agree with @unional, `Record` should be used for this. 

What if I want a dictionary where keys are numbers? In theory all object keys will be converted to strings in JS anyway, but TS at the type system level allows for objects having numeric indexes.

**Comment by sindresorhus** [comment]
I'm mildly against this for two reasons:

1. You only save a few characters from `Record` which is more flexible and more well known.
2. You shouldn't use an object as a dictionary. We have `Map` in JS now.

**Comment by BendingBender** [comment]
Same here, `Record` should be used for this.

**Comment by sindresorhus** [comment]
I'm declining this.
