### ISSUE TITLE
How to use `Float`/`Integer`?

### ISSUE THREAD

**Issue by Semigradsky** [sindresorhus/type-fest#334]
For example, if I have these functions:
```ts
import type { Float, Integer } from 'type-fest'

function setYear<T extends number>(length: Integer<T>): void { ... }
function setPrice<T extends number>(length: Float<T>): void { ... }
```

How define that my data implement these types?
```ts
// Data received from API
const myData: {
	year: Interger<?>;  // What I should write here?
	price: Float<?>;    // What I should write here?
}

setYear(myData.year)
setPrice(myData.price)
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/334">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/334/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/334/pledge.svg">
</picture>
</a>

**Comment by Beraliv** [comment]
I think the usage of both `Float` and `Integer` is limited: it's mostly needed for number literal types, e.g. when you pass `setYear(5)` and `setPrice(4.5)`

But when you have the data which is just `number` you cannot do anything specific

## Narrow down the type from `number`

Imagine you have `number` and you want to make sure that you have `integer`. I see it like this – https://tsplay.dev/mqQgJm

But as you mentioned, `Integer<T>` is declared like

```typescript
type Integer<T extends number> = `${T}` extends `${bigint}` ? T : never
```

It means that if you don't specify `T`, you will get `never`

That happens with `year` in this example:

```typescript
if (isInteger(myData.year)) {
  // ❌ myData.year is never 🙃
  setYear(myData.year)
}
```

I would suggest to use opaque types instead – https://tsplay.dev/w2EebW

That would change the usage of `myData.year`. You will still need to check what `myData.year` is (with `isInteger`) but it will infer it correctly:

```typescript
if (isInteger(myData.year)) {
  // ✅ myData.year is number & Tagged<"integer">
  setYear(myData.year)
}
```

## Get data directly from graphql with the type you want

That's the only case I imagine at the moment and then you need to be sure that you used the correct unit to be passed to the correct function

In this case you don't need validators (like `isInteger` and `isFloat`) but I would also use opaque types – https://tsplay.dev/NBeKzw

```typescript
type Integer = Opaque<number, 'integer'>;
type Float = Opaque<number, 'float'>;

const myData: {
	year: Integer;
	price: Float;
}
```

## When do you use `Integer<T>` and `Float<T>`?

So now it looks like we don't really need those types at all, right?

There are several places where they can still be helpful, where you work still number literal types, e.g. translations, css-in-js or anything else

See one example with translations – https://tsplay.dev/mbGpdW

Please let me know about more cases and I can include it in my overview

**Comment by Semigradsky** [comment]
It is a great explanation! Thank you!
