### ISSUE TITLE
Proposal: `IsLiteral`

### ISSUE THREAD

**Issue by jonahsnider** [sindresorhus/type-fest#339]
Returns `T` if `T` is a literal type belonging to `U`.

```ts
type IsLiteral<T, U> = T extends U ? (U extends T ? never : T) : never;
```

```ts
type A = IsLiteral<1, number>;
//   ^? 1

type B = IsLiteral<number, number>;
//   ^? never
```

**Playground Link:** [Provided](https://www.typescriptlang.org/play?target=8#code/C4TwDgpgBAkgzgGQJbAgJwIYBsA8AVAGigFUA+KAXijyggA9UA7AEzhKgH536nXrOojCADd0UAFz9JQ0WgDcAKAWhIUAIKVYiFOmw4AjEUYBXALYAjdKUUB6G1AcA9DkpXQAQpvjJUmXCYt0IzNLNGsFOwcoZwUgA)

Not sure if this is useful. Maybe for certain high-level generic types?

**Comment by sindresorhus** [comment]
Do you have any exact use-cases in mind?

**Comment by sindresorhus** [comment]
The name makes it sound like it returns a boolean.

**Comment by jonahsnider** [comment]
> Do you have any exact use-cases in mind?

Still not sure of any concrete use cases for this. Perhaps it's not a very useful type.

**Comment by tommy-mitchell** [comment]
Some related discussion in #541
