### ISSUE TITLE
Proposal: `StringKeyof`

### ISSUE THREAD

**Issue by younho9** [sindresorhus/type-fest#341]
`keyof` object could include number type. ([It is intended.](https://github.com/microsoft/TypeScript/issues/44577))

However, sometimes we want to get only string keys. (https://github.com/sindresorhus/type-fest/blob/main/source/get.d.ts#L68-L70)

How about provide `StringKeyof` type for this use cases?

```ts
type StringKeyof<BaseType> = `${Extract<keyof BaseType, string | number>}`
```

See also:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_Accessors#property_names

**Comment by sindresorhus** [comment]
I would argue that you almost always want only the string keys, so this sounds useful indeed.
