### ISSUE TITLE
Question: ExclusiveArray

### ISSUE THREAD

**Issue by chris-schra** [sindresorhus/type-fest#345]
Dear All,

I'm not even sure if it is possible, but a lot of times we convert Props to Array. Use case: imagine a "Cached Model":

```javascript
export class CachedModel {
  id: CacheIdentifier<number>;
  locale: CacheIdentifier<string>;
  noIdentifier: string;
}
```
I can already extract the keys:
`type ExtractCacheIdentifierKeys<Model extends CachedModel> = ConditionalKeys<Model, CacheIdentifier<string | number>>; `

But what if I need to construct an array of all the keys? Like
```javascript
const cacheIdentifiersToUse:Array<ExtractCacheIdentifierKeys<CachedModel>> = ["id","id"]
```

How would it be possible to make sure that each key of ExtractedKeys does only exist once in the array?

**Comment by sindresorhus** [comment]
> How would it be possible to make sure that each key of ExtractedKeys does only exist once in the array?

Sounds like you should be using a `Set`.

**Comment by chris-schra** [comment]
Oh what a shame… absolutely correct… I‘ll better leave now 😂
