### ISSUE TITLE
Exclude `Date` and `RegExp` in all "deep" methods

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/type-fest#347]
See: https://github.com/sindresorhus/type-fest/pull/342

**Comment by chris-amaya** [comment]
The title should've been "Include Date and RegExp in all deep methods" isnt this right? 

basically, what i understand its that deep methods are extending `Primitive` type and now instead of
```ts
 T extends Primitive
```

is going to be 
```ts
type BuiltIns = Primitive | Date | RegExp;
```

to finally extend the new type `BuiltIns`
```ts
 T extends BuiltIns 
```

is this correct?

**Comment by chris-amaya** [comment]
basically, what i understand its that deep methods are extending `Primitive` type and now instead of
```ts
 T extends Primitive
```

is going to be 
```ts
type BuiltIns = Primitive | Date | RegExp;
```

to finally extend the new type `BuiltIns`
```ts
 T extends BuiltIns 
```

is this correct?
