### ISSUE TITLE
feat: Sister of Except, stricter version of Required

### ISSUE THREAD

**Issue by vicary** [sindresorhus/type-fest#350]
It caught me by surprise that the built-in `Required` only removes the optional operator, but doesn't explicitly excludes `undefined` if the value includes that.

For naming, I am thinking of `Include` vs `Except`. But that *may* be ambiguous with the existing array util `Includes`, maybe `ForceRequired`?

Ideas are welcomed.

```typescript
type Include<T> = {
  [P in keyof T]-?: Exclude<T[P], undefined>;
}
```

And in turn, `SetRequired` should use the new type instead.

```typescript
type SetRequired<BaseType, Keys extends keyof BaseType> = Simplify<
  Except<BaseType, Keys> & 
  Include<Pick<BaseType, Keys>>
>;
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/350">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/350/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/350/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
I don't think `Include` would work. `ForceRequired` is also does not that clear.

The name should convey that it both removes optionality of the keys and also keys with undefined values.

The only name I can think of is `RequiredAndDefined`, but it's a bit verbose.

**Comment by vicary** [comment]
How about `Defined`? It should be enough to exclude the meaning of optional.

`Exist` may also be a second choice.

**Comment by fregante** [comment]
Probably added as `SetNonNullable` https://github.com/sindresorhus/type-fest/blob/main/source/set-non-nullable.d.ts
