### ISSUE TITLE
Cannot find name 'unknown'. 

### ISSUE THREAD

**Issue by symis84** [sindresorhus/type-fest#36]
platform: win10

ERROR in node_modules/type-fest/index.d.ts(20,23): error TS2304: Cannot find name 'unknown'.
node_modules/type-fest/index.d.ts(61,30): error TS2304: Cannot find name 'unknown'.
node_modules/type-fest/source/package-json.d.ts(60,28): error TS2304: Cannot find name 'unknown'.
node_modules/type-fest/source/package-json.d.ts(375,24): error TS2304: Cannot find name 'unknown'.
node_modules/type-fest/source/package-json.d.ts(486,21): error TS2304: Cannot find name 'unknown'.
node_modules/type-fest/source/package-json.d.ts(493,17): error TS2304: Cannot find name 'unknown'.

**Comment by CvX** [comment]
Type-fest uses the `unknown` type introduced in TypeScript 3.0. What's your TS version?

I wonder if there's a way to show a nicer error explaining which TS version is required at a minimum?

**Comment by BendingBender** [comment]
I don't think that this library will work for TS < 3.2 becase we now use `bigint` primitive type that was introduced in TS 3.2.

**Comment by symis84** [comment]
@angular/compiler-cli@6.1.10 requires typescript@'>=2.7.2 <2.10' but 3.4.5 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@">=2.7.2 <2.10"

To disable this warning run "ng config cli.warnings.typescriptMismatch false".



Basically, i need to update my Angular project to the latest Angular 7 if i want to use this library

**Comment by sindresorhus** [comment]
@BendingBender I think we add `typescript` as a peer dependency. That way we can make it clear what `typescript` version we support. Thoughts?

**Comment by BendingBender** [comment]
Sounds good to me. Let's try this out.

**Comment by CvX** [comment]
My experiences with peer dependencies range from "doesn't work at all" to "gives a bunch of invalid warnings" 😉 but at the very least it will document minimal TS version in the package.json, so that's a win. 😄

**Comment by sindresorhus** [comment]
Actually, this was a bad idea. It means it now complains about TypeScript in a non-TS project that uses `type-fest` just for the `index.d.ts`.
