### ISSUE TITLE
FR: make a dark mode compatible logo

### ISSUE THREAD

**Issue by mesqueeb** [sindresorhus/type-fest#361]
Currently the text is hard to read:
<img width="759" alt="image" src="https://user-images.githubusercontent.com/3253920/152987730-98012740-8a43-40e4-a313-240aaea53064.png">

On github you can define assets for just light mode or for just dark mode.

**Comment by sindresorhus** [comment]
I plan to do this, but the dark mode support for SVG is not fully implemented on GitHub's side: https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981/97

**Comment by sindresorhus** [comment]
I have made the logo itself dark mode aware. The only downside is that it doesn't work in Safari, because of missing SVG support there.
