### ISSUE TITLE
DelimiterCasedPropertiesDeep with Opaque yields wrong type

### ISSUE THREAD

**Issue by valkum** [sindresorhus/type-fest#364]
When using `DelimiterCasedPropertiesDeep` with a type containing a `Opaque` field, the result seems wrong.

```
type O = Opaque<string, "O">
type D = DelimiterCasedPropertiesDeep<{partnerId: O}, '_'>

// Expected
// D: {partner_id: O}

// Actual
// D: {partner_id: {char_at, .....}}
```

It seems all functions for strings are also cased and then added.

**Comment by skarab42** [comment]
@valkum This is the expected behaviour, you have to use [UnwrapOpaque](https://github.com/sindresorhus/type-fest/blob/main/source/opaque.d.ts#L104) to get the base type before passing it to another type.
