### ISSUE TITLE
Add `eslintConfig` to `PackageJson` type

### ISSUE THREAD

**Issue by philting** [sindresorhus/type-fest#371]
ESLint allows their [configuration to be stored](https://eslint.org/docs/user-guide/configuring/configuration-files#configuration-file-formats) within the `package.json`. Seeing as TypeScript and Yarn configs are added, I think ESLint deserves a spot there as well.

**Comment by sindresorhus** [comment]
We cannot possible support every config that can be put into package.json. We support TypeScript as it's only 3 fields and very popular. So not sure about this one.

**Comment by sindresorhus** [comment]
Do you actually need this or are did you just notice it was missing?

**Comment by voxpelli** [comment]
I agree with @sindresorhus, at most it would be as part of something like `PackageJsonExtras`, but also nothing stopping eg ESLint themselves to publish a type for their property, which would be even better than us maintaining it here 👍

Have you tried asking the ESLint project? If they reject the idea, then we can revisit it here?

**Comment by philting** [comment]
Yeah I actually do need this for another project. I've done [my own implementation](https://github.com/philting/config-doctor/blob/main/packages/eslint-doctor/src/lib/load-config.ts#L22) for the time being.

There is a definition in `@types/eslint` for their configuration object: `Linter.Config`. I'm proposing that the `PackageJson` include a property `eslintConfig` that points to that type. I just noticed you don't have any dependencies on other `@types` packages, so wanted to check in if that was a specific design decision. Otherwise, the change should be fairly simple, and I can raise a PR.

@voxpelli makes a good point about having some sort of `PackageJsonExtras`. Perhaps we should consider that for other possible `package.json` additions (including this one). Thoughts?

**Comment by voxpelli** [comment]
Added comment to #372, lets keep the discussion there then
