### ISSUE TITLE
Add `AbstractClass<T>`

### ISSUE THREAD

**Issue by s97712** [sindresorhus/type-fest#374]
The `Class<T>` cannot be used for `abstract` in some cases, [playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYQDYEMDOm4F84BmUEIcARDAJ5gCmAtATZjGQNwBQn6ARs1OgGN4AjNjgAxCBETtcnAgFcAdkOAQlcGExgAeACoA+ABQjMALhSjM+gwEoZszluZHJEW+yA).
Consider adding `Abstract<T>`?
```
interface Abstract<T> extends Function {
    prototype: T
}
```
or `Type`
```
interface Type<T> extends Function {
    prototype: T
}
```

**Comment by sindresorhus** [comment]
I think the first one named as `AbstractClass` makes sense.

**Comment by rayrw** [comment]
Hello! I'd like to work on this.
