### ISSUE TITLE
Is there any runtime function for `CamelCasedPropertiesDeep`

### ISSUE THREAD

**Issue by hyf0** [sindresorhus/type-fest#375]
I have already tried humps and lodash.

For `ID`
`CamelCasedPropertiesDeep` will transform to be `id`
humps will transform to be `iD`
lodash will transform to be `id`

For `ReactDOM`
`CamelCasedPropertiesDeep` will transform to be `reactDOM`
humps will transform to be `reactDOM`
lodash will transform to be `reactDom`

So both humps and lodash have inconsistent behavior for `CamelCasedPropertiesDeep`.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/375">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/375/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/375/pledge.svg">
</picture>
</a>

**Comment by fregante** [comment]
Likely https://github.com/sindresorhus/camelcase-keys/issues/88
