### ISSUE TITLE
SetRequired not allowing other optional fields

### ISSUE THREAD

**Issue by xenoterracide** [sindresorhus/type-fest#378]
```
Property 'uri' is missing in type '{}' but required in type 'Simplify<Except<DevExchangeCallOptions, "uri"> & Required<Pick<DevExchangeCallOptions, "uri">>>'
```
intellij happens to think that the problem is that version and headers are included. So strange...  
  
  interface
  
  ```ts
  export interface DevExchangeCallOptions {
    uri?: string,
    url?: string,
    method?: string,
    responseType?: string,
    headers?: object,
    body?: object,
    form?: object,
    timeout?: number,
    version?: number,
    context?: object,
    query?: object,
    agentOptions?: DevExchangeAgentOptions,
  }

export interface Client {
    async makeCall<T = unknown>(
    options: SetRequired<CallOptions, 'uri'>,
    context: object,
    retry = true
  ): Promise<Response<T>>
  ```
  execution
  ```ts
        const response = await testClient.makeCall({
          uri: matchingPath,
          version: 3,
          headers: { 'x-special': 'test' },
        })
 ```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/378">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/378/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/378/pledge.svg">
</picture>
</a>

**Comment by skarab42** [comment]
@xenoterracide  Please provide a [minimal reproduction](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMoFMYCUUEcCuwooAmAvnAGZQQhwDkMAnmCgLRkoDOMNA3AFC8oAHpFhxgAOxgooZAIYBjFHAAiKAG4BRQfIAWs8QHMUAYVkAbMwHkwMYBHHtEvOHBxRgAfgBccTu8MANM6uUGbevjD+BkEuIGg6EIThfhLRwQTskA4oACqMKMmRqTFwOiiyhNLs4RAARgBWKPIwJbWJ9DUNTS3BZNAgnY3NJbZxEDgw4eI4ILXSJWpVduJTM3NQJfL2UoKTPnVDPS640h37XcPBskaS1rb21T6qmtp6higAgjcwd8vsQcR+EIRPAJFIZAolMYzMAUJInC5ZOx6OJ5HAQLIANYmcxmAA8OTgAF5XOJMeIIAB3cQAPgAFMEIDY-j5UBhsHgCIQ8aYLL8HgFaG5gDQaZttkIYOdDiUCJF6MS4JEcCheABKHwABUoIGA7BQeMwmQeBpyNJp-C2DngGSy+sVskpsmA8CknGhsMkADoMdjeWY6QhgsKfBiYLpUprZDAdAslvYfABmEplCpVHwIWiCZiZJrAcw0Hx0DhcODEAFqoA).
