### ISSUE TITLE
[Feature] ReturnTypeWithGenerics

### ISSUE THREAD

**Issue by xenoterracide** [sindresorhus/type-fest#379]
I'm not entirely sure if this is possible, or if there's a good way to do it. I've tried, and a few other iterations

```ts
ReturnType<SinonSandbox['createStubInstance']>
```
but `createStubInstance` infers generics on the method not the class.

```ts
        createStubInstance<TType>(
            constructor: StubbableType<TType>,
            overrides?: { [K in keyof TType]?:
                SinonStubbedMember<TType[K]> | (TType[K] extends (...args: any[]) => infer R ? R : TType[K]) }
        ): SinonStubbedInstance<TType>;
```

honestly I'm not even sure how you would do this.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/379">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/379/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/379/pledge.svg">
</picture>
</a>

**Comment by skarab42** [comment]
@xenoterracide Please provide a minimal [working exemple](https://www.typescriptlang.org/play?#code/) with actual and expected results.
