### ISSUE TITLE
Proposal: KeysOfUnion, `keyof` Union type

### ISSUE THREAD

**Issue by ajitzero** [sindresorhus/type-fest#381]
Context: https://stackoverflow.com/q/49401866

```ts
interface Foo {
  foo: string;
}

interface Bar {
   bar: string;
}
type Batz = Foo | Bar;
type AvailableKeysFoo  = keyof Foo;  // Works as expected
type AvailableKeysBatz = keyof Batz; // Gives 'never', expected (keyof Foo | keyof Bar)
```

Solution: https://stackoverflow.com/a/49402091

```ts
type Batz = Foo | Bar;
type KeysOfUnion<T> = T extends T ? keyof T : never;

type AvailableKeys = KeysOfUnion<Batz>; // keyof Foo | keyof Bar -> "foo" | "bar"
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/381">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/381/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/381/pledge.svg">
</picture>
</a>

**Comment by ajitzero** [comment]
I am willing to open a PR with this change if this is fine "as-is". This solution belongs to the OP in the linked StackOverflow [answer](https://stackoverflow.com/a/49402091).

**Comment by sindresorhus** [comment]
This type is being added internally in https://github.com/sindresorhus/type-fest/pull/259/files#diff-49eaac4718b21c2c3d9ed8024c97600050979229a82a0255cc3c538e36350131R45-R53. After that PR is merged, we can expose it. If you want to see this happen sooner than later, help with reviewing the referenced PR is welcome.

**Comment by sindresorhus** [comment]
This can now be done: https://github.com/sindresorhus/type-fest/blob/f171b707fdbc9b7e895a34374ee865272a9b1d5a/source/internal.d.ts#L46-L53

**Comment by ajitzero** [comment]
@sindresorhus Thank you! I think with this the pending changes would be documentation?

- [ ] Mention/link in Repository README
- [ ] Update on paka.dev? Or is that auto-generated from the TSDoc?

I can take this up this weekend if you can point to a relevant docs PR.

**Comment by sindresorhus** [comment]
Read: https://github.com/sindresorhus/type-fest/blob/main/.github/contributing.md#submitting-a-new-type

It needs tests and expanded doc comments.

**Comment by sindresorhus** [comment]
> Update on paka.dev? Or is that auto-generated from the TSDoc?

Auto-generated

**Comment by tommy-mitchell** [comment]
This was done in #709 @sindresorhus
