### ISSUE TITLE
Proposal: NonDiscriminatedUnion

### ISSUE THREAD

**Issue by RebeccaStevens** [sindresorhus/type-fest#386]
For a union of only 2 elements, this would just be:

```ts
type NonDiscriminatedUnion<Union> = Union | UnionToIntersection<Union>
```

However, the type would be more complex for the case of 3 or more elements.

### Example usage

Given these types:

```ts
type Foo =
  | {
      bar: number;
    }
  | {
      baz: string;
      qux?: number;
    };

type NonDiscriminatedFoo = NonDiscriminatedUnion<Foo>;
```

If you have a value typed as `NonDiscriminatedFoo`

```ts
declare const value: NonDiscriminatedFoo;
```

You can access each part of the union independently.

```ts
// No benefit over normal union.
if ('bar' in value) {
    // `value ` will be typed as `{ bar: number; }`
}

// No benefit over normal union.
if ('baz' in value) {
    // `value` will be typed as `{ baz: string; qux?: number; }`
}

// This benefits from the non-discriminated union
if ('bar' in value && 'baz' in value) {
    // `value` will be typed as `{ bar: number; baz: string; qux?: number; }`
    // `value` would be `never` with a normal union
}
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/386">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/386/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/386/pledge.svg">
</picture>
</a>

**Comment by TkaczykAdam** [comment]
I'm looking for this type too. Any ideas to achieve that?

**Comment by JGJP** [comment]
Isn't this covered by `UnionToIntersection`?
