### ISSUE TITLE
CamelCase<string> is of type 'never' ?

### ISSUE THREAD

**Issue by GMartigny** [sindresorhus/type-fest#392]
I might be misusing the `CamelCase` type, but I have an error "TS2322: Type 'string' is not assignable to type 'never'." with that very simple `toCamelCase` function.

```tsx
import { CamelCase } from 'type-fest';

function toCamelCase (string: string): CamelCase<string> {
    return string.replace(/_(.)/g, (_, $1) => $1.toUpperCase());
}
```

[Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYQIYgKYBs0GcNwC+cAZlBCHAOQwCeYGAtCRrjFQNwBQXJArgDsAxjGAQBcGBDSYcqfHAAUbKMAEBzAFxwVa9QEptM7HgwAeXRoB8iLnHtwoGGHygTL6gHROwWVEIxFAHoAfUVPfSD1ABolENiAEgBGfTgAXhtkzykAVTAGKFNFfX1uQi4gA)

What's wrong here ?

**Comment by sindresorhus** [comment]
You need to use generics: [Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMIEMQFMA2qDO6C+cAZlBCHAOQwCeY6AtEejjBQNwBQHRArgHYBjGMAh84MCKgzYUeADwAVOOgAeMdHwAmOOCyjA+AcwB8ACj0HDALjgKAlDalZc6RccQc4XuFHQweUGIWRgB0vmCYKALopgD0APqmIXaxhgA0cKbxGQAkAIx2cAC87vkhEgCqYHRQLqZ2hbJwTjLyCsac+FwSLXUAREQQEPEARihQfXZAA)

**Comment by GMartigny** [comment]
Thanks a lot ! 🙇‍♂️
