### ISSUE TITLE
Add type for union joins

### ISSUE THREAD

**Issue by roydukkey** [sindresorhus/type-fest#393]
For example, this would be useful for a `FontStyle` type where the possible values are the space separated string of the terms `bold`, `italic`, `underline`, and `strikethrough`.

Here a [possibility](https://stackoverflow.com/questions/59471947), but it seems this could be improved.

```ts
import type { UnionToIntersection } from 'type-fest';

type UnionToOvlds<U> = UnionToIntersection<U extends unknown ? (f: U) => void : never>;
type PopUnion<U> = UnionToOvlds<U> extends (a: infer A) => void ? A : never;
type UnionConcat<U extends string, Sep extends string> = PopUnion<U> extends infer SELF
	? SELF extends string
		? Exclude<U, SELF> extends never
			? SELF
			: `${UnionConcat<Exclude<U, SELF>, Sep>}${Sep}${SELF}` | UnionConcat<Exclude<U, SELF>, Sep> | SELF
		: never
	: never;

type FontStyle = UnionConcat<'bold' | 'italic' | 'underline' | 'strikethrough', ' '>;
	// "bold" | "italic" | "underline" | "strikethrough" | "bold italic" | "bold underline" |
	// "italic underline" | "bold italic underline" | "bold strikethrough" | "italic strikethrough" |
	// ... 4 more ... | "bold italic underline strikethrough"
```

Also, I'm unsure whether this should be considered a feature or not, but notice that `"italic bold"` is not acceptable by this type because `"bold italic"` is.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/393">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/393/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/393/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
This could easily lead to infinite permutations. Not sure it's a good idea. It's also quite niche. I think we are more likely to add the underlying utilities that enable this, rather than this exact type (for example `UnionConcat`).

In this specific case, it sounds like it's better to have the canonical value as a union and instead split the type of the user input into a union.

**Comment by roydukkey** [comment]
Yup. That's fair. Thanks!
