### ISSUE TITLE
Add `PartialOnUndefined` type

### ISSUE THREAD

**Issue by bbrk24** [sindresorhus/type-fest#399]
What it does is simple: it makes all keys whose type allows `undefined` optional.

This is similar to `ConditionalExcept<T, undefined> & Partial<T>`, except the condition is reversed: instead of `T[keyof T] extends undefined`, this checks `undefined extends T[keyof T]`.

[Sample implementation and use case](https://stackoverflow.com/a/72320731).

Maybe also a deep/recursive variant for consistency with existing types?

**Comment by sindresorhus** [comment]
Makes sense to me.

**Comment by clemclx** [comment]
#426

**Comment by yvele** [comment]
There is now a `PartialOnUndefinedDeep` type, but it there a flat `PartialOnUndefined` or am I missing something? 🤔
