### ISSUE TITLE
`Merge` type does not handle correctly optional properties

### ISSUE THREAD

**Issue by adridavid** [sindresorhus/type-fest#402]
The problem happens when `Merge` is used with two types that share one same key, and when the key is optional in the second type. The returned type for this property should be a union of the two initial types.

### Example

Given these two interfaces :

```ts
interface Foo {
    baz?: "a";
    qux: number
}

interface Bar {
    baz?: "b",
    qux: string
}
```

If we define two values typed as `Foo` and `Bar` :

```ts
const foo: Foo = {
    baz: "a",
    qux: 2
}

const bar: Bar = {
    qux: "qux"
}
```

After merging these two objects, the inferred type is :

```ts
const result = {
    ...foo,
    ...bar
}
// const result: {
//    baz?: "b" | "a" | undefined;
//    qux: string;
// }
```

The optional property `baz` is typed as `"b" | "a" | undefined`.

Using `Merge`, the optional property `baz` is typed as `"b" | undefined` :

```ts
type Result = Merge<Foo, Bar>
// type Result = {
//    baz?: "b" | undefined;
//    qux: string;
// }
```

`"a"` is missing in the union here.

I don't know if `Merge` should be changed to handle this use case or if a new type should be created ?

**Comment by skarab42** [comment]
It's very strange, I don't expect that when I do an intersection. And TypeScript also seems to handles the case differently depending on whether you use the spread operator or an `Object.assign`. [REPL](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyRyARnAF4D8AXMgERx0DcBxyAjgK4AetInAWxLQCAXwIFQkWIhQAhOFBytiZKrTok6AGhVEuvZAGcwUUAHMxE-AQToQJ5DEy0MWALzLCqihsa7vfR5aACYrG3w7BzBSRVoFJU88QI5g+gM6cNt7RygII04AGxikvWQAOkrndAC2SvKyKCzInJi8guKQ5E8AeRIAKwgEMHK4IyNgcxAACj7B4dHxyZnsUW0nTABKdcbNlgiwAE8ABxQ3BO60TGQAMmQE-ezo5HaisABmanPFS+S6qswtWI9UaYiAA)

```ts
const result2 = Object.assign(Object.assign({}, foo), bar); // infered as "Foo & Bar"

type FooBar = Foo & Bar;

const result3:FooBar = { // <- ERROR Type '"b"' is not assignable to type '"a"'
    ...foo,
    ...bar
}
```

**Comment by skarab42** [comment]
In any case when I do a merge I expect the destination value to be replaced if the source exists. Maybe we need another type to handle this ?
