### ISSUE TITLE
`Jsonify` problems

### ISSUE THREAD

**Issue by frontsideair** [sindresorhus/type-fest#407]
I mentioned in #406 that I was building my own `Jsonify`. I have a small test suite that I based on [the spec](https://tc39.es/ecma262/#sec-json.stringify) and there's a [simplified version on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description).

I put the definition in here and it fails a few cases, namely these:

- `Number`, `String` and `Boolean` should be turned into primitives
- `undefined`, `Function` and `symbol` should make keys to be omitted if they are values in an object
- `Function` and `symbol` in an array should turn into `null`
- `symbol` keys should be omitted in an object

I can help with these if it aligns with the project goals. My plan would be first add these tests, then fix the current definition to make the tests pass. [My current implementation](https://gist.github.com/frontsideair/dfd696bc927514ba4a78e1c5ed4acd1c) passes the tests, but is not exhaustively tested and it's not as modular as the one in this repo, so I would rather improve this implementation.

**Comment by sindresorhus** [comment]
I'm happy to see the `Jsonify` type become more correct. Pull request welcome :)
