### ISSUE TITLE
Require at least one element in arrays or function arguments (`RequireAtLeastOne`)

### ISSUE THREAD

**Issue by fregante** [sindresorhus/type-fest#420]
I'm opening this issue for documentation/googlability, but it should also probably be added to https://github.com/sindresorhus/type-fest/blob/main/source/require-at-least-one.d.ts

It turns out, `RequireAtLeastOne` also works with arrays:

```ts
type NonEmptyArray = RequireAtLeastOne<unknown[], 0>;
export const full: NonEmptyArray = [2];
export const empty: NonEmptyArray = [];
// Type '[]' is not assignable to type 'NonEmptyArray'.
//   Property '0' is missing in type '[]' but required in type 'Required<Pick<unknown[], 0>>'.
```

It also works for functions:

```ts
export function atLeastOneArg(...numbers: RequireAtLeastOne<number[], 0>): number[] {
	return numbers;
}

atLeastOneArg(0);
atLeastOneArg();
// Argument of type '[]' is not assignable to parameter of type 'RequireAtLeastOne<number[], 0>'.
//  Property '0' is missing in type '[]' but required in type 'Required<Pick<number[], 0>>'.ts(2345)
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/420">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/420/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/420/pledge.svg">
</picture>
</a>

**Comment by adam-rocska** [comment]
Nice idea, but won't cover for cases like 😢 
```ts
const wontWork: RequireAtLeastOne<number[], 0> = [...[], ...[1]];
```

**Comment by fregante** [comment]
As mentioned in https://github.com/sindresorhus/type-fest/issues/476, that's likely a non-resolvable TypeScript limitation (because it doesn't resolve the value/type deeply enough)
