### ISSUE TITLE
`Override<{a: number, b: number}, {a: string}>` for unions that override props from the previous object

### ISSUE THREAD

**Issue by fregante** [sindresorhus/type-fest#429]
Union types are sometimes able to override the properties:

```ts
type Confused = {name: string | number}
type Certain = Confused & {name: string};
const user: Certain = {};

user.name
// string
```

but sometimes they can't

```ts
type Confused = {name: string | Element}
type Certain = Confused & {name: string};
const user: Certain = {};

user.name
// (string | Element) & string
```

https://www.typescriptlang.org/play?#code/LAKALgngDgpgBAYQPYDsBmBXAzjAJnAXjgG8UBDAWxgC44swAnASxQHM4AfOAUQBsYqKMAF9QoSLEQwGYMi0KJUmHPgBkJclVr1mbYQG4xIAMap6cbNNoJpslkcsMAdJphA

This is either a bug or a TS limitation, but perhaps it can be avoided:

```ts
type Certain = Override<Confused, {name: string}>
```

This is currently feasible with:

```ts
type PreCertain = {name: string};
type Certain = Omit<Confused, keyof PreCertain> & PreCertain;
```

https://www.typescriptlang.org/play?#code/LAKALgngDgpgBAYQPYDsBmBXAzjAJnAXjgG8UBDAWxgC44swAnASxQHM4AfOAUQBsYqKMAF9QoSLDgAFBjAQwGYMi0IlyVWvWZthAbnHR48xcpSqA8hSZgAPMnTY8AGjgBrGBCRpps40pYAfHAAZD5yCv4o+iCgAMao9HCODLR+pqrEemIgyQB06jBAA

I'm not sure if it's worth adding to type-fest, but I wanted to document it

**Comment by adridavid** [comment]
Regarding your last code block, you can get the same result by using the `Merge` type.

```ts
import {Merge} from 'type-fest';

type Confused = {name: string | Element}
type Certain = Merge<Confused, {name: string}>;
const user: Certain = {};

user.name
// string
```

**Comment by fregante** [comment]
That’s the one!
