### ISSUE TITLE
ConditionalPickDeep

### ISSUE THREAD

**Issue by dninomiya** [sindresorhus/type-fest#438]
Would it be possible to consider adding a deep option?
Thanks for the useful library.

```ts
import type {ConditionalPick} from 'type-fest';

interface Example {
	a: string;
	b: string | number;
	c: {
		d: string;
	}
}

type StringKeysOnly = ConditionalPick<Example, string, {deep: true}>;
//=> {a: string, {c: {d: string}}}
```

Thanks for the useful library.

**Comment by skarab42** [comment]
Yes I think it could be useful I'll see what I can do.

**Comment by sindresorhus** [comment]
Sounds useful, but it should be a separate type: `ConditionalPickDeep`.

**Comment by skarab42** [comment]
@dninomiya @sindresorhus Done in #444

**Comment by dninomiya** [comment]
@skarab42 @sindresorhus 
appreciate!
