### ISSUE TITLE
Tests no longer run with xo v0.52.2

### ISSUE THREAD

**Issue by skarab42** [sindresorhus/type-fest#451]
I have just done a fresh install from the main branch and it looks like xo cannot find the `tsconfig.json` file.

![image](https://user-images.githubusercontent.com/62928763/187194644-9dc71867-f5a8-4819-9ace-d95fd30b7d87.png)

Even when adding the config in the `package.json` or in an `.eslintrc` doesn't change anything.

```json
"eslintConfig": {
  "parserOptions": {
    "project": "./tsconfig.json"
  }
}
```

**Comment by sindresorhus** [comment]
Try to install with npm and see if that makes a difference.

**Comment by sindresorhus** [comment]
It works fine for me locally and it also works fine on the CI.

**Comment by skarab42** [comment]
@sindresorhus this is related to windows, works on WLS but I don't understand what changed to make it break like that...
![image](https://user-images.githubusercontent.com/62928763/187215243-0fdac48a-0faa-4170-834b-3f6caff370f4.png)

**Comment by sindresorhus** [comment]
Also make sure you have the latest minor version of Node.js 14 or 16.

**Comment by sindresorhus** [comment]
Does XO 0.51.0 work? Just to see if it's a reason problem.

**Comment by skarab42** [comment]
> Does XO 0.51.0 work? Just to see if it's a reason problem.

I have tested them all up to 0.43.0 which is the first one that works.

**Comment by skarab42** [comment]
@sindresorhus Same with latest node and npm version
![image](https://user-images.githubusercontent.com/62928763/187238952-a695ebb4-6858-4748-8ad7-9fca17247c14.png)

**Comment by imrane245** [comment]
Hello

**Comment by skarab42** [comment]
@sindresorhus I think I found the issue in XO and so it's not related to type-fest. I'm closing this issue and doing a PR with a fix on the XO repo.
