### ISSUE TITLE
Jsonify Map type returned as `{}`

### ISSUE THREAD

**Issue by MGibson1** [sindresorhus/type-fest#457]
I've been having an issue with parsing JSON serialized `Map<TKey, TValue>` in a type-safe way.

It comes down to the fact that `Jsonify<Map<TKey, TValue>>` return `{}` instead of taking the key/value types into consideration. I would expect Jsonify to treat Maps and Records equivalently

**Expected result**

```typescript
type JsonifyMapType = Jsonify<Map<string, string>> // JsonifyMapType = {[key: string]: string}
```

**Actual result**

```typescript
type JsonifyMapType = Jsonify<Map<string, string>> // JsonifyMapType = {}
```

**Comment by papb** [comment]
> I would expect Jsonify to treat Maps and Records equivalently

Why? `JSON.stringify` itself does not treat them equivalently:

```js
const x = new Map([['a', 1], ['b', 2]]);
const y = { a: 1, b: 2 };
JSON.stringify(x); // '{}'
JSON.stringify(y); // '{"a":1,"b":2}'
```

To me, the current behavior is correct.

**Comment by MGibson1** [comment]
Well, color me surprised. I should have tested that myself, you're 100% right.
