### ISSUE TITLE
Version upgrade causes seemingly unrelated TS errors

### ISSUE THREAD

**Issue by uriklar** [sindresorhus/type-fest#459]
Hi! I've upgraded from v0.18.0 to v2.19.0 and started getting the following error:
```
property 'replaceAll' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2021' or later.
```

Happens on v1.4.0 as well. I tried adding es2021 to my tsconfig but that just causes many more errors..
Is there a reason upgrading type-fest should cause my tsconfig to change?
I'm using TS v4.6.3 and this is my tsconfig.json file:
```
{
    "compilerOptions": {
        "resolveJsonModule": true,
        "outDir": "./dist/",
        "sourceMap": true,
        "noImplicitAny": false,
        "allowJs": true,
        "module": "commonjs",
        "target": "es6",
        "jsx": "react",
        "esModuleInterop": true,
        "experimentalDecorators": true,
        "skipLibCheck": true,
        "baseUrl": ".",
        "paths": {
            "~/*": ["./src/*"],
        }
    },
    "exclude": [
        "./node_modules/*"
    ]
}
```

Thanks!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/459">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/459/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/459/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
>  I tried adding es2021 to my tsconfig but that just causes many more errors..

Did you add it to the `lib` property (which is an array)?

> Try changing the 'lib' compiler option to 'es2021' or later.

**Comment by uriklar** [comment]
I did, but it caused a bunch of other unrelated errors. I guess it's because specifying it requires me to explicitly specify all other libs I want to support.

What I don't understand is why does it require me to change my tsconfig at all?
I mean, this replaceAll code was there all along and TS errors on it only when upgrading `type-fest`. Is that expected?

**Comment by voxpelli** [comment]
@uriklar Copy the lib definition from one of the predefined tsconfigs out there and/or have your tsconfig extend one of those

Here's mine: https://github.com/voxpelli/tsconfig

I link to Sindre's and a community one in there as well 👍

**Comment by DaniilIsupov** [comment]
i got same error
solution: roll back to `0.20.2` version
