### ISSUE TITLE
Suggestion: Make `SetNonNullable` 2nd Generic Optional

### ISSUE THREAD

**Issue by joealden** [sindresorhus/type-fest#461]
https://github.com/sindresorhus/type-fest/pull/431 added the `SetNonNullable` type, which is very similar to a type we use where I work (see https://github.com/sindresorhus/type-fest/issues/228#issuecomment-1136017869), but unlike this type, the one in `type-fest` enforces that the 2nd keys generic is passed. Is there a reason we would be opposed to making the 2nd generic optional (where the default is to make all keys non nullable)?

**Comment by joealden** [comment]
@sindresorhus any thoughts on this? I'm happy to create the PR once I get your approval on the idea.

**Comment by sindresorhus** [comment]
👍 Go for it.
