### ISSUE TITLE
I think I found a bug in your Jsonify type?

### ISSUE THREAD

**Issue by Evertt** [sindresorhus/type-fest#466]
The title ends with a question mark, because I've literally never installed this package before. I was just reading the source code out of interest.

And while reading the code for `Jsonify`, I saw something that looked like a bug to me. Namely here:

https://github.com/sindresorhus/type-fest/blob/main/source/jsonify.d.ts#L103

At first I was like _"oh really? I never knew that `Map` and `Set` are converted to empty objects by `JSON.stringify()`, that's interesting, let's try that!"_. And indeed:

<img width="253" alt="image" src="https://user-images.githubusercontent.com/1267282/190583200-c5b29aba-4a94-4827-bcb2-dc5625972827.png">

However, that line that I linked to, is still a bug, I believe. Because the `{}` there is not representing `an empty object value`, but instead it represents the `{}` type, which as far as I know means `any non-nullish type`. So instead you should use your own [`EmptyObject` type](https://github.com/sindresorhus/type-fest/blob/main/source/empty-object.d.ts), don't you think?

**Comment by sindresorhus** [comment]
Seems like a bug to me. It was introduced in https://github.com/sindresorhus/type-fest/commit/8ca2959bc8613e6856681dd14abb1ebcbfef6b25.

// @frontsideair

**Comment by frontsideair** [comment]
Yeah, sounds like a bug. It looks like there's already a PR addressing it, otherwise I'd be looking at it. Thanks for taking the initiative!
