### ISSUE TITLE
`Type instantiation is excessively deep` in `ReadonlyDeep`

### ISSUE THREAD

**Issue by marekdedic** [sindresorhus/type-fest#467]
Hi,
I recently updated my declaration of `ReadonlyDeep` to use the new call signature handling from #359, however, I get `error TS2589: Type instantiation is excessively deep and possibly infinite.` :(

See the repro in the [playground](https://www.typescriptlang.org/play?ts=4.8.2#code/JYWwDg9gTgLgBDAnmApnA3nASighgEwgDsAbRAERRTDgF84AzKCEOAciVQFoGUBnGGwDcAKFCRYcAFRxcfOACkAigFcUURI2as2AKwCOajcJEiGKogGMYwYoyIAKFAC5seQqQpUwAHmVHEAD4ASlcANwhgfAwRAEgAEidg0VogA) for details.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/467">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/467/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/467/pledge.svg">
</picture>
</a>

**Comment by skarab42** [comment]
@marekdedic I'm not sure why you want to make the `jQuery` object read-only (and deep). It's a huge object with lots of references to HTML objects and as the update includes index signatures all these objects will be made read-only deep which makes TS reach its memory limit very quickly.

**Comment by marekdedic** [comment]
Hi, for the same reason you'd make anything read-only I think 😀 To have stricter control over what gets modified...

I agree that the jQuery object is huge, that's why it crashes...

**Comment by fregante** [comment]
I don’t think it's practical/possible because it would ask to make all the nested DOM types readonly too, not just jQuery methods
