### ISSUE TITLE
Add `SimplifyDeep` type

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/type-fest#469]
https://github.com/sindresorhus/type-fest/issues/436#issuecomment-1221518145

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/469">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/469/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/469/pledge.svg">
</picture>
</a>

**Comment by KubaJastrz** [comment]
There is one: https://github.com/sindresorhus/type-fest/blob/5ad462a678512af3299d163f7db64ea89a9770d4/source/merge-deep.d.ts#L15-L18

Here's another: https://github.com/sindresorhus/type-fest/blob/5ad462a678512af3299d163f7db64ea89a9770d4/source/conditional-simplify.d.ts#L17-L32

None of them are exported in `type-fest/index.d.ts`
