### ISSUE TITLE
`NonEmptyTuple` type

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/type-fest#476]
```ts
export type NonEmpty<T> = [T, ...T[]];
```

Context: https://github.com/sindresorhus/type-fest/pull/287

Why add such a simple type? Mostly for readability and discoverability. Most people don't know about this trick and we can document it well with examples and stuff.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/476">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/476/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/476/pledge.svg">
</picture>
</a>

**Comment by Evertt** [comment]
I would find it just a *bit* more readable if it mentioned the word `Array`, like `NonEmptyArray` for example. Other than that, I'm all for it.

**Comment by skarab42** [comment]
I will make the one we already have generic and public.
https://github.com/sindresorhus/type-fest/blob/fedbc441a314c1f9f5f6225c993860d0886261da/source/internal.d.ts#L74

**Comment by sindresorhus** [comment]
I agree.

Any thoughts on naming it `NonEmptyTuple`? It's technically a tuple, even though the term tuple/array is a bit of a conflated mess in TS.

**Comment by Evertt** [comment]
Isn't the difference that tuples have a fixed length and arrays have a variable length?

So a `NonEmptyArray` is not the same as a `NonEmptyTuple`. The main difference being that the `NonEmptyTuple` is readonly and the `NonEmptyArray` is not (necessarily) readonly. Right?

**Comment by skarab42** [comment]
> Isn't the difference that tuples have a fixed length and arrays have a variable length?

I'm not sure about that, it's more to do with the positioning of the elements and their types. A tuple can have a variable length but an imposed sequence of elements.

```ts
type VariableLengtTuple1 = [string, boolean, ...number[]];

const foo:VariableLengtTuple1 = ['hello', true, 1, 2, 3]; // Pass
const bar:VariableLengtTuple1 = ['hello', 'world', 1, 2, 3, 'not-allowed']; // Fail
const baz:VariableLengtTuple1 = ['hello', true, 1, 2, 3, 'not-allowed']; // Fail
```

**Comment by skarab42** [comment]
> Any thoughts on naming it `NonEmptyTuple`? It's technically a tuple, even though the term tuple/array is a bit of a conflated mess in TS.

A tuple matches both tuple and array, but array does not match tuple. It's clearer for me to call it a tuple because technically it is one, but I understand that it can be confusing.

**Comment by skarab42** [comment]
> The main difference being that the `NonEmptyTuple` is readonly and the `NonEmptyArray` is not (necessarily) readonly. Right?

No, a readonly tuple cannot be modified, a non-readonly tuple can have its members modified as long as they are of the same type.

```ts
type WritableTuple = [string, number];

const writableTuple: WritableTuple = ['life', 42];

writableTuple[0] = 'hello'; // Pass, it not reaonly
writableTuple[2] = 'hello'; // Fail, key out of bound


type ReadonlyTuple = readonly [string, number];

const readonlyTuple: ReadonlyTuple = ['life', 42];

readonlyTuple[0] = 'hello'; // Fail, Cannot assign to '0' because it is a read-only property.
```

**Comment by bvandercar-vt** [comment]
`NonEmptyTuple`'s type could definitely be improved to allow passing a type restriction to the tuple:

Current:
`export type NonEmptyTuple = readonly [unknown, ...unknown[]]`

Proposed:
`export type NonEmptyTuple<T extends any = unknown> = readonly [T, ...T[]]`

**Comment by fregante** [comment]
Isn't this the same as `RequireAtLeastOne`?

Related:

- https://github.com/sindresorhus/type-fest/issues/420
