### ISSUE TITLE
Problem with `SetNonNullable` in Type Predicate Context

### ISSUE THREAD

**Issue by joealden** [sindresorhus/type-fest#486]
[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwg9gOwGYEsDmUC8UDeUCGAXFAEZxwA2E+CUAPlAgK4UUDcpxZl1tDzrKAF82AKFEB6AFRZMc+QsVLlK1WvXKoUieJQBbMHABOwXFFCQoAZQjAAcojssK+ElQIBna7YcInrVyoARmEoJCM4PSgAIgsIAFokCA9gaLFRAGNEFKgs5HQACXwPAAUIsBDsAB4AFTK4MCgIAA9gCAQAEy8AawgQOCRYRFQ0AD4AClEoXOH0Ynh8tAAaKagwcuI68tEASmI8kagULxt7R2dAiCCqhZGlqC2G0axnnFWjWyYjWgAhcioaOMDugANrrBoAXR2YhE4jyOTaKQAYghKlAgbM0PNMTsXrhVtMUIMMYsiqVykESXcYvhojtcW9pkymcC0AA6fBiZncpkSCRQAB6AH4CcJREJxNJZBoZbK5fK5FodKI4t4zn4Lm4IAAmKqrH7FCA1cAQFbTADSfQ8NTgpyarXaXSgvX6gwNHiNJqwzr6Ayg7s9kFEz2wjKgIMtICOtBdfoDxsgEOIkftbU6Xkj1tttlFQqgvn8Li1VXjJojfQho1FxFLkHLIAhMPS8NMrLJ9TA2u9tQ7qcdPV9g1u6Amq1Z2MWZrWGweHd2+0xRxOPnOAS1uuHy1n5RDr3en2+-v+vCpoPBYChTbh2VMiOAKK72FPWKGi1xmD3zKJ6LbxQ72ufe5olpel8R5aY4j9VkOS5cC4N5flhVFCUhCAA).

When using`SetNonNullable` in a type predicate context where the predicate contains a generic from the function, I am seeing the following error: `A type predicate's type must be assignable to its parameter's type (2677)`.

When I use the `SetNonNullable` from my own types (see https://github.com/sindresorhus/type-fest/issues/228#issuecomment-1136017869), this is not an issue. Is there something we can do to the existing type to prevent this error, and is there any reason that the type definition provided in https://github.com/sindresorhus/type-fest/issues/228#issuecomment-1136017869 wouldn't suffice?

**Comment by sindresorhus** [comment]
// @JohannCooper

**Comment by JohannCooper** [comment]
@joealden 
Sorry for the late reply, this is a great catch! I think the type definition you provided in your comment is sufficient. Would you like to make a PR?
