### ISSUE TITLE
Proposal: Constructor

### ISSUE THREAD

**Issue by fabiospampinato** [sindresorhus/type-fest#51]
I propose the following "Constructor" interface:

```ts
interface Constructor<Class, Args extends any[] = []> {
  new ( ...args: Args ): Class
}
```

The problem it solves is the following.

Let's say we have the following `Foo` class:

```ts
class Foo {}
```

If we need to accept a `Foo` class as an argument we can write something like this:

```ts
function fn ( cls: typeof Foo ) {}
```

But what if Foo is a generic class? Then we can't write something like this:

```ts
function fn ( cls: typeof Foo<any> ) {}
```

And we also can't just write something like this:

```ts
function fn ( cls: Foo<any> ) {
  new cls ();
}
```

Because `cls` won't be recognized as a constructor and TS will throw the following error:

```
Cannot use 'new' with an expression whose type lacks a call or construct signature.ts(2351)
```

Here's where the proposed `Constructor` interface comes in, with it we can write the following:

```ts
class Foo<T1, T2> {}

function fn ( cls: Constructor<Foo<any, any>> ) {
  new cls ();
}
```

Apparently this has been discussed already in TypeScript's repo, [here](https://github.com/Microsoft/TypeScript/issues/20719), and somebody mentioned how Angular also had to define a similar interface.

I've already stumbled on this twice, [here](https://github.com/fabiospampinato/overstated/blob/a426f0ac1283bd66286fec7f564b164321e8b233/src/types.ts#L15) and in another library I haven't released yet.

**Comment by BendingBender** [comment]
We already have a type like this: [Constructor](https://github.com/sindresorhus/type-fest/blob/master/source/basic.d.ts)

However, it lacks the generic parameter feature. Do you think it makes sense to extend the `Class` implementation with the generic parameter? What about contructors with multiple parameters?

**Comment by fabiospampinato** [comment]
Oh I missed that, thanks!

Perhaps it could be enhanced so that constructor's arguments can be typed too, something like:

```ts
export type Class<T = unknown, Args extends any[] = []> = new(...arguments_: Args) => T;
```

Anyway I'm closing this since a similar interface one is already present.

**Comment by BendingBender** [comment]
PRs are always welcome!
