### ISSUE TITLE
Standard npm package.json `workspaces` field is missing from PackageJson type

### ISSUE THREAD

**Issue by electrovir** [sindresorhus/type-fest#510]
Workspace setup from Yarn have been covered in #77 but now NPM itself has a workspaces field which is not covered in the `PackageJson` type: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#workspaces

**Comment by vyvy8801** [comment]
i think you need do **npm init install** againt to test be cause i see that your code is good nothing to fix sir

**Comment by bmish** [comment]
I opened #530 which should resolve any confusion here.
