### ISSUE TITLE
Use the new `satisfies` operator?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/type-fest#512]
https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/

Can it be useful somewhere in type-fest?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/512">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/512/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/512/pledge.svg">
</picture>
</a>

**Comment by thorn0** [comment]
It can't be used in .d.ts files, so...
