### ISSUE TITLE
Suggestion: type for Object.fromEntries

### ISSUE THREAD

**Issue by tranvansang** [sindresorhus/type-fest#521]
It will be great if type-fest has support for the output of `Object.fromEntries`.

Existing implementation:
https://dev.to/svehla/typescript-object-fromentries-389c

Related issues:
https://github.com/microsoft/TypeScript/pull/12253#issuecomment-263132208
https://github.com/microsoft/TypeScript/issues/35745

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/521">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/521/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/521/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
I have a type for this in https://github.com/sindresorhus/ts-extras#api

I'm not sure how useful it is to provide only the type.
