### ISSUE TITLE
Conditional pick deep not compiling, internal?

### ISSUE THREAD

**Issue by AuspeXeu** [sindresorhus/type-fest#526]
`"type-fest": "3.3.0"`

![image](https://user-images.githubusercontent.com/2115696/204777012-5531427a-b66d-47e5-afeb-54e2e1cd2435.png)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/526">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/526/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/526/pledge.svg">
</picture>
</a>

**Comment by papb** [comment]
What TypeScript version are you using?

**Comment by AuspeXeu** [comment]
`"typescript": "4.9.3"`

**Comment by FailurMan** [comment]
maybe you can try change skipLibCheck option in your configuration file

**Comment by AuspeXeu** [comment]
Sure, as a workaround. But this should be fixable without preventing the lib check?
