### ISSUE TITLE
Importing `type-fest` unable to resolve module.

### ISSUE THREAD

**Issue by bombillazo** [sindresorhus/type-fest#527]
Hello, for some reason in some files, when I import `type-fest` my linter says it cannot resolve the path to the dependency (even though I've confirmed it exists)

```ts
import { SetRequired } from 'type-fest';
// Error - Unable to resolve path to module 'type-fest'.eslint (import/no-unresolved)
```

inside node_modules dir:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/44002321/205625229-ee7d73dc-329e-40be-9240-b4fd89c7773c.png">

**Comment by sindresorhus** [comment]
This sounds like a problem with eslint-plugin-import, not this package. You should report this there instead.

**Comment by papb** [comment]
Yeah, [I posted this solution on StackOverflow](https://stackoverflow.com/a/71375585/4135063) some time ago. Weird indeed. Probably a bug with eslint-plugin-import.
