### ISSUE TITLE
Feature request: `IsStringLiteral`

### ISSUE THREAD

**Issue by Ayc0** [sindresorhus/type-fest#541]
What do you think of adding a type that can say if a string is a string literal (like `'foo/bar'`) and not a regular `string`?

```ts
export type IsStringLiteral<T> = string extends T ? false : true;
```

**Comment by sindresorhus** [comment]
What are some real-world use-cases for it?

**Comment by Ayc0** [comment]
In one of my projects, I'm using a library like `react-router`, and I only allow it to use literal strings for the `path` variable. This allows me to use a custom TS type to parse the `path` and propose the route parameters (like `/foo/:bar/:paz`) as props in the Route component.

I already have this type util in my project, but I was wondering if other people in the community wanted to use it too.

If you find it useful, feel free to add it to this awesome project!

**Comment by tommy-mitchell** [comment]
In `tsd`, [`expectDocCommentIncludes`](https://github.com/SamVerschueren/tsd/blob/main/source/lib/assertions/assert.ts#L96-L104) expects a generic string literal type parameter, but checks for it [through the TypeScript compiler](https://github.com/SamVerschueren/tsd/blob/main/source/lib/assertions/handlers/informational.ts#L65). This type could help users when testing.

---

Related, a better way to write this type would be:

```ts
type IsStringLiteral<T> =
  T extends string
    ? string extends T
      ? false
      : true
    : false;
```

Would adding types to check for other literals be useful? E.g. `IsNumericLiteral`, etc. Perhaps:

```ts
import type {Primitive} from 'type-fest';

type IsLiteral<T extends Primitive> =
  | IsStringLiteral<T>
  | IsNumericLiteral<T>
  | IsBooleanLiteral<T>
  | IsSymbolLiteral<T>
  // ...
```

I'd be open to adding a PR. Other use cases of `IsStringLiteral` or other `IsXLiteral` types would be helpful.

**Comment by sindresorhus** [comment]
> Would adding types to check for other literals be useful?

👍 It would make sense to do these too for completeness.

**Comment by sindresorhus** [comment]
This is now accepted. Pull request welcome.
