### ISSUE TITLE
Transpose or invert object keys to/from key-like literal values

### ISSUE THREAD

**Issue by texastoland** [sindresorhus/type-fest#543]
I'm not sure whether this would be generally useful. I personally struggled to implement it. Happy to PR but wanted to gauge interest first and document my solution for searchability otherwise:

```ts
type Transpose<Obj extends Record<PropertyKey, PropertyKey> | PropertyKey[]> = {
  [Value in Extract<Obj[keyof Obj], PropertyKey>]: keyof {
    [Key in keyof Obj as Obj[Key] extends Value ? Key : never]: never
  }
}

type Letters = ["A", "B", "C", "D", "Etc"]
type Letters2Indexes = Transpose<Letters>
//   ^? type Letters2Indexes = { 5: "length"; A: "0"; B: "1"; C: "2"; D: "3"; Etc: "4"; }
```

[[Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgTgQwHYGcwHsUQDwHkBGAVlBAB7ARIAmKUAShAMbpxXYAKc6kcoA0hBAAaKJ24ReIASAB8UAD6iuPfoIDaAXTkBeKAG8AUFChqAaggA2AV2gBLJFACi5RI2B4iagNaD0AMygCQg0RMRUpQRkNAC4oHxB-fSNjE2koezjfAKCoBFogtWkNEnJKGihza2gAfig02KQIADcJGKhGlrhkgF8DXoNQSCgAGQhgCjhaXTUAIgBBGZEZgCFFqBmAYTWZgBFtx2BGGY0B8GhR8YkUACYASWoyCCnYRFQMLGwLiZQZAwB6P4pAB6tUG5zG3zuD1ITyguj0UAArLEZhZKABzYAACxmAG4oHMUQAGPFQZYogCMpI2KOupJ2KIAzKSDowUQAWUm9IA)]

**Comment by sindresorhus** [comment]
What are some practical use-cases for this? I don't really see the use-case without also an actual code implementation, and then you would do so in TS and not need this type.

**Comment by sindresorhus** [comment]
It could also be more type-safe by ensuring the input object values are valid keys.

**Comment by texastoland** [comment]
> It could also be more type-safe by ensuring the input object values are valid keys.

Fixed.

> What are some practical use-cases for this?

I don't have 1. It was for an unfortunately contrived teaching exercise. I thought it'd be worthwhile to start with an implementation (and maybe close the issue) and reconsider if someone comes looking (like I did) with a better use case.

**Comment by texastoland** [comment]
> I don't really see the use-case without also an actual code implementation, and then you would do so in TS and not need this type.

Sounds right so I linked it to the invert function in Remeda instead.
