### ISSUE TITLE
Exact incorrectly handles optional object with union type

### ISSUE THREAD

**Issue by defunctzombie** [sindresorhus/type-fest#545]
When trying to use `Exact` with my function input, I am seeing the following error from typescript type checking:

```
Property 'union' is incompatible with index signature.
                      Type 'string' is not assignable to type 'never'.
                        Type 'string' is not assignable to type 'never'.(2345)
```

Here is the code which uses the `Exact` type with my `func` to validate the input object.

```typescript
type ParamType = {
  outer?: {
    inner?: {
      union: "foo" | "bar";
    };
  };
};

type Input = {
  outer?: {
    inner?: {
      union: "foo" | "bar";
    };
  };
};

const input: Input = {
  outer: {
    inner: {
      union: "foo",
    },
  },
};

function func<InputT extends Exact<ParamType, InputT>>(_foo: InputT) {
  // no-op
}

func(input);
```

`ParamType` and the `Input` are both the same.

[Playground Link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3hqBzAXPAK4oCWAjkQmgJ4C2ARkhANwBQboksCGNADggAqeXCGAAeIUgDWIFAD54AXngBvNgEg4UYKgg14AbRy4AuoWlyU7AL7s2fQfADyDAFbgMANSgQqUgA08ADSSqoh8CAAHhjywGjwcjRIAGbwQvAA-BlGIWbwhCggAG4gMOxOCACCMDBQNACiECB08hhS4RlRsfGJOnooBsQoMihIAO4oRgU5QkYADAVFpeWVAggu-FCUIFIbwVbyKiNjk4onQhvwAGQZouJSsvIK684hIDRoLqkAqmSoTqXHpxFAJbo5ZJpborMoVDhVeCNaJQMAYNyeNESAAKsCgbTiMCugmCAEkUPwiBhiSAumo8p94KQUElPtDcfUCeUaRYkSisRz8SBCTSGTQzMEMV5fP49uTKdSDqFPgoFLY2HcAErgJAwSTIyBEUASKHpeVUmnBD5fH7-UiAwVcokbVXBYpw14I67I1EdR3C7lK82KwThLQAenD8AAwqg4VgSPaWdDYPVDBgkPBUw14NDE6hCNUZrd4AAhYvKJQACmqJdLAEoZlp-SLrjFQeCSGcpsWcrU0xIfVj+w1mq12ji8U6aQpgiOmi02igOsGZ6qI1HyRkNgBlMAwUj8DBzuo50iJKDwNBEBiI6Ha3T6Gjz4JoTN+CYNRJxTDwefwBgQFSXUEAfQYDHnAA6LRNEIFtA2cds+ngAYn1OcYe1meAwKfedB35Dp5zHJc-SnANnVDE802IidVxdddNEYyN4AAMV1Vxtl2bANjQYJmUJFA-HgUAcFICALzgeAAAtSGAUAWVSGAkDoeBKQYCBSDAV9MxaDAAHJEhaKAyiZLAoESc9oMY2D4HgiiECQsFEi2HYAmZVJyg41yQEtJkUA8mAvN2I4LhyOyaRgxi4LI1tEN6Jzcw8Lxsj5X0pQFGKEJAMkKQtF1Iqi2zMvshxHGuR0aRODR4FzKlyiyQhqpqvzihgBr1DYZrmvzFBCAAImApA+vgAAfeA+oYWA+vYLr7E6+A5rmsrnGDKr5qQOq2sa+aauZVr2qarqev6wbhrGiappm5q5pqxaHGQdAsGZBVCFW1Qmo2wltq6vbym+rqRiTE6kCGwIdoWsHbrBpbUhINEk3gWGUDACRVxBZCh1IzlfNXVUqwAfUG17cupesOpq5jxgAWiQfg2HVNgkbAKtnqpesWCAA)

Is my expectation of what `Exact` should be doing here wrong?

**Comment by sindresorhus** [comment]
// @zorji
