### ISSUE TITLE
`Except` is not strict

### ISSUE THREAD

**Issue by nurliman** [sindresorhus/type-fest#556]
```ts
import { Except } from "type-fest";

type Foo = {
    a: number;
    b: string;
    c: boolean;
};

type FooWithoutA = Except<Foo, 'a'>;

const foo: Foo = {
    a: 1,
    b: 'b',
    c: true
}

const fooWithoutA: FooWithoutA = foo; // not error
```

[playground link](https://www.typescriptlang.org/play?ts=4.9.5&ssl=27&ssc=37&pln=1&pc=1#code/C4TwDgpgBAkgzgUQI4FcCGAbAPAQQDRQBCAfFALwBQU1UAFFgOLG0CU5pDUEAHsBAHYATOFBxQA-FACMUAFxQATGx58hcKjXpNW7KJxUDhRCdLmKWG6pOAAnFBEtmAZpjgQA3BQqhIUAGIAlhh8NlgA0hAgACrgEAQI3ADGGCiCEDGQpGSwiKiY4ZEZcVAJyanpsaQGalC29ib8EABuEDZmtBHRsVy8hiKlKWlFDc2tZp1FLJ7e3aUQYMBYAPIARgBWEInARQSdcMPVRgDWkQD2TlCrG1tFWVAA3o4A2hPdAfxQJyDnl+ub2900CJAsFWgUupBdpF9pUALryK7-IovQqxWGeAC+0x80D8p1O5AejjQ8n4KAAtitWp4aFAVvI4LZ3gBzGk0RLyFb4jAQND8THY7p404AdQCwAAFqcUMAxNk5gssMKCAByNAq4jTRKnfiMqBOfHyYWEx60knSPCOelQFUrFWW2kc2p2BwYrza3XAfX4sWS6Wyo0+8VSmVy72nIA)

Is this intended behavior? if yes, how can i restrict `foo` for being assign to `fooWithoutA`?
Thank you.

**Comment by nurliman** [comment]
> This is probably because TypeScript has a design decision that causes it to only check for excess properties when an object is defined using an object literal syntax.
> 
> It is possible to restrict `foo` for being assign to `fooWithoutA` with this solution:
> 
> ```ts
> import { Except } from "type-fest";
> 
> type StrictExcept<T, K extends keyof T> = Except<T, K> & Partial<Record<K, never>>;
> 
> type Foo = {
>     a: number;
>     b: string;
>     c: boolean;
> };
> 
> type FooWithoutA = StrictExcept<Foo, 'a'>;
> 
> const foo: Foo = {
>     a: 1,
>     b: 'b',
>     c: true
> }
> 
> const fooWithoutA: FooWithoutA = foo; // error
> ```
> 
> If relevant, I would be happy to submit a PR and fix the original `Except`.

Cool, your solution worked. Thank you!

**Comment by tommy-mitchell** [comment]
> It is possible to restrict `foo` for being assign to `fooWithoutA` with this solution:
> 
> ```ts
> // ...
> ```
> 
> If relevant, I would be happy to submit a PR and fix the original `Except`.

@orimiles5 Maybe adding an `ExceptOptions` similar to `Get` would suffice?

https://github.com/sindresorhus/type-fest/blob/a0658655c346bf2eebfe4ee2bcf6c93eaa33dfc7/source/get.d.ts#L5-L14

The default behavior would be the updated strict version, and users could opt in to the non-strict `Except` if they were relying on the old behavior.
