### ISSUE TITLE
Proposal: PartialExcept

### ISSUE THREAD

**Issue by fabiospampinato** [sindresorhus/type-fest#57]
I've recently made the following type, and I though it might be useful enough to be included here:

```ts
type PartialExcept<Object, Keys extends keyof Object> = Partial<Object> & {
  [Key in Keys]: Required<Pick<Object, Key>>[Key]
};
```

It makes all properties in `Object` optional, except for the properties specified in `Keys`, which are required.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/57">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/57/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/57/pledge.svg">
</picture>
</a>

**Comment by fabiospampinato** [comment]
Other possible names could be `RequiredKeys`, `RequiredProps`, `RequiredOnly` or `Requiredonly` (as in `Readonly`, but it sounds weird).

**Comment by fregante** [comment]
I think this was added as `SetRequired`: https://github.com/sindresorhus/type-fest/blob/main/source/set-required.d.ts
