### ISSUE TITLE
ConditionalPickDeep includes Array prototype properties & methods

### ISSUE THREAD

**Issue by roblav96** [sindresorhus/type-fest#570]
## Problem:
When using `ConditionalPickDeep` it also picks all `Array.prototype` methods and properties.

---

## `ConditionalPickDeep`
<img width="767" alt="Screen Shot 2023-03-11 at 9 22 01 PM" src="https://user-images.githubusercontent.com/1457327/224520903-4e5befc1-9872-4f90-aa80-e172638fc892.png">

Notice the `length: number;` and `at: {};` properties set on `customRegistrationQuestions`.

---

## `ConditionalPick` does not include array properties
<img width="767" alt="Screen Shot 2023-03-11 at 9 21 13 PM" src="https://user-images.githubusercontent.com/1457327/224520833-06ccab1a-3a03-40bf-91d7-fb1f46fb5a98.png">

---

## Example source
```ts
import type { ConditionalPick, ConditionalPickDeep } from 'type-fest';

export interface UpdateEventDto {
  about: string;
  address: {
    addressLine1: string;
  };
  addressName: string;
  contactEmail: string;
  contactPhoneNumber: string;
  currentSetupStep: number;
  customRegistrationQuestions: {
    isRequired: boolean;
    name: string;
  }[];
  healthScreening: {
    enableScreeningQuestions: boolean;
    screeningQuestions: {
      correctAnswer: boolean;
      id: number;
      question: string;
    }[];
  };
  useLogoAndBackgroundInAllEvents: boolean;
}

type FormValues = ConditionalPickDeep<UpdateEventDto, string | number | boolean>;
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/570">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/570/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/570/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
I would say that's a bug.
