### ISSUE TITLE
feature request: Omitdeep

### ISSUE THREAD

**Issue by wajeehsf** [sindresorhus/type-fest#576]
Create a type that can omit deeply nested properties. 

Something like this: 

```
import { OmitDeep } from 'type-fest';

interface User {
  id: number;
  name: string;
  address: {
    street: string;
    city: string;
    state: string;
    zip: string;
  };
}

type UserWithoutZip = OmitDeep<User, 'address.zip'>;

```

It should work for any any number of levels. 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/576">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/576/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/576/pledge.svg">
</picture>
</a>

**Comment by sadik-malik** [comment]
Unfamiliar with this library myself, but its potential for simplifying nested type omission caught my eye. Worth a look? https://github.com/tobloef/deep-omit-ts
