### ISSUE TITLE
`Simplify` does not transform deep/recursively

### ISSUE THREAD

**Issue by NoamLoewenstern** [sindresorhus/type-fest#577]
The "Simplify" type does not simplify **_recursively_**. 
Which does not apply when an interface has sub-interfaces...
https://github.com/sindresorhus/type-fest/blob/c3bc0e8b08dc7656935eea49c76d8131a0abd32e/source/simplify.d.ts#L58

```typescript
interface A {
  num: number;
}
interface B = {
  a: A;
  name: string;
};
````
Will result in the following:

![image](https://user-images.githubusercontent.com/6962980/227617145-d685ac92-6d46-4e4b-ba1a-3b98a9cadaec.png)

My proposed fix checks if the value is a **_Record<string, any>._** I don't know the internals of the library using the "Simplify" to know if that's the correct type to check "extends" from, but it's to show the point that recursive transforming interface to a valid JsonValue is necessary.

**Comment by sindresorhus** [comment]
This is intentional. See: https://github.com/sindresorhus/type-fest/pull/441#issuecomment-1230077846 It should be a separate type.

**Comment by skarab42** [comment]
In fact it [already exists ](https://github.com/sindresorhus/type-fest/blob/main/source/conditional-simplify.d.ts) and used internally for a while.
@sindresorhus  maybe we can make it public?

**Comment by skarab42** [comment]
As you wish, maybe both?

**Comment by sindresorhus** [comment]
Actually, we can just export it as `SimplifyDeep` and have the filters be optional.

**Comment by Evertt** [comment]
@sindresorhus when can we expect a release of that? 😇
