### ISSUE TITLE
Proposal: ValueOf

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/type-fest#58]
It's a common question and not many know how to do it: https://stackoverflow.com/a/49286056/64949

```ts
type ValueOf<T> = T[keyof T];

type Foo = {a: string, b: number};

type ValueOfFoo = ValueOf<Foo>;
// string | number
```

The code is simple, but remembering the syntax is not. It would also be nice to have it as few know it's possible at all.

Real-world use-case: https://github.com/goodmind/FlowDefinitelyTyped/blob/333ce3a4273848326bfc43827eb4e7aa9a9d7441/types/react-native-vector-icons/FontAwesome5.d.ts

---

We could also consider instead adding a more powerful version that optionally supports picking the keys to get value from:

```ts
type ValueOf<T, K extends keyof T = keyof T> = T[K];

type Foo = {a: string, b: number: c: boolean};

type ValueOfFoo = ValueOf<Foo, 'a' | 'c'>;
// string | boolean
```

**Comment by sindresorhus** [comment]
This is accepted. PR welcome :)

**Comment by Richienb** [comment]
I'll take this. PR coming soon 🎉
