### ISSUE TITLE
Prettify utility

### ISSUE THREAD

**Issue by kof** [sindresorhus/type-fest#581]
This thread by @mattpocock https://twitter.com/mattpocockuk/status/1622730173446557697 explains the details

```ts
type Prettify<T> = { [k in keyof T]: T[k] } & {}
```

TLDR is complex intersection types are unreadable in autocomplete and this makes it readable, seems like something that should be in ts itself, but lets get it become more popular first, people are unaware

**Comment by istarkov** [comment]
Already exists https://github.com/sindresorhus/type-fest/blob/main/source/simplify.d.ts

**Comment by kof** [comment]
ohhh nice!
