### ISSUE TITLE
`RequireAtLeaseOne` issues

### ISSUE THREAD

**Issue by xiaoyu-tamu** [sindresorhus/type-fest#59]
```ts
import { RequireAtLeastOne } from 'type-fest';

interface BaseConditionProps {
  when: string;
  is?: any;
  isNot?: any;
  children: (value: any) => React.ReactNode;
}

type ConditionProps = RequireAtLeastOne<BaseConditionProps, 'isNot' | 'is'>;

const Condition: React.FC<ConditionProps> = ({ when, is, isNot, children }) => (  // ERROR HERE
  <Field name={when} subscription={{ value: true }}>
    {({ input: { value } }) => {
      const show = is ? value === is : value !== isNot;
      return show ? children(value) : null;
    }}
  </Field>
);

```

Typescript complain that 
1. Property 'isNot' does not exist on type 'PropsWithChildren<RequireAtLeastOne<BaseConditionProps, "is" | "isNot">>'.ts(2339) 
2. Property 'is' does not exist on type 'PropsWithChildren<RequireAtLeastOne<BaseConditionProps, "is" | "isNot">>'.ts(2339)

I had no problem if I use another version that I found in the issue.

```ts
import { Except } from 'type-fest';

export type RequireOne<ObjectType, KeysType extends keyof ObjectType = keyof ObjectType> = {
  // For each Key in KeysType make a mapped type
  [Key in KeysType]: (// …by picking that Key's type and making it required
  Required<Pick<ObjectType, Key>> &
    // …and adding the other keys in KeysType as optional and of type `never`
    Partial<Record<Exclude<KeysType, Key>, never>>);
}[KeysType] &
  // …then, make intersection types by adding the remaining properties to each mapped type.
  Except<ObjectType, KeysType>;
```

**Comment by sindresorhus** [comment]
// @CvX

**Comment by ulken** [comment]
[@azure/keyvault-certificates](https://docs.microsoft.com/en-us/javascript/api/@azure/keyvault-certificates/?view=azure-node-latest) use the following implementation:

```ts
export type RequireAtLeastOne<T, U extends keyof T = keyof T> = {
  [K in U]-?: Required<Pick<T, K>> & Partial<Pick<T, Exclude<U, K>>>;
}[U];
```

The above solves it for me. How do we feel about replacing the current implementation with the above ☝️?

Of course with more readable naming. Documentation with explanations can be found at: [RequireAtLeastOne type](https://docs.microsoft.com/en-us/javascript/api/@azure/keyvault-certificates/requireatleastone?view=azure-node-latest).

**Comment by xenoterracide** [comment]
yeah, same issue

**Comment by ulken** [comment]
@sindresorhus Gave it a go. Added a minimal test to capture the issue the OP experienced.
