### ISSUE TITLE
[MergeDeep] No attempt merge on Destination + Source types

### ISSUE THREAD

**Issue by bombillazo** [sindresorhus/type-fest#595]
Hello, I was looking at the MergeDeep type definitions since we have a use case that requires a specific behavior for MergeDeep:

Given:
```ts
MergeDeep<Destination, Source, Options extends MergeDeepOptions = {}>
```

I would like to know: if the key is present in both Destination and Source types, is it possible to completely ignore the Destination type and use the incoming Source type instead of attempting to merge?

If not, it would be great to add a new option to MergeDeepOptions so that the merge behavior is to utilize the Source type completely, not merging if the key exists.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/595">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/595/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/595/pledge.svg">
</picture>
</a>

**Comment by bombillazo** [comment]
Hello, any ideas on this?

**Comment by bombillazo** [comment]
Hey @sindresorhus , any thoughts on this?

**Comment by sindresorhus** [comment]
> I would like to know: if the key is present in both Destination and Source types

Do you mean if all keys are present in both?

**Comment by sindresorhus** [comment]
The `MergeDeep` type is already quite complicated, so it must be something very convincing for us to add more complication to it.

**Comment by bombillazo** [comment]
What I mean is having the option to keep the type of either source or destination key types. At the moment, the behavior is to attempt to merge every on of each key type. So for simplicity's sake, we have the following:
```ts
type Source = {
  a: string;
  b: number;
  d: string | null;
}

type Destination = {
  a: boolean;
  b: boolean | undefined;
  c: string;
}
```
The resulting merge type would be something like this:
```ts
type Merge = {
  a: string | boolean;
  b: number | boolean | undefined;
  c: string;
  d: string | null;
}
```
It would be nice to have the option to prioritize or "keep" the type of source or destination. In the same example, if we want to merge but maintain any types present in the source, the result would be:
```ts
type Merge = {
   a: string;
   b: number;
   c: string;
   d: string | null;
 }
```

**Comment by bombillazo** [comment]
The use case for this is when one wants to enrich or enhance the properties of an object by only adding what it is missing from the incoming type object. This is common like when one creates a typed object with the default, minimally required data for forms or DB model that is later filled with remote or user-generated data.

**Comment by sindresorhus** [comment]
Pinging @skarab42 as he's the one that added the type.

**Comment by skarab42** [comment]
@bombillazo @sindresorhus  I'm not sure I understand, because it seems to me that this is already the behavior of Merge ([playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwLIFMoHMUBo6oygERRTAF84AzKCEOAchgE8wUBaClAZxjoG4AofkxZwAyhACuUAMYo4AXkT84cAIYAuONyjAAdugEqARpt0SQRtIbgATTdr3o4AHzhmANu4GlBwuUW49VRhgCF0FJRUNOCMICHcUVV1rExi4hKSXOAldGxQKPRQba2l7GB19b19mOQAlLgl3GABGCLxMAB4AkN1g0N0ccSlZAD4BAHpxlTgAPQB+apF6zkaYIhI2tEx1sC6uHr6wwckZFDH+Sen5-iA)).

![image](https://github.com/sindresorhus/type-fest/assets/62928763/f716cd9a-86f3-4ff4-bd9a-b6a87502cbb3)

**Comment by bombillazo** [comment]
Ahh now I remember what it was! We want to override the types from Source if they are `unknown` or `undefined` :)

**Comment by bombillazo** [comment]
I think we can close this as the use case has been worked around and I don't remember quite what I was going for, I probably solved it some other way.
