### ISSUE TITLE
Opaque not working correctly?

### ISSUE THREAD

**Issue by AuspeXeu** [sindresorhus/type-fest#599]
I have the following type defined
```
type Encrypted = Opaque<string, 'Encrypted'>
```
However I can still do the following.
```
const enc = 'xyz' as Encrypted;
console.log(JSON.parse(enc));
```
Shouldn't this throw a compiler error?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/599">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/599/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/599/pledge.svg">
</picture>
</a>

**Comment by mirceak** [comment]
Since everything is handled through functions or by functional means you should also have a function that wraps around such methods. More specific the global scope's default methods. Imagine having to strong-type the "Eval" method with string literals and whatnot...

**Comment by AuspeXeu** [comment]
I have to admit I don't quite understand your comment. Would you be able to provide an example as to how you would handle this case?

**Comment by mirceak** [comment]
Hey,

So something along these lines:

```
type Encrypted<T> = Opaque<T, 'Encrypted'>
const enc = '333' as Encrypted<string>

/* JSON.parse(text: string, reviver?: (this: any, key: string, value: any) => any): any; */
type JSONParseStringParam = InvariantOf<Parameters<typeof JSON.parse>[0]>
type JSONParseReviverParam = Parameters<typeof JSON.parse>[1]

const newJsonParse = (text: JSONParseStringParam, reviver?: JSONParseReviverParam) => {
	return JSON.parse(text, reviver)
}

newJsonParse(enc)
```

`Type 'string' is not assignable to type '(argument: string) => string'.`

Now, if you want to use the actual JSON.parse method instead of using some new function that wraps around, you could make yourself a .d.ts file that defines a new type of JSON.parse and that type should be like above.

Good luck!

**Comment by mirceak** [comment]
I feel like chat-gpt right now :))

**Comment by AuspeXeu** [comment]
Haha. If that helps in any way. I'm more confident in your answers ;)
