### ISSUE TITLE
Proposal: NonEmptyArray

### ISSUE THREAD

**Issue by bvandercar-vt** [sindresorhus/type-fest#613]
would be handy and very simple to implement!

`type NonEmptyArray<T extends any = any> = [T, ...T[]]`

**Comment by sindresorhus** [comment]
Duplicate of #476

**Comment by bvandercar-vt** [comment]
@sindresorhus I see, `NonEmptyTuple` exists. Its type could definitely be improved to allow passing a type restriction to the tuple though.

Current: `export type NonEmptyTuple = readonly [unknown, ...unknown[]]`

Proposed: `export type NonEmptyTuple<T extends any = unknown> = readonly [T, ...T[]]`

**Comment by sindresorhus** [comment]
@bvandercar-vt Comment in the linked issue. This issue is closed and will be lost in time.
