### ISSUE TITLE
NonEmptyObject

### ISSUE THREAD

**Issue by kkmuffme** [sindresorhus/type-fest#621]
Opposite of https://github.com/sindresorhus/type-fest/blob/main/source/empty-object.d.ts (as this would used way more often than EmptyObject for us at least) which ensures that an object contains at least 1 key

Useful for e.g. updates, where all keys are optional, but there must be at least 1 key.

**Comment by sindresorhus** [comment]
👍

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see the initial attempt here: https://github.com/sindresorhus/type-fest/pull/623
