### ISSUE TITLE
The peer deps of `typescript` causes it installed in production mode

### ISSUE THREAD

**Issue by OpportunityLiu** [sindresorhus/type-fest#622]
ref: #598 #606

With a `package.json` like:
```json
{
  "devDependencies": {
    "typescript": "^5.0.4"
  },
  "dependencies": {
    "dep": "^1.0.0" // has a dependency of "type-fest"
  }
}
```
`typescript` will be installed even if in production mode (`npm install --omit=dev`, `pnpm install --prod`, or `yarn install --prod`).

How can I omit the `typescript` package in production mode?

**Comment by sindresorhus** [comment]
// @charpeni

**Comment by OpportunityLiu** [comment]
https://nodejs.org/en/blog/npm/peer-dependencies

> UPDATE: npm versions 1, 2, and 7 will automatically install peerDependencies if they are not explicitly depended upon higher in the dependency tree. For npm versions 3 through 6, you will receive a warning that the peerDependency is not installed instead.

So for npm 3~6, yarn 1, and pnpm with `auto-install-peers=false`, `typescript` will not be installed when you are not explicitly depended it.

However, when `typescript` is depended by the main package, even in `"devDependencies"`, it will be installed due to peer deps.

**Comment by voxpelli** [comment]
One could maybe avoid this by adding:

```json
  "peerDependenciesMeta": {
    "typescript": {
      "optional": true
    }
  }
```

I would rather remove it completely though.

Showing which TS versions you support feels like something for `"engines"` rather than a peer dependency.

@sindresorhus What do you think about adding this?

```json
"engines": {
  "typescript": ">=4.7"
}
```

Eg. tools like VSCode defaults to using their own version of TS anyway, so it should be metadata that can be read explicitly by such tools rather than be inferred implicitly by an installed dependency. (Sorry for not chiming in on the earlier issues)

One can use a tool like my [`installed-check`](https://github.com/voxpelli/node-installed-check) to ensure that one exposes the correct needs of ones dependencies:

```bash
installed-check --engine-check --engine-no-dev
```

**Comment by voxpelli** [comment]
@OpportunityLiu Is that true for optional peer dependencies as well? Not just for optional dependencies?

**Comment by OpportunityLiu** [comment]
In fact, for pnpm@8.5.0, I've tried:

package.json
```json
{
  "pnpm": {
    "peerDependencyRules": {
      "ignoreMissing": [
        "typescript"
      ]
    },
    "packageExtensions": {
      "type-fest": {
        "peerDependenciesMeta": {
          "typescript": {
            "optional": true
          }
        }
      }
    }
  }
}
```

.npmrc
```ini
auto-install-peers=false
```

and install with `pnpm install --prod --no-optional`, and `typescript` is still installed.

**Comment by sindresorhus** [comment]
> Eg. tools like VSCode defaults to using their own version of TS anyway, so it should be metadata that can be read explicitly by such tools rather than be inferred implicitly by an installed dependency. (Sorry for not chiming in on the earlier issues)

Do any tools use `engines.typescript`. If not, I don't really see the point.

**Comment by voxpelli** [comment]
> > Eg. tools like VSCode defaults to using their own version of TS anyway, so it should be metadata that can be read explicitly by such tools rather than be inferred implicitly by an installed dependency. (Sorry for not chiming in on the earlier issues)
> 
> Do any tools use `engines.typescript`. If not, I don't really see the point.

Chicken and the egg problem – if no one publishes it then no one uses it and vice versa. If we think there’s merit to the original issue then we could add it to help solve that issue.
