### ISSUE TITLE
Helper for `fn(...rest, extra)` ("A rest parameter must be last in a parameter list.")

### ISSUE THREAD

**Issue by fregante** [sindresorhus/type-fest#625]
This might not be a good/common idea, but I have a situation where I want to accept an indefinite amount of arguments and then use the last one differently.

In JS this looks like:

```js
function foo(...args) {
	const somtam = args.pop();
	console.log(args, somtam)
}
```

but `.pop()` doesn't really deal with tuples and typing `args` isn't easy.

---

Side note: I think I'll do the opposite in my current [situation](https://github.com/fregante/webext-storage-cache/issues/40), but the API isn't set yet, because it's awkward:

```ts
function set(somtam: string, ...args: unknown[]) {
	console.log(args, somtam)
}
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/625">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/625/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/625/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
You could use https://github.com/sindresorhus/type-fest/blob/main/source/last-array-element.d.ts to get the type of the last element. So what's missing is a `pop` helper, to get the array minus last element. How do you imagine this type would like from a usage standpoint?

**Comment by fregante** [comment]
Nice, I think it would be super awkward but with `ts-extras`:

```ta
const last = arrayPop(args);
assertNoLast(args);
``` 

Maybe it can be done via TypeScript assertion functions, which would be dropped by any compiler since they’re noop. 

ChatGPT suggested another way, which actually seems to alter the tuple: https://www.typescriptlang.org/play?target=9#code/FDAuE8AcFMAICVoFsD2A3aAZAhgZ1AKIA2y0AdqADwAqs0AHqOQCa6zZngDaAugHywAvLFoMmZVrC4A6WQEsyAM2gAnWAFUANO049YAfg2wAXLDLQMKgNwhFAVzIBjUHJRlYK5Oix5CJJORUoowsbBzc-AAUoHaQJKbUAJSmiKgYOPjEpBQ0AgDewLCwjm74sCRkAOagABZCsDFx0NIV1TU2RXKKsJGttbCUwgCMibAFRUWeMSruvOxsqd4ZftlBfB2wAL6FHtDT7o0k0rhEco7QkQAM2n11ALSwI-MIXum+WQE51OvA28AlZDKSHA1Fi8SkZDsSAARqptPgVApKtpoSgUCQOHphFwhtoAESgADuKDx2lAKjs0B4NgBZVizGwTGYoKa9U8aR8mX8gUiwJZJESGwmRQA9CLYAA9fT-Uro5pEFCVSL0xnQZlg6CCkBAA

Maybe a less awkward usage would be a function that returns the altered array:

```TS
function arrayWithPop() {
  // 🪄 
  return [rest, last]
}

**Comment by sindresorhus** [comment]
> Maybe a less awkward usage would be a function that returns the altered array:

Yeah. I think this would be the best solution. With a better name.

**Comment by fregante** [comment]
> With a better name

I didn't realize that they had changed the names: https://github.com/tc39/proposal-change-array-by-copy

- `arrayToPop` 😬 
- `restFirst` 😴
- `splitLast` 🙏

**Comment by papb** [comment]
Is the function going to mutate the array (like `.pop()`), or not?

**Comment by fregante** [comment]
> Is the function going to mutate the array (like `.pop()`), or not?

I don’t think that's possible without 2 separate function calls (one to create `last` and one to `assert args`) in TypeScript, so probably not.

**Comment by sindresorhus** [comment]
No, it would be immutable.

**Comment by papb** [comment]
In this case I vote for the name `splitLast`

**Comment by fregante** [comment]
That reminded me of a similarly-named package (for strings) https://www.npmjs.com/package/split-on-first
