### ISSUE TITLE
Is there a way to check that a key conforms to a base type without using an interface?

### ISSUE THREAD

**Issue by matthew-dean** [sindresorhus/type-fest#631]
I've read through the types in `type-fest`, and I want to do something like this:

```ts
interface Request {
  data: Record<string, any>
}
interface BaseUpdateCollectionRequest extends Request {
  data: {
    title: string
    linkIds: string[]
  }
}
export type UpdateCollectionRequest = Simplify<BaseUpdateCollectionRequest>
```
Ideally, I'd like to do something like an interface extends, but without an interface, so that I can type-check that a definition of `data` conforms to the base definition and correctly extends it. But without having to define a base interface that gets assigned / re-exported as a type.

Are there types here that allow this?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/631">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/631/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/631/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
Sounds like you want the [`satisfies` operator](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#satisfies).

**Comment by matthew-dean** [comment]
You can use `satisfies` on a type? 🤔

**Comment by ethanjdiamond** [comment]
+1 from me on this. Satisfies would be useful on a type when I want to create a union type that follows a pattern. See the answer in the comments for https://stackoverflow.com/questions/76367389/satisfies-but-for-types.
