### ISSUE TITLE
Is it possible to Omit native type like booleans or numbers?

### ISSUE THREAD

**Issue by silversonicaxel** [sindresorhus/type-fest#653]
I would like to know if it is possible to have a scenario like this one:

```
type A = {
  a: string;
  b: number;
  c: boolean;
  d: boolean;
  e: boolean;
};

type B = Omit<A, boolean>;
```

where type B looks like this

```
type B = {
  a: string;
  b: number;
};
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/653">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/653/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/653/pledge.svg">
</picture>
</a>

**Comment by tommy-mitchell** [comment]
[`ConditionalExcept`](https://github.com/sindresorhus/type-fest/blob/main/source/conditional-except.d.ts) should work:

```ts
type B = ConditionalExcept<A, boolean>;
```

**Comment by silversonicaxel** [comment]
Amazing, last part of question is, what if one boolean is optional?
Because now, considering this example:
```
type A = {
  a: string;
  b: number;
  c: boolean;
  d?: boolean;
  e: boolean;
};

type B = ConditionalExcept <A, boolean>;
```

type B looks like this:
```
type B = {
  a: string;
  b: number;
  d?: boolean;
};
```

**Comment by tommy-mitchell** [comment]
`d?: boolean` is the same as `d: boolean | undefined` (for most cases). One solution is to use the built-in `Required` utility type ([TS Playground](https://tsplay.dev/Nry6zw)):

```ts
type B = ConditionalExcept<Required<A>, boolean>;
```
