### ISSUE TITLE
`MergeDeep` doesn't preserve `readonly` modifier

### ISSUE THREAD

**Issue by shaungrady** [sindresorhus/type-fest#655]
The `Merge` type preserves the `readonly` modifier, but `MergeDeep` does not:

```ts
type Foo = { foo: 'foo'; fooBar: string[] };
type Bar = { readonly bar: 'bar'; fooBar: number[] };

type FooBarMerge = Merge<Foo, Bar>;
type FooBarMergeDeep = MergeDeep<Foo, Bar>;

const fooBarMerge: FooBarMerge = { foo: 'foo', bar: 'bar', fooBar: [1] }
const fooBarMergeDeep: FooBarMergeDeep = { foo: 'foo', bar: 'bar', fooBar: [1] }

// @ts-expect-error Shown error as expected
fooBarMerge.bar = 'bar'
// @ts-expect-error No TS error is shown here
fooBarMergeDeep.bar = 'bar'
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/655">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/655/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/655/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
// @skarab42
