### ISSUE TITLE
Jsonify fails on nested object with name property. 

### ISSUE THREAD

**Issue by RalphSleigh** [sindresorhus/type-fest#657]
Code here:
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgKQM4QHbAGYE84C+c2UEIcARDLmAKYC02tqMFA3AFAfV1wQBGAKwByzGLQAmwgIYhacALyIOcVcWBQWALmVq9cDLNo6WUYBgDmKtQQ63uNeQJFjJwiDLmLda7Bu0++gYQMJ7GcKbmVnq29jzygugYAOrAMAAWYd5omDi4ADzOoixuRgB8DryJmADyQsXiUh5G2Ul5hfWuTWFlQA

```
import { Jsonify } from "type-fest";

type objNestedName = {
    first: {
        name: string
    }
}

type objNestedNoName = {
    first: {
        notName: string
    }
}

type jsonWithName = Jsonify<objNestedName>
type jsonObjNestedNoName = Jsonify<objNestedNoName>
```

Note if you mouseover the second one you can see inside the object, but the first one is an empty object. Might be wrong but I am fairly sure name is not a reserved word in typescript or ES6 so would expect this to work.

**Comment by sindresorhus** [comment]
When I mouse over them in the playground, they both show the same thing.

**Comment by RalphSleigh** [comment]
### Playground
Yeah, output has changed since I posted the issue. Not sure why there, maybe due to the release? The mouseover now displays both as:

```type objNestedNoName = {
    first: {
        notName: string
    }
}```

Which is not right either, but the structured types plugin gets it right if you enable/run that.

### Locally

I updated to the latest version of type-fest locally and can still see the issue in visual studio code: 

![Screenshot 2023-08-01 115753](https://github.com/sindresorhus/type-fest/assets/4304184/09dbec06-0edd-486a-9ed1-a593d587a43a)
![Screenshot 2023-08-01 115747](https://github.com/sindresorhus/type-fest/assets/4304184/7f7a8796-c2a5-42a1-9640-9b1fc2b35a2d)

**Comment by RalphSleigh** [comment]
Trying to narrow this down, I made a new folder and added that example, Node is: 17.8

`npm install typescript type-fest`

This gets me typescript 5.1.6 and I can see the issue

`npm install type-fest@2.19.0`

No issue

`npm install type-fest@3.0.0`

Its back.

**Comment by donovanhiland** [comment]
@sindresorhus @RalphSleigh I'm experiencing the same thing today, dug into it a bit and found this. `BaseKeyFilter` is used in Jsonify:

```typescript
import { Jsonify } from "type-fest";

type objNestedName = {
    first: {
        name: string
    }
}

type objNestedNoName = {
    first: {
        notName: string
    }
}

type jsonWithName = Jsonify<objNestedName>
type jsonObjNestedNoName = Jsonify<objNestedNoName>

type BaseKeyFilter<Type, Key extends keyof Type> = Key extends symbol
	? never
	: Type[Key] extends symbol
		? never
		: [(...arguments_: any[]) => any] extends [Type[Key]] // <------- I think is where the issue lies
			? 'Uh oh' // <------- Which lands us here (it's `never` actually but you get the idea)
			: Key;

type Test1 = BaseKeyFilter<objNestedName, 'first'> // 'Uh oh'
type Test2 = BaseKeyFilter<objNestedNoName, 'first'> // 'first'

type SomeObjWithNameProp = { name: string }
type SomeFunction = (...args: any[]) => any

type Test3 = [SomeFunction] extends [SomeObjWithNameProp] ? 'Uh oh' : 'Yay' // 'Uh oh'

type Test4 = SomeFunction extends Record<string, unknown> ? 'Uh oh' : 'Yay' // 'Yay'
type Test5 = SomeObjWithNameProp extends Record<string, unknown> ? 'Yay' : 'Uh oh' // 'Yay'

type FixedBaseKeyFilter<Type, Key extends keyof Type> = Key extends symbol
	? never
	: Type[Key] extends symbol
		? never
        : Type[Key] extends Record<string, unknown>  // <------- If we check for record first this helps
            ? Key
		    : [(...arguments_: any[]) => any] extends [Type[Key]]
			    ? never
			    : Key;

type Test6 = FixedBaseKeyFilter<objNestedName, 'first'> // 'first'
type Test7 = FixedBaseKeyFilter<objNestedNoName, 'first'> // 'first'
```

[Playground link](https://www.typescriptlang.org/play?ssl=48&ssc=58&pln=1&pc=1#code/JYWwDg9gTgLgBAbzgKQM4QHbAGYE84C+c2UEIcARDLmAKYC02tqMFA3AFAfV1wQBGAKwByzGLQAmwgIYhacALyIOcVcWBQWALmVq9cDLNo6WUYBgDmKtQQ63uNeQJFjJwiDLmLda7Bu0++gYQMJ7GcKbmVnq29jzygugYAOrAMAAWYd5omDi4ADzOoixuRgB8DryJmADyQsXiUh5G2Ul5hfWuTWEVlfIAQtKotADStLgAYsAANuJQ+QAqjgA0cGP4tAAe4hgSqHAA1uMQ2HBLdGXe63BbO3sRuCD8ENMcAJAA-Aa0AG60UO8dOdaABtdYAXRu21ou32qEez1eb0+3z+AOROhBAAoAHR46RQCwAVzkGBgqAA+jppBhcCDwQBKRSXGm4SG3GH3EHAsHjcGQgD0Arg+XoYvFErFcAAknAMuYDnBgPsAO7pf7yDLyZWoInyabAZjvZFfADkAFV0nx0qa4EKRZLHfQ4Ml0sAAMZW6Y0+5E-bqqDyLFpU37AAGGF+-zDcGk7pgROk02m+H4RPguAgRLgFlo8C1SoktGkDONbx0604fTOYgAjN5BsN1lNZv8Oi4SlIjKtTX5NDBTRV4jWWAAmBtDUbjFtzdsNNzNOQ9vssQdcYcAZTItDqglSGTCAAVSGBvEhDHITDAzJZCNWt3IJkSMPHgJhvLj8YTUNTafSmQoLK0uujgjjAADM3ggg+tBPi+MBvhg7LQrCcDQduu77pkRjHhAYCQmalrWraOimgAmtIuCmiBvALGIAAs3gwXBr7vhyqEAEq0O60ASPkkSWKsz4HBgEAqhglxmpgtAkXApowCqEDUcOdEsAArExGFCFhR4nlCdz7FxPFQHxAkWEJGAiWJElwFJkayfJinUdWUybJIjZTpMMyzsCqzXOx9xHJmpzApcSj+Sh9zwk8LzvF8kZooCZyOLybL6ZycIIrFJqov81hBECKUQulnHcbx-HXlEFlWeJlx2sKopOhKMqnCq8ietxirYNAcCBsZEjqP2cpuv6tDTGAqD5UEahfOsxp6Jin44gSxKkuSVKxn+jLMptaUBfs3JFXy4Jlno8VRuiyILWs4xVipYgAGzeK57mTs23ltkUXRhMu-gDkOoGqTAADsz3AG5Egee9rbzF9nbuD9ckrv9QA)

**Comment by sindresorhus** [comment]
It seems https://github.com/sindresorhus/type-fest/commit/d83d62c9668952337f072f1b06fc83184156e34f is the cause then.

**Comment by RalphSleigh** [comment]
@donovanhiland Thanks, appears for now I can work around this by adding another property. 

@ThomasBoxall Cool huh?

**Comment by sindresorhus** [comment]
@donovanhiland Thanks for looking into this. Would you be willing to submit a pull request?

**Comment by donovanhiland** [comment]
@sindresorhus Sure I can probably put something up this week

**Comment by nmackey** [comment]
Any status updates on this?

**Comment by duvet86** [comment]
After a quick investigation I found that "UndefinedToOptional" is causing the issue. Removing it allows all the properties to be visible again.

**Comment by duvet86** [comment]
Ok, the root cause is "BaseKeyFilter". If we replace 
`[(...arguments_: any[]) => any]`
with
`((...arguments_: any[]) => any)`
Square brackets with round ones everything works.

**Comment by milamer** [comment]
I fixed this via a patch for me. Not sure if other problems arise with this (version 4.3.1)
```diff
diff --git a/node_modules/type-fest/source/internal.d.ts b/node_modules/type-fest/source/internal.d.ts
index ea479aa..64cb298 100644
--- a/node_modules/type-fest/source/internal.d.ts
+++ b/node_modules/type-fest/source/internal.d.ts
@@ -189,7 +189,7 @@ type BaseKeyFilter<Type, Key extends keyof Type> = Key extends symbol
 	? never
 	: Type[Key] extends symbol
 		? never
-		: [(...arguments_: any[]) => any] extends [Type[Key]]
+		:   [Type[Key]] extends [((...arguments_: any[]) => any)] 
 			? never
 			: Key;
 
```

**Comment by duvet86** [comment]
That solves the issue but breaks existing unit tests.

**Comment by milamer** [comment]
@donovanhiland 

Thanks for the quick fix, but I still have this error with a type like this
```ts
{ name: string } | null
```
