### ISSUE TITLE
Expose `UnknownRecord` in the public API

### ISSUE THREAD

**Issue by MatanYadaev** [sindresorhus/type-fest#659]
Currently `UnknownRecord` can be imported only from an internal file:
```ts
import { UnknownRecord } from 'type-fest/source/internal.js';
```

However, this type is very handy and I use it frequently in my app. I believe it's fair enough to expose it like the other types:
```ts
import { UnknownRecord } from 'type-fest';
```

**Comment by tommy-mitchell** [comment]
I agree, especially since `typescript-eslint/ban-types` recommends [using a similar type](https://typescript-eslint.io/rules/ban-types/) over `{ }`.

**Comment by sindresorhus** [comment]
PR welcome :)
