### ISSUE TITLE
Proposal: OneOrMore

### ISSUE THREAD

**Issue by CarsonF** [sindresorhus/type-fest#66]
```ts
type OneOrMore<T> = T | T[];
```
lodash also has this type named as `Many`.

This is useful when you have a complex type:
```ts
OneOrMore<Validator<Value> | null>
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/66">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/66/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/66/pledge.svg">
</picture>
</a>

**Comment by resynth1943** [comment]
Hmm. Could you share a use-case for this?

**Comment by CarsonF** [comment]
If you are accepting one or more of `T` then `T` has to be written twice without this.
```ts
Validator<Value> | Array<Validator<Value>>

((...args: any[]) => any) | Array<((...args: any[]) => any)>
```
vs:
```ts
OneOrMore<Validator<Value>>

OneOrMore<((...args: any[]) => any)>
```
The latter is DRY and is quicker to comprehend.

lodash uses their `Many` (same thing) abundantly.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/common/collection.d.ts

**Comment by resynth1943** [comment]
Right then. I'm happy to send in a PR for this.

**Comment by CarsonF** [comment]
I noticed lodash's uses `ReadonlyArray` which would probably be better.

**Comment by resynth1943** [comment]
Done.

**Comment by fregante** [comment]
Recently added as `Arrayable`: https://github.com/sindresorhus/type-fest/blob/main/source/arrayable.d.ts
