### ISSUE TITLE
Expose `NonEmptyTuple`

### ISSUE THREAD

**Issue by tommy-mitchell** [sindresorhus/type-fest#661]
Similar to #659, `NonEmptyTuple` is a convenient type to expose:

https://github.com/sindresorhus/type-fest/blob/f63c3437bc483e7532698d14548494802c04f372/source/internal.d.ts#L90-L93

We could augment it to accept a generic type argument:

```ts
type NonEmptyTuple<TupleType = unknown> = readonly [TupleType, ...TupleType[]];
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/661">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/661/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/661/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
PR welcome 👍

**Comment by sindresorhus** [comment]
> We could augment it to accept a generic type argument:

👍

**Comment by tommy-mitchell** [comment]
Hm, maybe it's not such a good idea? You can't use `array.length` checks to guard against empty arrays, and sparse arrays add a lot of edge cases: https://github.com/microsoft/TypeScript/issues/38000 ([SO thread](https://stackoverflow.com/questions/56006111/is-it-possible-to-define-a-non-empty-array-type-in-typescript))

```ts
function printFirstElement<Tuple extends NonEmptyTuple>(tuple: Tuple) {
	console.log(tuple[0]);
}

printFirstElement(['a', 'b', 'c']);
//=> 'a'

printFirstElement([]);
//=> error TS2345: Argument of type '[]' is not assignable to parameter of type 'NonEmptyTuple'.

declare const arr: string[];

if (arr.length > 0 {
	printFirstElement(arr);
	//=> error TS2345: Argument of type 'string[]' is not assignable to parameter of type 'NonEmptyTuple'.
}
```
