### ISSUE TITLE
Broken link on paka.dev in readme.md

### ISSUE THREAD

**Issue by zkulbeda** [sindresorhus/type-fest#663]
In readme link [![Docs](https://paka.dev/badges/v0/cute.svg)](https://paka.dev/npm/type-fest) leads to page that will never load. I tried open it on multiple browsers (Firefox, Chrome, Edge) and on Android.
I couldn't find the paka.dev project repository to open an issue, so I opened it here.

![image](https://github.com/sindresorhus/type-fest/assets/24959171/4734163c-ebe1-4938-872f-235576c8d79e)

**Comment by sindresorhus** [comment]
// @schickling
