### ISSUE TITLE
Support composable tagged types

### ISSUE THREAD

**Issue by ethanresnick** [sindresorhus/type-fest#665]
Type-fest's current implementation of opaque types is great for attaching _one_ tag to a type. However, it does not support attaching _more than one_ tag to the same type, which is often useful to represent multiple validations that have been performed on a value, or multiple "aspects" of how it can be interpreted.

For example, the Typescript discussions about tagged types [use the example](https://github.com/microsoft/TypeScript/pull/33038) of a string that can be an absolute path, a normalized path, _or both_. Similarly, in my code, I have a tagged type representing URLs and a tagged type representing the ids used by a particular sub-system, but these subsystem ids happen to also be URLs. Therefore, I'd like to have:

```ts
type Url = Opaque<string, "Url">;
type SubsystemId = Opaque<Url, "SubsystemId">;

// NB: SubsystemId above is ultimately the same as:
// string & Tagged<"Url"> & Tagged<"SubsystemId">
```

That way, I can pass a `SubsystemId` to any utility function I have that takes a `Url`, too.

If you try this sort of thing in type-fest today, though, [you run into problems](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeTAQwI4FcCmcC+cAZlBCHAOQwCeYOAtETgM4wUDcAsAFA11wBBAEbMIAGywwcABTQwAFnAC8KdNhwAeVlGAA7AOYAaSsNESpshRQB8XXrTwA5aCDRjgALxwATS4pWomLhaMDoGxhTOUK7uXr5y8jZ2fHjS8hC6OI5YIEI4UMqqQZraekaUaRlZOXlQSTw83jgAxmJoUHhEWLrNMMAZcMDMpuKSMgkaACpwOAAeUrrezHClBtYAFMAwAFxwkwCUu1uDy9MAZIIioxYJdk2t7Z3dvf26cB3YwB3MlZnZuflNjs4L9qgCoIc4AA3CDAbx2HgAekRKywYEgzDwAHc8G4OmhvNQ4PI0FDcdC3Lg4Ao5MS0MsqtS0Po4HIYGhmvIfNSIIMYMsUgA6RotNodODNDKsOC6FxuTw+Py7KIxBXxBQI7jImUQLHGHFwLFoXTwGC8qHy7xyPDHLqwLlQfXyYCclbpLBibys9FiIloFYtDJe9ks43eJEosQ4eBYZboZgCrkUiR4M3EZ59KXvHCfMIsmmm5k8YBETbDK7mcYKday6LyuJ+fb7RA8OBwbUKIYStxiN0QD1eohoYBiYx5ZpoWOppPoBQnOBNIh6LY4X1wAD6spg69ZcDA6UyMpq+Tsbe1elYOAJxmOzCwzWaOB8y3Hk8x1KTKTgECIcAABrWqoNgkf50i+T5vK27Yoh03j3tyaYATgZJQH+xhQAk+QfsacAqvWioJHAFwjJWfhQR8WBfCwoL-LUNZyrEBEKPsdj4EAA):

```ts
type AbsolutePath = Opaque<string, 'AbsolutePath'>;
type NormalizedPath = Opaque<string, 'NormalizedPath'>;
type PhoneNumber = Opaque<string, 'PhoneNumber'>;

declare function isAbsolutePath<T extends string>(it: T): it is T & AbsolutePath;
declare function requiresPhoneNumber(it: PhoneNumber): void;

// suppose we already have a value that has one tag attached to its type.
declare const normalizedPath: NormalizedPath;

// now, we want to validate it further, which should apply a second tag and
// let us pass the value to functions requiring that tag
if(isAbsolutePath(normalizedPath)) {
  // this call should fail, because the path is definitely _not_ a phone number;
  // instead, it succeeds because the type of `normalizedPath` has been 
  // reduced to `never`, rather than `NormalizedPath & AbsolutePath`
  requiresPhoneNumber(normalizedPath);
}
```

The root of the issue is that:

1. the Typescript compiler has some built-in hacks that tell it not to reduce `string & Tagged<"NormalizedPath">` to `never`, even though there's no runtime value that can actually be both a string and an object w/ a symbol-named property, which is what that type requires; 

2. however, as soon as the type becomes `string & Tagged<"NormalizedPath"> & Tagged<"AbsolutePath">`, those hacks are insufficient and the type is immediately reduced to `never`, as shown [here](https://www.typescriptlang.org/play?#code/PTAEGEHsAcEsFMAmoDOAXATgQ1gcwBZqgBmGkAtqGgJ7TwC0x86AsAFCLwDGANlhvFBdIAO3RUsuAFygAriNgBHWYJTVyAI0g8A3O3YgIMBMnTY8hEmUo06jZmnade-QbcEAVSbiQAeD5AA1vAiAHygALygAN7sAJACWIiiPNSgANpokgC6MgHBInpsAL5FBmAetMxcGLDQRMLkcDzwGKD4WCioFIIasrA8aPSwIu1YXIFdAO74sFz4oFg8PJBToLBE5VSQoAD6IpBou6ACiLJcbrNdaDsABiLwAG6ttwA0oE8hVPiQsgTfrXgAHIugcTvI0LByPB2O5QAANSKoTAjXCgABkoC8uB8iF8ACIAHKQDDkJawABeSAAClg0Ph8eFMdjcQSAIIaFDaWRoeC0+mMopAA). The compiler  sees `{ [tag]: "NormalizedPath" } & { [tag]: "AbsolutePath" }` and determines (correctly) that the strings in the  `[tag]` property cannot both be satisfied.

The way to work around this, as described [here](https://github.com/microsoft/TypeScript/pull/33290), is to use an object type to store all the tags, and use _one key per tag_ in that object. I.e., instead of `SubsystemId` ultimately being represented like:

```ts
string & { [tag]: "Url" } & { [tag]: "SubsystemId" }
```

which reduces to `never`, you represent it as:

```ts
string & { [tag]: { Url: void } } & { [tag]: { SubsystemId: void } }
```

which is equivalent to:

```ts
string & { [tag]: { Url: void, SubsystemId: void } }
```

This ends up working very well with the structural nature of Typescript, in that a function that needs its argument to only have one of the tags can still be called with an argument that has more tags (by the normal TS rules for allowing excess object keys); meanwhile, the structure of the type prevents reduction to `never`, because the `{ [tag]: { Url: void, SubsystemId: void } }` part actually _is satisfiable_, which is enough for the TS compiler hack to preserve the full type when intersecting with `string`.

All of this is to say: **supporting types with multiple tags is definitely possible, and I'd be happy to put up a PR. `UnwrapOpaque` can be made to work too. However, representing tagged types like this would be a breaking change, in two ways:**

1. The `Token` parameter on `Opaque` is currently unconstrained; with this implementation, it would have to extend `string | number | symbol`. I don't actually think that limitation is a big problem, because `Token` is usually a literal string in my experience, and, for people who want even stronger guarantees about the uniqueness/non-assignability of different opaque types, the ability to use a `unique symbol` type as the `Token` is sufficient. However, this example from the current documentation would no longer be supported:

    ```ts 
    type Person = {
      id: Opaque<number, Person>;
      name: string;
    }; 
    ```

     One would instead need to do:

    ```ts
    type PersonId = Opaque<number, "PersonId">; 

    type Person = {
      id: PersonId;
      name: string;
    }; 
    ```

    or, for the super-paranoid:
    
    ```ts
    declare const personId: unique symbol;
    type PersonId = Opaque<number, typeof personId>; 
    ```

2. Second, the underlying representation is different enough that type-fest users who've built their own utility types that inspect the current `Opaque` types might need to update their logic.

So, my questions for you @sindresorhus are: Do you think this multiple tags functionality is valuable? If so, do you think it's acceptable to break the current API in the (imo, relatively small) ways mentioned above?

If those breaks are not acceptable, another option would be to introduce a new type that's basically the same as `Opaque`, except that it supports multiple tags. I think that `UnwrapOpaque` could be made to work on both the current `Opaque` type and the new version. The only potential downsides to that approach are: 

1. We'd need a new name for this new type, and (for a while) there'd be two types in type-fest with similar functionality. Personally, I think having a new name could be a good thing, because the `Opaque` name is actually kinda misleading: the type is not opaque at all, in that the type of the runtime value is very plainly exposed and usable — i.e., an `Opaque<string, 'X'>` can be passed to any function that takes a string, which means its "string-ness" is not hidden and can be depended on in code outside the module where the "opaque" type was defined. Given that, I'd be tempted to call the new type "Tagged" and rename the existing `Tagged` type (which isn't exported so should be fine to rename) to something like `TagContainer`.

2. Existing `Opaque` types that use a `Token` which isn't a string, number, or symbol couldn't interoperate with the new tagged types.

3. All the types would be a bit more complicated, to support interoperability between the old and new form of tagged types.

**Comment by sindresorhus** [comment]
Such a type would be welcome. It should be a new type (we can eventually deprecate `Opaque` if this one turns out to be better). I think the name `Tagged` or `Brand` makes sense.

**Comment by yoursunny** [comment]
Please do not deprecate `Opaque`.
The new `Tagged` type requires the tag to be a `PropertyKey`.
I have a use case in which an arbitrary type would be used as the tag:
https://github.com/yoursunny/NDNts/blob/9f4ad1258e071ae5e3a9146137b28d31b590e37a/integ/browser-tests/test-fixture/serialize.ts
Thus, I hope both types can be kept.

**Comment by sindresorhus** [comment]
@ethanresnick Is there any way `Tagged` could support this? If not, we should document it as another difference between the types.

**Comment by ethanresnick** [comment]
@sindresorhus Yes, I actually think that use case doesn't require `Opaque`, if I'm understanding it correctly. We have a very similar use case in our code at work, and there's a natural extension to `Tagged` that I was planning to propose anyway, which would make this even more ergonomic.

Basically, as I understand the use case from @yoursunny, the idea is to have a type that means "this is a string of JSON that, when parsed, will give back a `T`".

At my work, we have a type for that called `JsonOf<T>`, which works like this:

```ts
declare const meta: unique symbol;
export type JsonOf<T> = Tagged<string, "JSON"> & { readonly [meta]: T };

export function jsonStringify<T extends JsonValue>(it: Readonly<T>) {
  return stringify(it) as JsonOf<T>;
}

export function jsonParse<T extends JsonOf<unknown>>(it: T) {
  return JSON.parse(it) as (typeof it)[typeof meta];
}
```

So `Opaque` isn't strictly needed, although the need for the extra `meta: unique symbol` is definitely a bit of an ergonomics hit.

If you compare the resulting types, though, between `JsonOf` and the `Value` type from @yoursunny's example, they look like this:

`JsonOf<{ hello: 'world' }>` expands to... 

```ts
string & { [tag]: { "JSON": void } } & { [meta]: { hello: 'world' } }
```

whereas `Value<number>` expands to

```ts
string & { [tag]: { hello: 'world' } }
```

The latter is simpler, though actually looses the ability to know that all such values are strings of JSON.

I think the best approach — the one I was going to propose — is to end up with a type like this:

```ts
string & { [tag]: { "JSON": { hello: 'world' } } }
```

This keeps all the composability of `Tagged` compared to opaque (i.e., one base type can have multiple "tags"), but extends it to allow each tag to provide _arbitrary_ type-level metadata. So, the above type is saying: "this is a string tagged as `"JSON"`, and the JSON tag's metadata includes the type you'll get back when you `JSON.parse` the string.

From an implementation perspective, this is _very_ simple and backwards compatible: it's just taking the current `Tagged` type and, where `void` is currently hardcoded (in `MultiTagContainer`), making `void` a default instead (i.e., the default is that a tag has no metadata) while allowing the user to override it.

So, it'd simply be:

```ts
type MultiTagContainer<Token extends PropertyKey, TagMetadata> = {
  readonly [tag]: { [K in Token]: TagMetadata };
};

type Tagged<Type, Tag extends PropertyKey, TagMetadata = void> = Type & MultiTagContainer<Tag, TagMetadata>;
```

Then, @yoursunny's type and my JsonOf type could be unified as simply:

```ts
type JsonOf<T> = Tagged<string, "JSON", T>
```

with no need for the extra `meta` symbol I had before.

**Comment by sindresorhus** [comment]
Thanks for explaining. Makes sense to me to support this.

**Comment by ethanresnick** [comment]
Awesome :) I can put together a PR at some point, but definitely can't promise a date. Or, if someone else wants to take this, that'd be great! It should be quite straightforward from my comment above; just involves writing new test cases etc. 

The only detail worth thinking about is around what the desired assignability semantics should be, based on tag metadata. E.g., with the implementation in my comment above, and having:

 ```ts
type A = Tagged<string, "JSON", MetaA>
type B = Tagged<string, "JSON", MetaB>
```

`A` will be assignable to `B` if (and only if) `MetaA` is assignable to `MetaB`. 

I'm pretty sure that's exactly what we want — and people who want invariant behavior can get that using the `InvariantOf` helper type (e.g., `type JsonOf<T> = Tagged<string, "JSON", InvariantOf<T>>`) — but I haven't thought about it in enough depth/gone through all the use cases to say that with total confidence.

**Comment by ethanresnick** [comment]
Ok, turns out I had a bit of time, so I threw up a quick PR in #723.
