### ISSUE TITLE
SingleOrArray - Add type for a single value or an array of values

### ISSUE THREAD

**Issue by Michael-Ziluck** [sindresorhus/type-fest#666]
Fairly straightforward type but quite useful. It's often that APIs will have a function that accepts `string | string[]` or similarly `string | FooType | string[] | FooType[]`. It would be nice to express these instead as `SingleOrArray<string>` or `SingleOrArray<string | FooType>`.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/666">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/666/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/666/pledge.svg">
</picture>
</a>

**Comment by fregante** [comment]
This exists and is called Arrayable.
