### ISSUE TITLE
Missing export after adding `Tagged` type

### ISSUE THREAD

**Issue by tommy-mitchell** [sindresorhus/type-fest#674]
`Exact` imports `TagContainer` from `Opaque`:

https://github.com/sindresorhus/type-fest/blob/9250be2c897dbae78b4b107d3c5b9ed02affaeb2/source/exact.d.ts#L1-L3

`TagContainer` is no longer exported in v4.3.0:

https://github.com/sindresorhus/type-fest/blob/9250be2c897dbae78b4b107d3c5b9ed02affaeb2/source/opaque.d.ts#L1-L9

**Comment by sindresorhus** [comment]
Why doesn't TypeScript catch this? Seems like something it should do... (Open a TS issue maybe?)

**Comment by tommy-mitchell** [comment]
Might be something to do with `.d.ts` files? In `meow`, we were importing `AnyFlag` in the `tsd` test even though it wasn't exported from `index.d.ts`. I only caught it because the build type test couldn't import the `AnyFlag` type.

**Comment by ethanresnick** [comment]
Sorry about this! Id have thought TS would catch this too…
