### ISSUE TITLE
Add `Expand` type

### ISSUE THREAD

**Issue by olalonde** [sindresorhus/type-fest#678]
Would you be open to [adding this type](https://github.com/microsoft/vscode/issues/94679#issuecomment-755194161)?

```typescript
type Expand<T> = T extends infer O ? { [K in keyof O]: O[K] } : never;
```

It's useful for debugging types in an IDE.

**Comment by sindresorhus** [comment]
Isn't this just [`Simplify`](https://github.com/sindresorhus/type-fest/blob/main/source/simplify.d.ts)?

**Comment by olalonde** [comment]
Oops, missed that one and `SimplifyDeep`.
