### ISSUE TITLE
Type error: '?' expected.

### ISSUE THREAD

**Issue by fgrs** [sindresorhus/type-fest#683]
I'm getting Type error here: https://github.com/sindresorhus/type-fest/blob/7950542f8fd001cae65a8fe76f467edd30cdd937/source/camel-case.d.ts#L25

```
./node_modules/type-fest/source/camel-case.d.ts:25:32
Type error: '?' expected.

  23 |  OutputString extends string = '',
  24 | > = Words extends [
> 25 |  infer FirstWord extends string,
     |                                ^
  26 |  ...infer RemainingWords extends string[],
  27 | ]
  28 |  ? Options['preserveConsecutiveUppercase'] extends true
error Command failed with exit code 1.
```

**Comment by fregante** [comment]
You'll have to upgrade to TypeScript 4.7 or later.

Tested in v4.6: _fails_ https://www.typescriptlang.org/play?ts=4.6.4#code/FDD0Cp2BhBDBbApgGzgZ0QAgPYAcAuAltgHZoB0IAAhlgN5XKEkDWmcSqsGAvsOKGCIAHrmwAnfJnwBPXFg4p0iAPIFiZTAF5MdYAEgIUfQHUAFonwXx07JlzjEGcQDdEAE0wBjUhi8BXIjdMf1x5cS9uLGRLfERxSgMqd0QAM1h-ZCl8cX9EAwEDByd4t2hfRACgxABVMPjIjAB+AC5MACNsbBjYEgBuYB4BsEgYUjdJTF6p8XFYGRxUzAB3CXc0W28EFABaRsRKQtl5dm2uDAAxcWx4AEFZ+YAeAxM1jZE4knXMNBzmAHMANoAXQANAY1ERfJgPogvhtFOdVOpfOD9CpArhAgBlP4kf4w4Sfb6-cQA7SYADklPBAD4Ka9xN9YfDMICDMxUvFMBdCOJfozPCySXj-mjyBLOdyAEqIeCwZgAwXvIlwkVk-Eg8HAgxNTCQjRoQGU4rOMoVKqENx1cL7SnAwnEjY5PIGfR6gAGABI6HBcIR8LAmAAvRCPXn8-CC2k8H2I5RXG73OYyR6y+WK-HK0H6lFkGMet1tb2+2D+wMhsMAGWwywaUXDfIFa1pMbjZwT1zuD1T6YVJCVbxzBt8BYMbQx+Cx+FxGv+AyAA
