### ISSUE TITLE
Proposal for ModifyType ?

### ISSUE THREAD

**Issue by nmccready** [sindresorhus/type-fest#69]
I find myself utilizing this useful type often for overriding a root type's fields with a different type.

https://stackoverflow.com/questions/41285211/overriding-interface-property-type-defined-in-typescript-d-ts-file#answer-55032655

Impl Type
```ts
type ModifiedType = Modify<OriginalType, {
  a: number;
  b: number;
}>
```

Example:
```ts
interface OriginalType {
  a: string;
  b: boolean;
  c: number;
}

type ModifiedType  = Modify<OriginalType , {
  a: number;
  b: number;
}>

// ModifiedType = { a: number; b: number; c: number; }
```

Would you all consider adding this or is there an existing suitable type in here already?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/69">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/69/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/69/pledge.svg">
</picture>
</a>

**Comment by devinrhode2** [comment]
Here's another [approach](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKg8gJwCYQVAvFA3gKClASyQC4oBnYBAgOwHMBuPKAQzLINuoiRgHsB+UgFdqAa2q8A7tUYBfHDgD0iqMF5JmIYjlCQoAW3UEAZgW5wARgCsIAY2AYocfQWAAeeMlQAaKAHJWdk5uPj8APigAMmwmQI4uHl5SCio6OUYlFUleIQAbJChcglEIbV1oAFkjYxAABQReSARQGHAINyZ4azsHCAAPYAhqJDIoACU7XmQ3FJpaX2ZqEDDvTvrG1FAofsHh0ZKQXmNYSxt7VfwYADkISVbIVYjMZ1cPU57fGHWm0Ajo3HwAG0+oRqLBvpsQABdUjXW73CDpBQKcoGapmJDvewAJkcVSQJjqDR+IARby8CF8ATY8RCvD8vlmdDCGWUUAAbtiym0oPjCRDmqS2tiOpcsb0BkMRuNJtMmfMWEsVp1xbVmMBbAALbaSvYy2xTJAzShzBZKnBPJwudxdM7AXwHI4nbr2NUazV-GJAkE0KCO462npurUw5124OawH+sNB9UhpHI1GGAmmcwu4AAZjx1SJG0FCJFnhQlOwLBpwUSyRNdCgshZQA):
```ts
type TOrder = {
  id: string;
  assignedTo?: unknown;
}

// today:
type modifiedObject = Omit<TOrder, 'assignedTo'> & {
  assignedTo: string;
};

// would like:
type ModifyPropertyType<
  TObject extends Record<string, any>,
  TProperty extends keyof TObject,
  TNewType,
> = Omit<TObject, TProperty> & {
  [x in TProperty]: TNewType;
};



type modifiedObject2 = ModifyPropertyType<TOrder, 'assignedTo', string>;

// v2:
type ModifyPropertyType2<
  TObject extends Record<string, any>,
  TObjectPatch extends Record<string, any>
> = Omit<TObject, keyof TObjectPatch> & {
  [x in keyof TObjectPatch]: TObjectPatch[keyof TObjectPatch];
};

type modifiedObject3 = ModifyPropertyType2<TOrder, { assignedTo: string }>;
```

**Comment by devinrhode2** [comment]
I might prefer to write this code with `Merge`

**Comment by devinrhode2** [comment]
I've been using `Merge<obj, { prop: NewType }>`, maybe nicer than `ModifyPropertyType`

**Comment by fregante** [comment]
Added as `Merge`: https://github.com/sindresorhus/type-fest/blob/main/source/merge.d.ts
