### ISSUE TITLE
OverrideProperties marks all properties optional

### ISSUE THREAD

**Issue by crizo23** [sindresorhus/type-fest#704]
The resulting type has all properties optional. I don't think this is intended?

I used the example from the [docs](https://github.com/sindresorhus/type-fest/blob/main/source/override-properties.d.ts): 
````
type Foo = {
	a: string
	b: string
}
type Bar = OverrideProperties<Foo, {b: number}>
//=> {a: string, b: number}
````
I'm on typescript 5.2.2 and see `a` and `b` optional in `Bar`:
````
type Bar = {
    a?: string;
    b?: number;
}
````
![Screenshot 2023-10-11 at 9 35 59 PM](https://github.com/sindresorhus/type-fest/assets/607765/7feb02a0-049a-41dc-a7cf-ef237ac9a43b)

**Comment by sindresorhus** [comment]
// @jinta4020 @nidomiro

**Comment by crizo23** [comment]
Same issue with [Merge](https://github.com/sindresorhus/type-fest/blob/main/source/merge.d.ts)

**Comment by henriqueinonhe** [comment]
It's caused by the `strict` option in your `tsconfig.json` not being set to `true`.

**Comment by crizo23** [comment]
> It's caused by the `strict` option in your `tsconfig.json` not being set to `true`.

confirmed! Thanks for the update.

**Comment by henriqueinonhe** [comment]
It doesn't affect the types generated themselves, but rather how Typescript checks types.

The `strict` [option](https://www.typescriptlang.org/tsconfig#strict), when enabled, turns on several behaviors that make type checking "stricter".

In this case, it's probably caused especfically by the [`strictNullChecks`](https://www.typescriptlang.org/tsconfig#strictNullChecks) flag.

Right now I won't be able to pinpoint the exact reason why `strictNullChecks` = `false` causes the problem you encountered, but the thing is that when that flag is turned off, it basically "ignores" `null` and `undefined`, effectivelly changing how the type checking works.
