### ISSUE TITLE
Proposal: Implement autocompletion for `OverrideProperties`

### ISSUE THREAD

**Issue by henriqueinonhe** [sindresorhus/type-fest#711]
Currently, while `OverrideProperties` restricts the keys you can override to the keys that are present in the type you pass (`TOriginal`), it doesn't offer autocomplete:

![image](https://github.com/sindresorhus/type-fest/assets/20905415/c4a746aa-fa54-407f-af29-68b58c07cd7e)

![image](https://github.com/sindresorhus/type-fest/assets/20905415/9515e3df-118a-4890-9bc7-3bfa4ad58076)

But with a simple tweak we can enable autocompletion:

![image](https://github.com/sindresorhus/type-fest/assets/20905415/260de0dc-3f72-412a-b7b9-ee445f01e56f)

Here's a demo showcasing the implementation:

https://stackblitz.com/edit/typescript-zyn86c?file=index.ts

This implementation keeps keys "strict", in the sense that you cannot override/add keys that are not present in the original type.

If maintainers agree that this is a good improvement, I can create a PR.

**Comment by sindresorhus** [comment]
PR welcome
