### ISSUE TITLE
Generate dot.notation access list for an object

### ISSUE THREAD

**Issue by fregante** [sindresorhus/type-fest#715]
I don't know how common or how useful this would be, but it might be a companion to the Get/Set types.

```ts
const event = {
	user: {
		id: 123,
		name: 'giorgio'
	},
	action: 'delete'
} as const;

const id = get('user.id', event);
   // ^? number, typed via Get

get('user.state', event);
   // ^? Error, typed via advanced Get
```

This would also enable/export a "dot-notation keyof":
```ts
type DeepKeys = DeepKeyOf<typeof event>;
   // ^? ['user', 'user.id', 'user.name', 'action']
```

Real-life example:

https://github.com/pixiebrix/pixiebrix-app/blob/d30a53fe6f9e8baecc0b86356b4eab844e16d296/pixiebrix-app/src/pages/queryRegistry/exportQueryResult.ts#L8-L14

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/sindresorhus/type-fest/issues/213

**Comment by fregante** [comment]
Oh good. I couldn't find it

**Comment by sindresorhus** [comment]
Maybe, but it has more info.
