### ISSUE TITLE
Proposal: `SetFieldType`

### ISSUE THREAD

**Issue by lucasteles** [sindresorhus/type-fest#718]
A simple shallow field type replace utility type

definition:
```ts
import type {Except} from './except';
import type {Simplify} from './simplify';

export type SetFieldType<BaseType, Keys extends keyof BaseType, NewType> =
  Simplify<
  Except<BaseType, Keys> &
  Record<Keys, NewType>
  >;
```

use case:
```ts
type MyModel = { id: number; createdAt: Date; updatedAt: Date; enabled: boolean }
type MyModelApi = SetFieldType<MyModel, 'createdAt' | 'updatedAt', string>
// MyModelApi == { id: number; createdAt: string; updatedAt: string; enabled: boolean }

const response = fetch<MyModelApi>("url")
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/718">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/718/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/718/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
I would name it `SetFieldType`.

**Comment by sindresorhus** [comment]
Related type: https://github.com/sindresorhus/type-fest/issues/675

**Comment by lucasteles** [comment]
@sindresorhus looks great, i will update the issue

**Comment by Emiyaaaaa** [comment]
This type seem like `type Overwrite<T, K> = Omit<T, keyof K> & K`
Maybe `Overwrite<MyModel, {createdAt: string, updatedAt: string}>` is more universal?

@sindresorhus Thoughts?

**Comment by sindresorhus** [comment]
> Maybe Overwrite<MyModel, {createdAt: string, updatedAt: string}> is more universal?

Yeah, I like it better. More flexible as you can replace multiple properties with different types at once.

**Comment by Emiyaaaaa** [comment]
> > Maybe Overwrite<MyModel, {createdAt: string, updatedAt: string}> is more universal?
> 
> Yeah, I like it better. More flexible as you can replace multiple properties with different types at once.

I found `Merge` is same to `Overwrite` in this case. could just use `Merge` before have the case that `Overwrite` is better than `Merge`

**Comment by lucasteles** [comment]
I believe overwrite/merge is not quite what I am aiming for here

I have used this approach before and I figured myself having to repeat the structure and the same type multiple times which made me create this helper, to easily change multiple fields to one single type

**Comment by sindresorhus** [comment]
Thinking more about this, I think we can have both types.
