### ISSUE TITLE
`Writable` is not suppert array

### ISSUE THREAD

**Issue by Emiyaaaaa** [sindresorhus/type-fest#725]
`Writable` Sounds like can make `readonly [a, b, c]` to be writable as `[a, b, c]` but it can not actually, although the documentation indicates that it is only used to handle object.

And the behavior of `Writable` is more like 'WritableObject'

Can we make `Writable` support array? @sindresorhus 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/725">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/725/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/725/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
Does `Readonly` support array?

**Comment by Emiyaaaaa** [comment]
> Does `Readonly` support array?

yes

![image](https://github.com/sindresorhus/type-fest/assets/37606228/3871e367-4e6c-40f6-8244-ac498b498f06)
![image](https://github.com/sindresorhus/type-fest/assets/37606228/1c25f1c5-90d0-4e9b-86a4-713a89cf2188)

**Comment by sindresorhus** [comment]
Then we should support it here too 👍

**Comment by Emiyaaaaa** [comment]
> > Then we should support it here too 👍
> 
> I'd like to fix it. Then should we transform `ReadonlyMap` to `Map` and `ReadonlySet` to `Set`?

PS: `Readonly` can not do this
