### ISSUE TITLE
Missing ArrayIndices and ArrayValues from 4.5.0

### ISSUE THREAD

**Issue by mp3por** [sindresorhus/type-fest#729]
Hello,

After installing the latest version 4.5.0 I am missing two types - ArrayIndicies and ArrayValues
Please check image for reference
<img width="431" alt="image" src="https://github.com/sindresorhus/type-fest/assets/5836859/bb8ee266-a1e4-4bf7-9ca3-402fe5027389">

**Comment by Emiyaaaaa** [comment]
Just waiting for version 4.6.0 
![image](https://github.com/sindresorhus/type-fest/assets/37606228/bc01335f-9ff4-4951-99c0-61a7cf574390)

**Comment by sindresorhus** [comment]
The readme (like most repos on GitHub) reflect the main branch and not the latest release. You can either visit a tag or the npm page for docs on the latest version.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/type-fest/releases/tag/v4.6.0

**Comment by mp3por** [comment]
Thank you ;)
