### ISSUE TITLE
Suggestion: add `ArraySlice` and `StringSlice`

### ISSUE THREAD

**Issue by Max10240** [sindresorhus/type-fest#734]
for example:
```ts
type Tuple = [0, 1, 2, 3];

type Segment0 = ArraySlice<Tuple, 0, 2>; // [0, 1]
type Segment1 = ArraySlice<Tuple, 1, 3>; // [1, 2]

type Str = 'abcde';
type StrSegment0 = StrSlice<Str, 0, 2>; // 'ab'
```

If the idea is feasible, I can propose a PR to complete it

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/734">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/734/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/734/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
Sounds like a useful type to me 👍

**Comment by Max10240** [comment]
I'm finishing it, but it may take some time

**Comment by sindresorhus** [comment]
Added in https://github.com/sindresorhus/type-fest/pull/748
