### ISSUE TITLE
Proposal: `UnknownArray`

### ISSUE THREAD

**Issue by Emiyaaaaa** [sindresorhus/type-fest#739]
Hi @sindresorhus 

like `UnknownRecord`. All array type（e.x. `['foo']`, `readonly string[]`, `Array<number>`）can assign to `UnknownArray`

It's also a helpful type for other type.

```typescript
type UnknownArray = readonly unknown[]
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/739">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/739/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/739/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
Go for it.
