### ISSUE TITLE
Comparison to `ts-essentials`

### ISSUE THREAD

**Issue by papb** [sindresorhus/type-fest#74]
Hello! Thanks for this great package. I have been using it for a while now. However, recently I stumbled on another similar package: https://github.com/krzkaczor/ts-essentials

Do you have any thoughts on the differences between it and type-fest?

Thank you very much.

**Comment by sindresorhus** [comment]
I remember looking at it a few months ago. In contrast to type-fest, it also includes TypeScript code, not just types. It's good too. It's just a different take on the idea of a type utility library. It does have many times I would never use, but maybe there are some ideas we can borrow there.

**Comment by papb** [comment]
Thank you very much!
