### ISSUE TITLE
Proposal: get the public part of union.

### ISSUE THREAD

**Issue by Emiyaaaaa** [sindresorhus/type-fest#750]
Hi everyone~
I'm having some problems with `OmitDeep` implementation, I want a type that can get the public part object type from union.

example:
```ts
type Union = { a: string, b: {b1: number, foo: string}, c: boolean } |
             { a: string, b: {b1: number, bar: number}, d: boolean }

type Result = PublicOfUnion<Union> // or other name
//=> type Result = { a: string, b: { b1: number } }
```

If the type is feasible, I'll try to implementation it but haven't idea now.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/750">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/750/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/750/pledge.svg">
</picture>
</a>

**Comment by Emiyaaaaa** [comment]
Seem was resolved
```ts
type PublicOfUnion<Union> = keyof Union extends infer Keys
	? {
		[Key in Keys]: Union[Key] extends BuiltIns ? Union[Key] : PublicOfUnion<Union[Key]>
	} : never;

type Union = {a: string; b: {foo: string}; c: boolean} | {a: string; b: {bar: number}; d: boolean};

type Result = PublicOfUnion<Union>;
//=> type Result = { a: string, b: {} }
```

Could I create a PR? and want a better name~
@sindresorhus

**Comment by sindresorhus** [comment]
`Public` sounds like it's about access levels.

How about `SharedUnionFields` or `CommonUnionFields`?

**Comment by Emiyaaaaa** [comment]
thanks! I perfer `SharedUnionFields`

**Comment by sindresorhus** [comment]
> SharedUnionFields

Lets go with that then.
