### ISSUE TITLE
Request: `Slice` or `Rest`

### ISSUE THREAD

**Issue by matthias-ccri** [sindresorhus/type-fest#751]
Use case: writing a facade for a function, that supplies the first function parameter:

```ts
import { getVehicleFeatures } from './vehicle-utils';

declare const vehicle;

function getFeatures (...args: Slice<1, Parameters<typeof getVehicleFeatures>) {
    return getVehicleFeatures(vehicle, ...args);
}
```

So the `getFeatures` function has all of the parameters of `getVehicleFeatures` except for the first, which is the vehicle itself. This is a form of currying. It allows `getFeatures` to reference the parameter array type of `getVehicleFeatures` and get a type with all the params except the first.

Alternate suggestions welcome :slightly_smiling_face: 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/751">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/751/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/751/pledge.svg">
</picture>
</a>

**Comment by Emiyaaaaa** [comment]
Related #734

**Comment by Emiyaaaaa** [comment]
#734 completed
