### ISSUE TITLE
How can I use the classic Omit functionality applied to an array type instead of a type?

### ISSUE THREAD

**Issue by silversonicaxel** [sindresorhus/type-fest#754]
How can I use the classic Omit functionality applied to an array type instead of a type?

For example, I've the following type

```
type Car = {
  a: number,
  b: string,
  c: Record<string, unknown> | null
}

type Cars = Car[]
```

I would like to create similar types without `c: Record<string, unknown> | null`.

For example I could declare.

```
type Voiture = Omit<Car, 'c'>

type Voitures = Omit<Cars, 'c'>  // obviously not working
```

For code constraints, I ca't use `Omit<Car, 'c'>[]`.

Is there a solution for this?

Thanks

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/754">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/754/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/754/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
Apply the `Omit` before making it an array, or wait for https://github.com/sindresorhus/type-fest/issues/576

**Comment by silversonicaxel** [comment]
Oh, I found out 
`type Voitures = Omit<Cars[number], 'c'>[]`

Thanks anyway
