### ISSUE TITLE
PartialOnUndefinedDeep removes non-optional properties when the input type contains an index signature

### ISSUE THREAD

**Issue by russelldavis** [sindresorhus/type-fest#756]
Example:
```ts
import {PartialOnUndefinedDeep} from "type-fest"

type WithoutSignature = {
  foo: number
  bar: number | undefined
}
// Output1 contains the `foo` property
type Output1 = PartialOnUndefinedDeep<WithoutSignature>

type WithSignature = {
  foo: number
  bar: number | undefined
  [k: string]: unknown
}
// Output2 does not contain the `foo` property
type Output2 = PartialOnUndefinedDeep<WithSignature>
```
[TS Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwAoENbBQGwPIDsCquAJgKYBmwuJRAIiSWAL5xlQQhwBEMAnmCQFoyJAM4xOAKAm9+cAOrAYACwgBXGAGVgAc1woYqqCTgBeRBLgsIEAFxxcqkACMSUC3Cdo7D567gAfOFVickpqCUYJAHoouGx1MHUARjgAYwhcGBRKEThlYwADMmsCuDA2flgeaT5jeJhEmBSzVHQsPEJSCipaejAAHgVlNU0dPQMjAD5o2MsAPQB+KRljIaUtXX1DYzMEd2Lbe0cXN0tPKG9jv0DgrrCidwBtAGs7MShKbQBdO2Dn3AgAHdcBEZnEEuoAExwIgQUT2CDwdKZbK4PJKQoHUrlCCVXg1WT1RrQlpoGAYHAEELdah0BiDRTrMZbKZg+ZLIA)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/756">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/756/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/756/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
// @clemclx
