### ISSUE TITLE
[4.8.0] fails when there are no DOM types

### ISSUE THREAD

**Issue by AviVahl** [sindresorhus/type-fest#757]
got this failure with the new version:
```
node_modules/type-fest/source/internal.d.ts:72:52 - error TS2304: Cannot find name 'Element'.

72 export type BuiltIns = Primitive | Date | RegExp | Element;
```

my tsconfig says: `"lib": ["es2021"],` without DOM types.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/757">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/757/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/757/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
Fixed: https://github.com/sindresorhus/type-fest/releases/tag/v4.8.1
