### ISSUE TITLE
[4.8.0] type error on jsonify

### ISSUE THREAD

**Issue by AviVahl** [sindresorhus/type-fest#758]
with the new version, I get:
```
ode_modules/type-fest/source/jsonify.d.ts:122:28 - error TS2344: Type 'WritableDeep<T>' does not satisfy the constraint 'unknown[]'.
  Type 'T | (T extends (...arguments_: any[]) => unknown ? {} extends WritableObjectDeep<((...arguments_: any[]) => unknown) & T> ? ((...arguments_: any[]) => unknown) & T : HasMultipleCallSignatures<((...arguments_: any[]) => unknown) & T> extends true ? ((...arguments_: any[]) => unknown) & T : ((...arguments_: Parameters...' is not assignable to type 'unknown[]'.
    Type 'readonly unknown[] & T' is not assignable to type 'unknown[]'.
      The type 'readonly unknown[]' is 'readonly' and cannot be assigned to the mutable type 'unknown[]'.

122              ? JsonifyList<WritableDeep<T>>
                               ~~~~~~~~~~~~~~~
```

changing:
`type JsonifyList<T extends unknown[]>`
to:
`type JsonifyList<T extends readonly unknown[]>`

fixes the issue.

saw this in https://github.com/wixplosives/file-services when I've upgraded to `type-fest@4.8.0`

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/758">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/758/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/758/pledge.svg">
</picture>
</a>

**Comment by AviVahl** [comment]
can also be seen in a dependabot PR: https://github.com/wixplosives/resolve-directory-context/pull/288

**Comment by sindresorhus** [comment]
Fixed: https://github.com/sindresorhus/type-fest/releases/tag/v4.8.1

**Comment by sindresorhus** [comment]
@Emiyaaaaa Would be great if you could add a test for this.

**Comment by Emiyaaaaa** [comment]
> @Emiyaaaaa Would be great if you could add a test for this.

ok, but look like typescript think `WritableDeep<T>` can return a `readonly unknown[]`?

**Comment by sindresorhus** [comment]
@Emiyaaaaa Yeah, it probably needs a better fix too. It should not return `readonly unknown[]`. I just pushed out a quick fix to fix the breakage.
