### ISSUE TITLE
"Stricter" intersection type?

### ISSUE THREAD

**Issue by kytta** [sindresorhus/type-fest#760]
I don't see it having been requested, and maybe there's a reason for this. My idea for a type is a stricter intersection type: When applied to two interfaces, it will produce a new one containing only the keys present in _both_ interfaces.

Example (modelled after a real-world problem I have):

```ts
interface ResponseOne {
  id: string;
  success: boolean;
  error?: Record<string, string | number>;

  foo: string;
  bar: number;
}

interface ResponseTwo {
  id: string;
  success: boolean;
  error?: Record<string, string | number>;

  baz: string;
  qux: string[];
}

type AnyResponse = MyIntersection<ResponseOne, ResponseTwo>
//=> { id: string, success: boolean, error?: Record<string, string | number> | undefined }
```

In an ideal case, there should have been a base interface like `BaseResponse` with the common keys. But in my case, there isn't one, and I can't control the types `ResponseOne` and `ResponseTwo`. I would love to use this "base" type to create arrays and functions working with the essential properties of a `Response` without worrying about them being incompatible.

I am a TypeScript rookie, so maybe there is an easier / more correct way to do this 😅 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/760">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/760/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/760/pledge.svg">
</picture>
</a>

**Comment by Emiyaaaaa** [comment]
Similar to #750

**Comment by kytta** [comment]
> Similar to #750 

Totally, I overlooked it!
