### ISSUE TITLE
`Paths` should not recurse into `Map`'s prototype properties.

### ISSUE THREAD

**Issue by Emiyaaaaa** [sindresorhus/type-fest#771]
![image](https://github.com/sindresorhus/type-fest/assets/37606228/167681e3-6521-4273-87e0-a5b7d73b11c4)
In this case:
```ts
declare const map: Paths<{foo: Map<'a', {bar: string}>}>;
```
Should we recurse into `Map`? 
```ts
//=> 'foo' | 'foo.a' | 'foo.a.bar'
```
Or just stop there?
```ts
//=> 'foo'
```

I perfer recurse into Map

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/771">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/771/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/771/pledge.svg">
</picture>
</a>

**Comment by Emiyaaaaa** [comment]
@sindresorhus

**Comment by sindresorhus** [comment]
I think it should be opt-in. `Map` would require using a different way to access the values using the path components.

`Set` does not make sense as it's not indexed.

**Comment by Emiyaaaaa** [comment]
> `Map` would require using a different way to access the values using the path components.

I agree opt-in, but it doesn't seem possible to use string to represent all type of the keys in a map, like object key, the most we can do is to access only the string/number keys in the map.

**Comment by sindresorhus** [comment]
That's fine.

**Comment by Emiyaaaaa** [comment]
I thought about it more. If the reason for using opt-in is that access to a map is different from access to an object, but if the user chooses `recurseInMap`, the end result is still indistinguishable from a map or an object. so maybe opt-in isn't necessary?

**Comment by sindresorhus** [comment]
The main reason for making it opt-in, is that most times when you need to get the paths, you don't support `Map`. For example, with https://github.com/sindresorhus/dot-prop, I don't support `Map`, so I wouldn't want the user to get autocomplete for `Map` keys.

**Comment by Emiyaaaaa** [comment]
> The main reason for making it opt-in, is that most times when you need to get the paths, you don't support `Map`. For example, with https://github.com/sindresorhus/dot-prop, I don't support `Map`, so I wouldn't want the user to get autocomplete for `Map` keys.

got it. maybe we shoudn't support recurse into map?

**Comment by Emiyaaaaa** [comment]
> Yeah, maybe we should wait until someone requests it. I personally don't have any need for it.

ok, but look at image in the description, there is still a bug that `Paths` should not recurse into `Map`'s prototype properties.
