### ISSUE TITLE
`Addition` And `Subtraction` Type Proposal

### ISSUE THREAD

**Issue by Dlurak** [sindresorhus/type-fest#774]
Typescript doesn't support arithmetic operators on a type level.
I suggest introducing new types for Addition and Subtraction

I've semi successfully implemented these types already as they can be seen in [this Gist](https://gist.github.com/Dlurak/82fbf7de4c4fc2f0564d03970d3a386e).

Especially a type for addition can be very useful to create recursive types.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/774">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/774/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/774/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
What's the real-world use-case for this?

**Comment by Dlurak** [comment]
And also for recursive types it can be quite useful to have a counter. Here is another code example in which i used the `Add` type to create a type that repeats a string n times.

```Typescript
type AppendString<T extends string, S extends string> = `${T}${S}`;

type RepeatString<
  S extends string,
  N extends number,
  Counter extends number = 0,
  TotalString extends string = "",
> = Counter extends N
  ? TotalString
  : RepeatString<S, N, Add<Counter, 1>, AppendString<TotalString, S>>;
```

And here is an example of using the `Add` type to get the length of a string:

```Typescript
type LengthOfString<
  T extends string,
  N extends number = 0,
> = T extends `${infer R}${infer L}` ? LengthOfString<L, Add<N, 1>> : N;
```

**Comment by sindresorhus** [comment]
These were added in https://github.com/sindresorhus/type-fest/releases/tag/v4.12.0

`Add` was named `Sum`.
