### ISSUE TITLE
`MergeDeep` removes optionals from `any` and `never` fields

### ISSUE THREAD

**Issue by Xananax** [sindresorhus/type-fest#775]
Example:

```ts
interface A{
  propNever?:never
  propAny?:any
  propString?:string
  propNull?:null
  propUndefined?:undefined
  propNumber?:number
  propLiteralUnion?:'A'|'B'
}

type B = MergeDeep<A, {additionalAny?:any, additionalString?:string}>
```
### Expectation:

That `B` keeps all the undefined fields as they are and adds two more.

### Actual:

`B` sets:
- all `undefined | any` to `any`
- all `undefined | never` to `undefined`

It doesn't matter if the types come from the left or the right interface.

![image](https://github.com/sindresorhus/type-fest/assets/836082/24a4b95c-fa8b-499a-9c8b-73971fde3ae7)

The merging seems to be conform to expectations for other types (the ones I tried at least).

### My use case:

I am using Supabase and their excellent typescript generation.

Supbase sets the `id` field of operations `update` and `insert` as `type?:never`, to make sure an `id` is never passed to an SQL operation that doesn't need it. So a table definition looks like so:

```ts
interface Tables{
  users:{
    Row:{
      id: string,
      email: string 
    },
    Insert:{
      id?: never,
      email: string
    }
    Update:{
      id?: never,
      email?: string
    }
  }
}
```

It's a neat and elegant system that makes all operations type-sound(-ish).

I use MergeDeep to refine the Supabase type (specifically, strictly typing the json fields). But because of the above bug, this won't work:
```ts
supabase.from("users").update({ email }).eq("id", id)
```
The linter won't let it pass,  it complains that `id` is required.

I am now forced to use
```ts
supabase.from("users").update({ email, id: undefined }).eq("id", id)
```
Or to leave a `//@ts-ignore`.

Both are suitable workaround at the moment, but I would much rather no do that.

Thanks for Typefest, it's one of my favorite libraries! Amazing work.

### Prior literature

- https://github.com/sindresorhus/type-fest/issues/506
- https://github.com/sindresorhus/type-fest/issues/579

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/775">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/775/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/775/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
Thank you @Emiyaaaaa for contributing to close this issue! ⭐

The rewards from this issue, totalling $30, has been shared with you.

**What now?**

1. Create a [Polar](https://polar.sh) account
2. See incoming rewards & setup Stripe to receive them
3. Get payouts as backers finalize their payments

_If you already have a Polar account setup, you don't need to do anything._

**Comment by Xananax** [comment]
Oh damn, that was fast, thanks!

(I don't know if the pledge had anything to do with the speed of resolution, but at any rate: anyone reading this, please support the open source projects you use if you are able!)
