### ISSUE TITLE
MergeDeep is never when compiled to .d.ts

### ISSUE THREAD

**Issue by dreinon** [sindresorhus/type-fest#780]
I'm trying to use MergeDeep to redefine certain types from the type generation Supabase CLI does, like it says in the [guide](https://supabase.com/docs/guides/api/rest/generating-types#using-typescript-type-definitions).

When I write the code, it works well, but when it is compiled to d.ts, it is never:
![image](https://github.com/sindresorhus/type-fest/assets/67071425/7837883e-66ef-488b-9b77-6fda0461b590)
![image](https://github.com/sindresorhus/type-fest/assets/67071425/db8fb9bd-49ec-480c-a592-66181abdda7b)

Any ideas? Thanks!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/780">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/780/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/780/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
First, make sure you are on the latest `type-fest` version and you're using strict TS config.

We cannot really do much based on a screenshot. If you want to see this fixed sooner, I recommend submitting a minimal failing test: https://github.com/sindresorhus/type-fest/blob/main/test-d/merge-deep.ts

**Comment by dreinon** [comment]
using strict TS config solves the problem, may I know why? Thanks!

**Comment by sindresorhus** [comment]
I haven't look into it, but certain types are more limited when strict mode is off.
