### ISSUE TITLE
Canary: `MergeDeep` failures in `typescript@next` not detected by canary tests

### ISSUE THREAD

**Issue by voxpelli** [sindresorhus/type-fest#784]
I'm seeing a lot of these style of errors in the canary tests in my own modules:

```
Error: ../node_modules/read-pkg/node_modules/type-fest/source/merge-deep.d.ts(144,5): error TS2321: Excessive stack depth comparing types 'PickRestType<ArrayTail<ArrayTail<Destination>>>[number]' and 'UnknownArrayOrTuple'.
Error: ../node_modules/read-pkg/node_modules/type-fest/source/merge-deep.d.ts(144,5): error TS2321: Excessive stack depth comparing types 'PickRestType<ArrayTail<ArrayTail<Destination>>>[number]' and 'UnknownRecord'.
Error: ../node_modules/read-pkg/node_modules/type-fest/source/merge-deep.d.ts(144,5): error TS2321: Excessive stack depth comparing types 'PickRestType<ArrayTail<ArrayTail<Source>>>[number]' and 'UnknownArrayOrTuple'.
Error: ../node_modules/read-pkg/node_modules/type-fest/source/merge-deep.d.ts(170,5): error TS2321: Excessive stack depth comparing types 'PickRestType<ArrayTail<ArrayTail<Destination>>>[number]' and 'UnknownArrayOrTuple'.
Error: ../node_modules/read-pkg/node_modules/type-fest/source/merge-deep.d.ts(170,5): error TS2321: Excessive stack depth comparing types 'PickRestType<ArrayTail<ArrayTail<Destination>>>[number]' and 'UnknownRecord'.
Error: ../node_modules/read-pkg/node_modules/type-fest/source/merge-deep.d.ts(170,5): error TS2321: Excessive stack depth comparing types 'PickRestType<ArrayTail<ArrayTail<Source>>>[number]' and 'UnknownArrayOrTuple'.
Error: ../node_modules/read-pkg/node_modules/type-fest/source/merge-deep.d.ts(196,5): error TS2321: Excessive stack depth comparing types 'PickRestType<ArrayTail<ArrayTail<Destination>>>[number]' and 'UnknownArrayOrTuple'.
Error: ../node_modules/read-pkg/node_modules/type-fest/source/merge-deep.d.ts(196,5): error TS2321: Excessive stack depth comparing types 'PickRestType<ArrayTail<ArrayTail<Destination>>>[number]' and 'UnknownRecord'.
Error: ../node_modules/read-pkg/node_modules/type-fest/source/merge-deep.d.ts(196,5): error TS2321: Excessive stack depth comparing types 'PickRestType<ArrayTail<ArrayTail<Source>>>[number]' and 'UnknownArrayOrTuple'.
```

I didn't receive them in `typescript@5.4.0-dev.20231119` then started receiving them in `typescript@5.4.0-dev.20231121`.

To avoid a regression once `typescript@5.4.0` gets launched, we should track down the cause of this and file an issue with `typescript` if needed.

We should also track down why the canary tests in `type-fest` itself isn't catching it.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/784">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/784/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/784/pledge.svg">
</picture>
</a>

**Comment by voxpelli** [comment]
The regression should be caused by any of the following commits: https://github.com/microsoft/TypeScript/compare/b4aefd2758b2d74b1d6747ffa4369224537a6212...13c9b16b2a0d2b9fe6bb78ba567c8c6c5161c510

**Comment by voxpelli** [comment]
Suggested to add `type-fest` into typescript's own canary tests: https://github.com/microsoft/typescript-error-deltas/pull/129

**Comment by jakebailey** [comment]
FWIW you can pretty easily bisect this using every-ts: https://www.npmjs.com/package/every-ts

```console
$ every-ts fetch
$ every-ts bisect bad 5.4.0-dev.20231121
$ every-ts bisect good 5.4.0-dev.20231119
$ every-ts tsc
$ every-ts bisect bad
$ every-ts tsc
$ every-ts bisect good
...
```

**Comment by voxpelli** [comment]
Finally got time to look into this and `every-ts` is really really great @jakebailey!

Came to the conclusion that its https://github.com/microsoft/TypeScript/pull/56004 that caused these errors
