### ISSUE TITLE
`PackageJson`: Why properties like `name` and `version` are not required?

### ISSUE THREAD

**Issue by JounQin** [sindresorhus/type-fest#790]
## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/790">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/790/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/790/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
Because they are optional with npm too. Mostly useful for private packages.
