### ISSUE TITLE
SetRequiredDeep - is it possible?

### ISSUE THREAD

**Issue by Hatgor** [sindresorhus/type-fest#796]
Hello there! 

Could anyone please advise if I can combine existing methods to achieve the following: 

`type Example = {
  a: string;
  b?: number;
  c: {
    ca: number;
    cb?: string;
  };
};`

`type ExampleWithRequired = SetRequiredDeep<Example, 'b' | 'c.cb'>;`

I've tried to slightly modify SetRequired on my own, but it didn't work as expected: 

<img width="691" alt="image" src="https://github.com/sindresorhus/type-fest/assets/30573650/7cca4caa-bdef-4701-a859-a2b6119947a8">
  
<img width="452" alt="image" src="https://github.com/sindresorhus/type-fest/assets/30573650/3041e241-52d9-42c6-a724-ee6153db2f48">

Is it possible at all? 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/796">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/796/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/796/pledge.svg">
</picture>
</a>

**Comment by Emiyaaaaa** [comment]
I think this can be a good feature.
