### ISSUE TITLE
Feature Request (or bug report?) - Get the last key of a record

### ISSUE THREAD

**Issue by matthew-dean** [sindresorhus/type-fest#797]
I've been trying to fiddle around with existing types, but I can't seem to figure this out.

Say I have an object like:
```ts
const object = {
  foo: 1,
  bar: 2
}
```
I have another object like:
```ts
const object2 = {
  foo(...args: any[]) {
    return SomeType
  },
  bar(...args: any[]) {
    return DifferentType
  }
} satisfies Record<keyof typeof object, any>
```

What I want to do is, if `object` is passed into a (not shown) function, get the return type of object2['bar']. That is, an object with a structure of:
```
{
  foo: 1,
  bar: 2
}
```
... would end up with a result of `DifferentType`, because `bar` is the last key provided in the object.

An object with:
```ts
{
   bar: 1,
   foo: 1
}
```
... would end up with a result of `SomeType` (because `foo` is the last key in the object)

The problem I'm having is that the `Entries` type doesn't seem to actually correctly type entries when the type passed in is a const, such that `Pick<typeof object2, LastArrayElement<Entries<typeof object>>[0]>` throws a `does not satisfy the constraint` error.

If I'm doing this wrong, alternatively it would be great to have something like `LastEntryOf<object>` that preserves a strongly-typed readonly key, value pair, such that I can get the proper type-defined function based on a (dynamic) key lookup.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/797">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/797/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/797/pledge.svg">
</picture>
</a>

**Comment by fregante** [comment]
I think it's best to ask StackOverflow first, then maybe request the resulting type/solution to be added here.
