### ISSUE TITLE
[4.10.0][Regression] failure when type checking with exactOptionalPropertyTypes

### ISSUE THREAD

**Issue by AviVahl** [sindresorhus/type-fest#801]
```
mkdir show-issue
cd show-issue
npm init -y
npm i typescript type-fest -D
npx tsc --init --skipLibCheck false --target es2022 --exactOptionalPropertyTypes
echo "import 'type-fest';" > test.ts
npx tsc --noEmit
```

See the following error:
```
node_modules/type-fest/source/merge-deep.d.ts:292:50 - error TS2344: Type '{ [KeyType in keyof ({ [Key in keyof PickIndexSignature<Options> as Key extends never ? never : Key]: PickIndexSignature<Options>[Key]; } & PickIndexSignature<...> & { [Key in keyof OmitIndexSignature<...> as Key extends "spreadTopLevelArrays" ? never : Key]: OmitIndexSignature<...>[Key]; } & OmitIndexSignature<...>...' does not satisfy the constraint '{ arrayMergeMode?: ArrayMergeMode; recurseIntoArrays?: boolean; spreadTopLevelArrays?: boolean; }'.
  Types of property 'arrayMergeMode' are incompatible.
    Type 'Options["arrayMergeMode"]' is not assignable to type 'ArrayMergeMode'.
      Type 'ArrayMergeMode | undefined' is not assignable to type 'ArrayMergeMode'.
        Type 'undefined' is not assignable to type 'ArrayMergeMode'.

292     ? MergeDeepArrayOrTuple<Destination, Source, Merge<Options, {spreadTopLevelArrays: false}>>
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/type-fest/source/merge-deep.d.ts:292
```

Saw first in https://github.com/wixplosives/core3-playground/pull/175

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/801">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/801/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/801/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
// @Emiyaaaaa

**Comment by Emiyaaaaa** [comment]
> // @Emiyaaaaa

#802 I was tested that it's working after the revert, we can revert first.

**Comment by Emiyaaaaa** [comment]
I found some thing

![image](https://github.com/sindresorhus/type-fest/assets/37606228/21f9223f-d41c-45ca-887c-df930ea39fe0)

![image](https://github.com/sindresorhus/type-fest/assets/37606228/ac6e216e-faed-4732-a483-da9042819336)

seem like `Merge<T, T>` is `{a?: T['a']}` and certainty `T['a']` is `string | undefined`,
then `string | undefined` is not assignable to type 'string' which is `a` in `A`, so ts throw an error

So the basic problem is that `Merge<T, T>` is `{a?: T['a']}` when `T` is a generic type, this maybe is a feature or rules of typescript I don't know.

In `type-fest@4.9.0`, `Merge` used `EnforceOptional` to convert `undefined` to `?` and remove `undefined`, but in fact this is a wrong action and people report the issue. So I removed `EnforceOptional` in `4.10.0`.

If we need to fix tsc error when `exactOptionalPropertyTypes: true`, I think we can only resolve bug case-by-case like this 
![image](https://github.com/sindresorhus/type-fest/assets/37606228/ec017ac5-dbfb-49b5-a15d-6d47d4a1066e)

**Comment by sindresorhus** [comment]
> exactOptionalPropertyTypes is false in type-fest's tsconfig, should we also support exactOptionalPropertyTypes: true?

Yes, we should add it to our config.

**Comment by AviVahl** [comment]
Thanks! ❤️
