### ISSUE TITLE
OptionalExcept type

### ISSUE THREAD

**Issue by stabai** [sindresorhus/type-fest#811]
A common use case of making a `Partial` of an object, but leaving a few keys as is.

```typescript
export type OptionalExcept<Type, AsIsKeys extends keyof Type> = Pick<Type, AsIsKeys> & Partial<Omit<Type, AsIsKeys>>;
```

Example:
```typescript
interface User {
  username: string;
  isAdmin: boolean;
  dateCreated: Date;
}

function newUser(userOptions: OptionalExcept<User, 'username'>): User {
  return {
    // Default values for optionals (if specified in userOptions, will be overwritten)
    isAdmin: false,
    dateCreated: new Date(),

    // Specified values (including the username, which we kept as required)
    ...userOptions
  };
}
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/811">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/811/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/811/pledge.svg">
</picture>
</a>

**Comment by voxpelli** [comment]
I guess this can be achieved somewhat by doing `SomeOptional<User, Omit<keyof User, 'username'>>` – maybe that's enough?

**Comment by stabai** [comment]
Oh, yes, that would work, I hadn't thought of that formulation. I may be misunderstanding the suggested types, but I think it would be like this:

```typescript
SetOptional<User, Exclude<keyof User, 'username'>>
```
