### ISSUE TITLE
Require exactly one key of type `string`

### ISSUE THREAD

**Issue by jakeboone02** [sindresorhus/type-fest#813]
Is there was a way to type an object to require that it has exactly one key? The key itself can be any `string` (or `number` or `symbol` for that matter), but I'd like to ensure there are at least _and_ at most one non-prototype/inherited property.

The use case is for typing the JavaScript implementation of [JsonLogic](http://jsonlogic.com/) ([npm](https://www.npmjs.com/package/json-logic-js) / [DT types](https://www.npmjs.com/package/@types/json-logic-js)). In the runtime code, the "logic" object itself and each nested object must satisfy the condition `Object.keys(logic).length === 1` ([see code](https://github.com/jwadhams/json-logic-js/blob/2.0.2/logic.js#L180)).

I tried `RequireExactlyOne<Record<string, any>, string>`, but that seems to be effectively the same as `Record<string, any>`.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/813">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/813/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/813/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
Sounds useful. Not sure whether it's possible though.
