### ISSUE TITLE
`UnionToUnorderedTuple` type

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/type-fest#819]
I think it's worth adding this as long as we clearly document its downsides.

Initial attempt in https://github.com/sindresorhus/type-fest/pull/686

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/819">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/819/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/819/pledge.svg">
</picture>
</a>

**Comment by voxpelli** [comment]
We basically want to do what's described here, right? https://stackoverflow.com/a/55128956

Any other techniques?

**Comment by voxpelli** [comment]
Basically:

1. Convert union values to return values of functions
2. `UnionToIntersection` to make it an intersection
3. Intersection will be treated as a function overload from which the base return value (the last one in the original union) can be easily extracted
4. Add that extracted last value to the the tuple result we want
5. Rinse and repeat everything again with the remaining values that has not yet been extracted, adding one more item to the tuple for every iteration
