### ISSUE TITLE
`ArraySlice` should support spread array

### ISSUE THREAD

**Issue by Emiyaaaaa** [sindresorhus/type-fest#828]
v4.12.0
```ts
const a: ArraySlice<[1, 2, 3, ...string[]], 1>
// => []
```

expect:
```ts
const a: ArraySlice<[1, 2, 3, ...string[]], 1>
// => [2, 3, ...string[]]
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/828">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/828/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/828/pledge.svg">
</picture>
</a>

**Comment by Emiyaaaaa** [comment]
// @Max10240 Would you like to fix it? No worries if not.

**Comment by Max10240** [comment]
@Emiyaaaaa Sure, let me test the feasibility!

**Comment by Emiyaaaaa** [comment]
> feasibility!

Maybe this might help you

https://github.com/sindresorhus/type-fest/blob/main/test-d/array-splice.ts
https://github.com/sindresorhus/type-fest/blob/main/source/array-splice.d.ts#L87
