### ISSUE TITLE
`ReadonlyDeep` / `WritableDeep` not modifying arrays as of TS 5.3.3

### ISSUE THREAD

**Issue by trevorade** [sindresorhus/type-fest#833]
See a repro of the issue for `ReadonlyDeep` in this [TS Playground](https://www.typescriptlang.org/play?ts=5.3.3#code/KYDwDg9gTgLgBDAnmYcAKUCWBbTNMBuqAvAFBxwA+cAdgK4A2D5VcdNAJsAGaY3AcW1AM4wsNAOZDadbACNgUaXIgQGwAIY1pwxPLXLMEvjADcpUqEiwEyVACE6mBjACSNYXGLosufEVYCCEwOVgARDRhUagAlYAkAUXBzS3BoeCQUOAAJDWEAWUZ8MHUAYQ0mAGUjGki6KGBhAB4AFThQKM5PAAoAOn6NKAlZYBoYYQB9AC44LUQAbQBdAEovAD42GgBrGggAdxoNsgo2jtGOTwBvPoGhkbHJmb5uRTgAQWWZ9h39mlM4G69QbDbCjcbTWY0BYrL7bXYHAC+LAoAH5Nj8Dkt2iBOhd3siKHA0dwKsJgASKDMxHRyYS4DMSQwySkrOlbFk4hoOBAaAxEGFgMAwK0jnBTjjzp5HM43B4WGiWiwZuLcZ5+HsAf0gUNhDM5ktVsQNt94do6QqCcrsarNbcQWDHpDoYbjXDfhSiXBLgjrZK4JzubzEAB5OQAK2AAGMYAKhSKPaixQn6Tk8oUXJgSsBylUanUGs0Whszl0EFAacnE4q6TWU91AcD7uCZmhBhpQVEoIW1i7-cAYPUaC07CLVgAyPtcnl80MR6Ox4VFj1Wkt4gPTxBNddB-IaYXPV4AaWAiGHKAANHAD1A4AA1Co0s-ANZrZNo7d83dgBdNY+nuyXveDCPnYr61pSYq+qWH6bjBlT9k015wK4UTYE+L6Vp6cH9j+KHAGhoGYTMmEqn6DRTkGcBYtQ5GBnyVFavwRBQEsiyYYmtEblRbHgTWK4SqWnGUfMSEAKqXlqSG3jxvE1miQn0fMME-qJawSf0ymCsKt5rDJsmEvxNoKYgDH9GJl5SXp+mEvJmh0SZ8xappcaqZeznabp7F8ZBq6eDBbxQFAGibkheEESgYHWbW752RuAVBbBsVBrhqHoZFUV0oZfoQOGUYwF5vExRRM65fOWnxhl4GwhifwWJkqAwV+P5-k+gEPsA6FeF6PoTjBW5JZ+e79cV-LlS1oFuQNo1xkBIERS+KT1ZO9nwTG5VhZ13jenAvVTcNK0Ie5TQbaBC11XYy0brOeU-td0ZPlBeI5XOMCipcLDGVR41ZHwcBbCeEDcHAd0wE+iwzEdINPvM33AIsr4IikFjnVkABy7aNGAGiRiQXosN03CqDM9DyIonxwKI4gSOYFByBoABeMwqGomg0Es5iIxYkY8qIcAcJEGhde9FC1KCwhYzjMzbXk6KmrMnjo2LEvAOepCc6Q3MePAxkRDAGgQ1NP71YDfMC6K-N6+YOsC70ouY9jwC9HT9PmAA9K7lXgQAeiipDu8hNBipUcAAKy9AATBHMzdGAUAQCgsCIKszszJ9zPqFoSx+x77hB6HvQAMyF9Hsfx4oSDJwzTOqBnbNsUAA) (change the version to 5.2.2 to see the older correct behavior)

This is verified in the test here (though failing to fail as it should): https://github.com/sindresorhus/type-fest/blob/67f90a31a592352cc92002fe1e96e3a6d52ed276/test-d/readonly-deep.ts#L105

`WritableDeep` exhibits the same issue.

I suspect that the typing system is behaving differently in `tsd` than the raw `tsc` leading to this issue not being detected. Not sure why...

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/833">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/833/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/833/pledge.svg">
</picture>
</a>

**Comment by gloomweaver** [comment]
The issue here is HasMultipleCallSignatures
In 5.2.2 it returned false for Namespace, in current it returns true
You can actually break it 5.2.2 if you provide additional signature in the type

Tried this
`
HasMultipleCallSignatures<T> extends true
          ? T & ReadonlyObjectDeep<T>
          : ((...arguments_: Parameters<T>) => ReturnType<T>) & ReadonlyObjectDeep<T>
`
But then type of baz is boolean[] & readonly boolean[]
Didn't find a way to pick only signatures from T

**Comment by voxpelli** [comment]
@trevorade I think the issue is that this repo is using an outdated version of `tsd` and since `tsd` ships with its own version of `typescript` this isn't discovered by it. When updating `tsd` it does error on this: #839 

Hence why we probably should move away from `tsd` as we talked about in #837

**Comment by mrazauskas** [comment]
I was looking at the issue with `ReadonlyDeep`. Bisecting tells that the first bad commit is https://github.com/microsoft/TypeScript/pull/54448. Hope that helps.
