### ISSUE TITLE
Set up dependabot / renovate

### ISSUE THREAD

**Issue by voxpelli** [sindresorhus/type-fest#840]
I think it would be great if PR:s like #838 and #839 was opened automatically. Especially something like the `tsd` one. Then it would be visible right away if a new version either breaks something or highlights something that was already broken but wasn't showing before, like #839 / #833.

Thoughts @sindresorhus @skarab42 and others?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/840">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/840/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/840/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
👎 I personally find those tools more spammy than helpful.

**Comment by voxpelli** [comment]
@sindresorhus In a normal project I can agree, but since we have five dependencies only in this project and since some (tsd, typescript) are vital to keep up to date I think it would be good.

Also, one can make Dependabot less spammy nowadays by having it create a single PR for all dependencies, see eg: https://github.com/hannobraun/fornjot/pull/2269

(And Renovate can be run in eg. a Dashboard only mode, only producing eg. https://github.com/voxpelli/eslint-config/issues/1 and no automatic PR:s, one need to toggle PR:s manually by checking the checkboxes)
