### ISSUE TITLE
IfAny circular constraint in TS 5.4+

### ISSUE THREAD

**Issue by kkmuffme** [sindresorhus/type-fest#846]
Line 3 reports `Type parameter 'T' has a circular constraint. (2313)` since TS 5.4 which can be fixed with `NoInfer`

```
import type {IfAny} from "type-fest";

function foo<T extends IfAny<T, never, string>>( arg: T ): string;

function fooN<T extends IfAny<NoInfer<T>, never, string>>( arg: T ): string;
```

[Playground](https://www.typescriptlang.org/play?ssl=3&ssc=67&pln=4&pc=1#code/JYWwDg9gTgLgBDAnmApnA3gSQGYEEB2iAvnNlBCHAERKoC02KAzjFQNwBQH2ArvgMYxgEfKQgQAPABU4KAB4wU+ACZM4OAomkAaOPhQA3FFF0sowfAHMAfNYAUcAIZRLALjgyAlO7MXLnbj5BYVFscQA5aVkFJVV1PEIJcIhMfEYoaWtdfSMTOF8rWwdnNw84b3yYcytOIA)

Is this something that can be fixed by IfAny internally to avoid having to change 100s of places where it reports this error since TS 5.4 in our codebase?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/846">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/846/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/846/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
Yeah, it does seem like we can just do:

```diff
-type IsAny<T> = 0 extends 1 & T ? true : false;
+type IsAny<T> = 0 extends 1 & NoInfer<T> ? true : false;
```

@tommy-mitchell Thoughts?

**Comment by voxpelli** [comment]
Also needs tests that catches the error, so yet another one that highlights #837
