### ISSUE TITLE
Make the second argument to RequireAllOrNone optional

### ISSUE THREAD

**Issue by roryabraham** [sindresorhus/type-fest#847]
Minor suggestion for an enhancement - make the second argument to `RequireAllOrNone` optional:

i.e: `RequireAllOrNone<MyType>` would be functionally equivalent to `RequireAllOrNone<MyType, keyof MyType>`

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/847">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/847/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/847/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
Makes sense to me.

@tommy-mitchell Any reason you went with `never`? I noticed you used `key T` in your issue: https://github.com/sindresorhus/type-fest/issues/652#issue-1823667703

**Comment by tommy-mitchell** [comment]
I didn't add the `never` constraint, that was introduced when `RequireAllOrNone` was created in #254.

We're just inconsistent in general with our `RequireX` types - some have an optional second parameter, others don't. I think all of them should, personally.

**Comment by sindresorhus** [comment]
Alright. Let's do it.

**Comment by roryabraham** [comment]
Thanks all! 🚀
