### ISSUE TITLE
Type for serializable objects?

### ISSUE THREAD

**Issue by chen-ye** [sindresorhus/type-fest#855]
Would it make sense to create a type for [serializable objects](https://developer.mozilla.org/en-US/docs/Glossary/Serializable_object)? 

Similar to Jsonify et al., this would match values that could losslessly be deep-copied via `structuredClone` or `postMessage`.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/855">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/855/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/855/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
How would you use it?

---

For reference, the algorithm for `structuredClone`: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm

**Comment by chen-ye** [comment]
My two use cases are similar to how I currently use the Jsonify family of types:
* To ensure that an application state object as passed between a web worker and the main thread remains serializable
* To more strongly type the outputs of a structuredClone call

**Comment by sindresorhus** [comment]
It's more like `Jsonifiable`. Could maybe be called `StructuredCloneable`.
