### ISSUE TITLE
Proposal: SetKeyRequired with key required, but allow undefined value

### ISSUE THREAD

**Issue by Clindbergh** [sindresorhus/type-fest#856]
```typescript
type a = { a?: number, b: number | undefined};

type b = SetRequired<a, 'a' | 'b'>;
```
I would have expected the type `b` to be: **(1)**
```typescript
{ a: number, b: number | undefined }
```
however the type seems to be
```typescript
{ a: number, b: number }
```
Is there a way to enforce the presence of the key but not require the value to be defined (like **(1)**)? 

This can be manually achieved with this type definition:
```typescript
{ a: b['a'], b: b['b'] }
```
But this is a bit more cumbersome.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/856">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/856/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/856/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
Do you have `"exactOptionalPropertyTypes": true,` in your tsconfig?
