### ISSUE TITLE
OverrideProperties changes undefined as optional

### ISSUE THREAD

**Issue by CarinaChenot** [sindresorhus/type-fest#858]
Considering this:

```ts
import { OverrideProperties } from 'type-fest';

type Original = {
  foo: string;
  bar: string;
};

type Modified = {
  foo: string | undefined;
  bar: string;
};

const test: OverrideProperties<Original, Modified> = { bar: '' };
```

foo is typed as `foo?: string` instead of `foo: string | undefined`

![CleanShot 2024-04-08 at 09 01 13@2x](https://github.com/sindresorhus/type-fest/assets/16705167/abc27af6-12c4-4fd1-ab6f-6e12605e9fcb)

This is particularly problematic when using `exactOptionalPropertyTypes` flag

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/858">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/858/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/858/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
Are you on the latest `type-fest` version?

I added a test for your case and it is passing: https://github.com/sindresorhus/type-fest/commit/2547a0093ceca89df404fb6c6b0ae0a02a760671

**Comment by CarinaChenot** [comment]
@sindresorhus Indeed, issue went away with 4.10.0 my bad, thank you!

**Comment by mwg-ofx** [comment]
Whatever changed between 4.9.0 and 4.10.0 related to `OverrideProperties` was a breaking change that should have happened with a major version bump. It doesn't matter if the behaviour of `OverrideProperties` was technically buggy, the fact is that there's plenty of code out there relying on the old behaviour, and upgrading to a newer release of the v4 series has been made more difficult by this breakage.
