### ISSUE TITLE
Type-fest based prelude

### ISSUE THREAD

**Issue by Superpat** [sindresorhus/type-fest#871]
My search-fu has failed to find exactly what I'm looking for, so I'm asking here.

Are there any projects that try to re-implement various js primitive type prototypes using the types in this ? For instance re-implementing String.split to return the Split type et al. This is mostly an intellectual curiosity, but I'd be curious how it works in practice. 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/871">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/871/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/871/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ts-extras and https://github.com/total-typescript/ts-reset
