### ISSUE TITLE
ArrayExceptLastElement type

### ISSUE THREAD

**Issue by Superpat** [sindresorhus/type-fest#872]
Maybe there's a simpler way to do this, but here's a function that will get the inverse of LastArrayElement:

```ts
export type ArrayExceptLastElement<Elements extends readonly unknown[], ElementBeforeTailingSpreadElement = never> =
	// If the last element of an array is a spread element, the `LastArrayElement` result should be `'the type of the element before the spread element' | 'the type of the spread element'`.
	Elements extends readonly []
		? ElementBeforeTailingSpreadElement
		: Elements extends readonly [...infer U, infer V]
			? U
			: Elements extends readonly [infer U, ...infer V]
				// If we return `V[number] | U` directly, it would be wrong for `[[string, boolean, object, ...number[]]`.
				// So we need to recurse type `V` and carry over the type of the element before the spread element.
				? ArrayExceptLastElement<V, U>
				: Elements extends ReadonlyArray<infer U>
					? U | ElementBeforeTailingSpreadElement
					: never;
```

I had use for it in a string manipulation function where I used it to remove the last `.${string}` part in pathnames. Is it worth it for me to write a pull request for this ?

**Comment by Emiyaaaaa** [comment]
You can use `ArraySlice`:
```ts
import type { ArraySlice } from 'type-fest'
type A = ArraySlice<[0, 1, 2, 3, 4], 0, -1>;
// => [0, 1, 2, 3]
```

**Comment by Superpat** [comment]
Reopening this, although it might be better as an actual bug report. `ArraySplice` is returning `unknown[]` where `ArrayExceptLastElement` was returning a more concrete type.

Meaning I was able to use `Join` on the output of `ArrayExceptLastElement`

**Comment by Emiyaaaaa** [comment]
Can you provide a minimum reproduction

**Comment by Superpat** [comment]
[Here you go](https://www.typescriptlang.org/play/?&e=183#code/FASwtgDg9gTgLgAgN4IFJRAOwDQIMoQA2IcuAgjDAIYCeBxAxgKYIC+CAZjFGAgERwaEJgFoOTAM5w+AbmDAOAV0wM4IKJgQwmYKADcmAUQAecJpgnrMAHgBiCJqfMATCQikwsAc1wAlB06YrmgYNhTUdEQgzNb0JHa4AOQAdIkAfLgADLgiAIwZCCnpaQAUwACQHCCE5lRgTABcCLbAAJRN-kgVDBpS7lFwAHJ1LAC8nNW19ckSAyVFrXLls8RDIzNRzCUrJMPTNZhecAAWCCIIubi5ixXacIowmjtr0wBWofOprQhUbr5yrHkgmECHCtBMzAgcAAMr84IZCNYKgidOY4G5HGYgm5tFRnBpCDQEMoANaYKAAd0wAG0ALrYZE1eqYOAAISYHFgTAAKlRqt4CLjnCjmYhxpgmAYYMA0ghxiK0RjAsEhQSiXSEAB6TUIACSHAQJxYhDhDiZaIQUANVE0VEotAQIDcVH6QrNqJZuCNCAABrCpGCaAqWT6tJJFIREBJjlAI84EAAjFg+xLe4EsK2G44sJjmlmJjlcrMsWZu3MeuCJBAAH0KaaEGYN3tLTDx7tFiR9yQqAH4EMG2YXtLz+YdBa3hXm4BUmgOlViVRO1Qhqck11hxDAEABVXAbphbgBqtIq5T729Ps6n85cOKXmEJK-3W93CDXyWfCGPp7PWp1+oQCkWDuB5NB9Q9qUwRQwCTGBaRrHdQ2cEBtFUQk90QClY0IeMk0A7hDk4WBfWpakPG8XAEygKAahtXAoATV4mFUXB3ygmCDzpWkux-cptXwKBAJYCUmHjOBBNQh4JBYdNfUPUMbXjBg7RgIl9APYtDQbS0m2zdsLSTTltE0ls23LUVu3KKzykDCEmChf14URQ9cG3NIfyvCsb2xBBfHvQlA2sT83N488EIHdkjJ5PliDHCAhQHXimglKU5AUZRVCsMNdAMEwsUsDQACY7ACBc3HIw4-FK28QiwaxbOMSEYThBFYgGBJClSNICiKbqykqSZMBGJoWnaXzkG6XoowGPYxgmA51meT5EhuZYZsWzYmG2db9nMI5TnOS4LlWkDHn6VZZuSd4sGW75fl8gFgCAA)

**Comment by Emiyaaaaa** [comment]
> [Here you go](https://www.typescriptlang.org/play/?&e=183#code/FASwtgDg9gTgLgAgN4IFJRAOwDQIMoQA2IcuAgjDAIYCeBxAxgKYIC+CAZjFGAgERwaEJgFoOTAM5w+AbmDAOAV0wM4IKJgQwmYKADcmAUQAecJpgnrMAHgBiCJqfMATCQikwsAc1wAlB06YrmgYNhTUdEQgzNb0JHa4AOQAdIkAfLgADLgiAIwZCCnpaQAUwACQHCCE5lRgTABcCLbAAJRN-kgVDBpS7lFwAHJ1LAC8nNW19ckSAyVFrXLls8RDIzNRzCUrJMPTNZhecAAWCCIIubi5ixXacIowmjtr0wBWofOprQhUbr5yrHkgmECHCtBMzAgcAAMr84IZCNYKgidOY4G5HGYgm5tFRnBpCDQEMoANaYKAAd0wAG0ALrYZE1eqYOAAISYHFgTAAKlRqt4CLjnCjmYhxpgmAYYMA0ghxiK0RjAsEhQSiXSEAB6TUIACSHAQJxYhDhDiZaIQUANVE0VEotAQIDcVH6QrNqJZuCNCAABrCpGCaAqWT6tJJFIREBJjlAI84EAAjFg+xLe4EsK2G44sJjmlmJjlcrMsWZu3MeuCJBAAH0KaaEGYN3tLTDx7tFiR9yQqAH4EMG2YXtLz+YdBa3hXm4BUmgOlViVRO1Qhqck11hxDAEABVXAbphbgBqtIq5T729Ps6n85cOKXmEJK-3W93CDXyWfCGPp7PWp1+oQCkWDuB5NB9Q9qUwRQwCTGBaRrHdQ2cEBtFUQk90QClY0IeMk0A7hDk4WBfWpakPG8XAEygKAahtXAoATV4mFUXB3ygmCDzpWkux-cptXwKBAJYCUmHjOBBNQh4JBYdNfUPUMbXjBg7RgIl9APYtDQbS0m2zdsLSTTltE0ls23LUVu3KKzykDCEmChf14URQ9cG3NIfyvCsb2xBBfHvQlA2sT83N488EIHdkjJ5PliDHCAhQHXimglKU5AUZRVCsMNdAMEwsUsDQACY7ACBc3HIw4-FK28QiwaxbOMSEYThBFYgGBJClSNICiKbqykqSZMBGJoWnaXzkG6XoowGPYxgmA51meT5EhuZYZsWzYmG2db9nMI5TnOS4LlWkDHn6VZZuSd4sGW75fl8gFgCAA)

`ArraySlice`, not `ArraySplice`

**Comment by Superpat** [comment]
Oh, I feel dumb. ArraySlice works as intended, sorry for the mistake.
