### ISSUE TITLE
ConditionalKeys does not correctly filter out `never` type

### ISSUE THREAD

**Issue by roryabraham** [sindresorhus/type-fest#878]
I'm seeing some unexpected behavior in this minimal example:

```ts
type ConditionalKeys<Base, Condition> =
{
	// Map through all the keys of the given base type.
	[Key in keyof Base]-?:
	// Pick only keys with types extending the given `Condition` type.
	Base[Key] extends Condition
	// Retain this key since the condition passes.
		? Key
	// Discard this key since the condition fails.
		: never;

	// Convert the produced object into a union type of the keys which passed the conditional test.
}[keyof Base];

type MyMap = {
	a: {
		b: string;
	};
	c: {
		html: string;
	};
	d: never;
};

type MyFilteredMap = ConditionalKeys<MyMap, {html: string}>;
```

The root cause is that `never` can extend anything. I'm not sure if this is expected behavior or not, but it was a gotcha for me. It can be fixed like so:

```ts
type ConditionalKeys<Base, Condition> = {
    [Key in keyof Base]-?:
        // The key is retained if its value extends the given `Condition` and is not `never`
        Base[Key] extends Condition
            ? (Base[Key] extends never ? never : Key)
            : never;
}[keyof Base];
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/878">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/878/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/878/pledge.svg">
</picture>
</a>

**Comment by roryabraham** [comment]
Happy to open a PR if we agree that this is unexpected behavior.

**Comment by sindresorhus** [comment]
That is indeed unexpected behavior. A pull request would be amazing 🙏

**Comment by roryabraham** [comment]
Opened https://github.com/sindresorhus/type-fest/pull/881. Thanks in advance for reviewing 🙇🏼
