### ISSUE TITLE
`schema` should properly set type of objects in arrays

### ISSUE THREAD

**Issue by bvandercar-vt** [sindresorhus/type-fest#883]
Current implementation:

```tsx
import type {Schema} from 'type-fest';

interface Users {
	names: Array<{
		firstname: string;
		lastname: string;
	}>;
}

type UserMask = Schema<Users, 'mask' | 'hide' | 'show'>;

const userMaskSettings: UserMask = {
	names: 'mask',
}
```

Should be:

```tsx
const userMaskSettings: UserMask = {
  names: [
    { firstname: 'mask', lastname: 'mask' },
    { firstname: 'hide', lastname: 'show' },
  ],
}
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/883">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/883/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/883/pledge.svg">
</picture>
</a>

**Comment by grigorischristainas** [comment]
@sindresorhus, @bvandercar-vt, do you think the implementation should change for arrays in general, or just for arrays of objects? 

Given the following example, based on the current implementation:
```ts
import type {Schema} from 'type-fest';

interface Users {
	names: Array<string>;
}

type UserMask = Schema<Users, 'mask' | 'hide' | 'show'>;

const userMaskSettings: UserMask = {
	names: 'mask'
}
```
should `userMaskSettings` be changed as follows ?
```ts
const userMaskSettings: UserMask = {
	names: ['mask']
}
```

**Comment by bvandercar-vt** [comment]
@grigorischristainas that change makes sense to me.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/type-fest/pull/887
