### ISSUE TITLE
Expose Max Recursion Depth of Paths

### ISSUE THREAD

**Issue by fardolieri** [sindresorhus/type-fest#917]
I have a custom type that makes use of `Paths`. Whenever I use this type with a sufficiently complex input `T` I do get an error `Type instantiation is excessively deep and possibly infinite.ts(2589)`.

[The recursion limit of Paths is currently locked at 15.](https://github.com/Emiyaaaaa/type-fest/blob/60712f1d667a88dc2e3ae846281dd852f1303ac0/source/paths.d.ts#L78) When I slightly lower the amount of allowed recursions, e.g. from 15 to 10, my error goes away. 

Is there a reason why the `Depth` parameter is hidden to the outside world? I would like it to be configurable to handle those errors. What do you think?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/917">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/917/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/917/pledge.svg">
</picture>
</a>

**Comment by fardolieri** [comment]
If you want I could work on a PR

**Comment by sindresorhus** [comment]
PR welcome :)

It should be an options object similar to what's done here: https://github.com/sindresorhus/type-fest/blob/8a45ba048767aaffcebc7d190172d814a739feb0/source/camel-case.d.ts#L3-L15
