### ISSUE TITLE
Issues with `Paths` type

### ISSUE THREAD

**Issue by matthew-dean** [sindresorhus/type-fest#921]
I'm not sure why this is, but the paths produced by `Paths` ends up being slightly different from `Get`. Specifically, it would be nice if `Paths` produced a string array tuple type like:
```
[
  'arr[0].field'
  'arr.0.field' // both valid
  // ... other paths
]
```
... or with a config option, just:
```
[
  'arr[0].field'
  // ... other paths
]
```
Instead, it produces only the `{dot}{number}{dot}` form, like:
```
[
  'arr.0.field'
  // ... other paths
]
```

The other problem with `Paths` is that it can't handle a type extended from `Record`. For example, imagine this very simple use case:
```ts
import get from 'lodash/get'
import type { Paths, Get } from 'type-fest'

export function getter<const T extends Record<string, any>, P extends string = Paths<T>>(
  obj: T,
  path: P
): Get<T, P> {
  return get(obj, path)
}
```
This produces the TypeScript error:
```
Type 'Paths<T>' does not satisfy the constraint 'string'.
  Type 'number | `${number}`' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.ts(2344)
```
Even though we've specified that the record will only have string keys, `Paths` produces something other than a union of strings.

It looks like a workaround is:
```ts
export function getter<const T extends Record<string, any>, P extends string = Exclude<Paths<T>, number>>(
  obj: T,
  path: P
): Get<T, P> {
  return get(obj, path)
}
```
... but I'm not sure why this should be the case

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/921">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/921/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/921/pledge.svg">
</picture>
</a>

**Comment by voxpelli** [comment]
Ideally the two would be unified, tracked in https://github.com/sindresorhus/type-fest/issues/863, but I'm not an expert on these types in particular

**Comment by Emiyaaaaa** [comment]
I perfer add a new option to output the normal result like `arr[0].field`

And this option maybe can choose to output `['arr', '0', 'field']` or `arr[0]['field']` or some  useful thing in the feature.

A question is which should be the default action?

What do you think? @sindresorhus @voxpelli @matthew-dean

**Comment by sindresorhus** [comment]
We should add an option to use the `arr[0].field` style.

**Comment by sindresorhus** [comment]
> A question is which should be the default action?

It would be nice if it was compatible with `Get` by default, but that can be discussed in https://github.com/sindresorhus/type-fest/issues/450
