### ISSUE TITLE
`ArraySlice` resolves to `never` when passing `number`

### ISSUE THREAD

**Issue by StyleShit** [sindresorhus/type-fest#928]
When passing `number` as the `Start` parameter of `ArraySlice`, the returned type is `never`.

I think it should probably be something like this:

### Expected Behavior

```TS
type A = ArraySlice<[1, 2, 3], number>;
  // ^? Array<1 | 2 | 3>;
```

### Actual Behavior

```TS
type A = ArraySlice<[1, 2, 3], number>;
  // ^? never
```

[Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzjAnmApnAglKBDFAZQBtgBjTAXzgDMoIQ4AiVDAWhvQGcYmBuAFADWmLHAC82XARLl0AHgDaARgA0cAEzqAzOoAs6gKwBddQDsAriABG6KAD5BcOAHoXcAHoB+IA)

WDYT?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/928">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/928/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/928/pledge.svg">
</picture>
</a>

**Comment by Emiyaaaaa** [comment]
I think return never is expected

**Comment by fregante** [comment]
> ```ts
> type A = ArraySlice<[1, 2, 3], number>;
>   // ^? Array<1 | 2 | 3>;
> ```

No, the type should be `[1, 2, 3] | [2, 3] | [3] | []` + whatever else with negative values

Is that a useful type? I don’t think it's worth the extra complexity to support that
