### ISSUE TITLE
AsyncReturnType doesn't work

### ISSUE THREAD

**Issue by UberMouse** [sindresorhus/type-fest#93]
I'm not sure how `AsyncReturnType` is supposed to work. If I try it with a basic `async` function, that takes a string argument & returns it, I get a type error.

> Type '(bar: string) => Promise<string>' does not satisfy the constraint 'AsyncFunction'.
  Types of parameters 'bar' and 'args' are incompatible.
    Type 'unknown' is not assignable to type 'string'

I've set up a [Codesandbox](https://codesandbox.io/s/optimistic-shaw-jjxzi) that demonstrates this. I'm not sure what Typescript version it's using, it's not listed in the dependencies, but I am getting it with TS v3.8.2 in my local project.

I'm not sure if there is a specific reason not to use `any` here, but replacing `...args: unknown[]` with `...args: any[]` in the `AsyncFunction` definition resolves the error.

**Comment by sindresorhus** [comment]
// @resynth1943

**Comment by resynth1943** [comment]
Ahhh. I know exactly what this is.
