### ISSUE TITLE
Line-wrap all documentation?

### ISSUE THREAD

**Issue by joliss** [sindresorhus/type-fest#944]
You may have "Wrap lines" enabled on GitHub ...

<img width="200" alt="image" src="https://github.com/user-attachments/assets/e6a54e81-fbe3-44d8-bf0a-3dc94d101f81">

... so everything looks fine to you, but it's off by default, which makes the documentation hard to read:

<img width="937" alt="image" src="https://github.com/user-attachments/assets/48d88c24-841a-4c8a-b2b4-0f949a72c589">

I wonder if it would make sense to either line-wrap all paragraphs of text in the JSDoc strings -- VS Code has a [Rewrap](https://marketplace.visualstudio.com/items?itemName=stkb.rewrap) extension that helps with this -- or alternatively have an HTML export of the sources somewhere.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/944">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/944/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/944/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
I prefer soft-wrapping. Makes it easier to edit and also lets people use the width they prefer.

Making a proper documentation site is a goal, but I'm not aware of any good solution for this. There is TypeDoc, but I don't have the best experience with it (constantly failed, didn't properly show many types, etc).

**Comment by joliss** [comment]
Makes sense. I'll go ahead and close this then!
