### ISSUE TITLE
IsAny not working with "any" as generic type argument under different constraint

### ISSUE THREAD

**Issue by Xriuk** [sindresorhus/type-fest#947]
Reproduction
```ts
type Generic<Type extends string> = Type;
type GenericInstance = Generic<any>;


type T1 = GenericInstance extends Generic<infer T> ? T : never; // any
type T2 = IsAny<T1>; // true, as it should be

type T3 = GenericInstance extends Generic<infer T> ? IsAny<T> : never; // false, but should be true

// I guess the second inference removes references to the type being a string?
type T4 = GenericInstance extends Generic<infer T> ? IsAny<T extends (infer TT) ? TT : never> : never; // true, as it should be
```

My wild guess is that it has something to do with the generic constraint `<Type extends string>` and the returned `any` is still seen as some sort of `string` in this case, might be a TS bug?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/947">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/947/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/947/pledge.svg">
</picture>
</a>

**Comment by Emiyaaaaa** [comment]
Fixed in https://github.com/sindresorhus/type-fest/pull/993
