### ISSUE TITLE
`Arrayable` is unusable

### ISSUE THREAD

**Issue by fregante** [sindresorhus/type-fest#952]
Initially reported in https://github.com/sindresorhus/type-fest/pull/935#issuecomment-2312879342

In short:

- `function castArray<T>(a: Arrayable<T>): T[]` is hard to type
	[Demo](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwIJSgQwJ5oEYBsCmAvnAGZQQhwDkMGY+AtCfgM4xUDcAUFyQK4A7AMYxgEAXCFo2KdBgCMAHgCSMfCAB8ACgBuaXH3wAuOLMw4CKtZoCUJ1eoDaAXURcAkFHww+UCWYwAOmAWAN19Qxs4AH44PQN8OBNHeMNnbkIefmFRcUlpGACAJit1bVTjU1RzPHxS2xMvNAATcVwMOAcQFzdPb19-aqCQsIqo2IqkuBSI-HSuTKA)
- The code example in the [type's source](https://github.com/Max10240/type-fest/blob/70e0d8074625bb18b32358447b59e3fddadfaa1b/source/arrayable.d.ts#L10-L11) produces `any[]`, losing the type information provided
	[Demo](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgQSlAhgT3QIwDYCmcAvnAGZQQhwDkMmYBAtGQQM4w0DcAUD2QFcAdgGMYwCELg5hAE0IAKYELACYALjgcoygOYAaOBDWqNKNFlyEAPNr0A+AJSIecAJAjJHIybUAZYG8AXnMMTAA6QNQwhWMYU2cAfh94tThNAG040wBdXjc4QoB6IrgAPUSeYj56RjgABTx0ZWjLfAJrAA17OBDOuAAfOE6MvL5BUXFJaTlCACYlFTVNOyEDFNNNRuahVux22xgdNacXd08hb2z-QPgQvci2PdjfGCSNtMzrmDGC4tKKlUeEA)
	<img width="529" alt="Screenshot 1" src="https://github.com/user-attachments/assets/39825d55-53e3-4ed7-9c39-8dc46e9bb14f">

cc @Max10240 let's continue here

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/952">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/952/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/952/pledge.svg">
</picture>
</a>

**Comment by Max10240** [comment]
I agree. After all, it's called `Arrayable `, not `ReadonlyArrayable`😂

**Comment by Emiyaaaaa** [comment]
> I agree. After all, it's called `Arrayable `, not `ReadonlyArrayable`😂

But the reason for adding `readonly` is to support "all array"(`Array` and `readonly Array`), if we remove `readonly`, `readonly Array` will can not pass in.

**Comment by Max10240** [comment]
Yes, I know that, which is why I was fine when @sindresorhus suggested I add the `readonly` modifier. But not being able to work with "Array.isArray" is really a big problem, and in general, I recommend removing "readonly".
