### ISSUE TITLE
`AsyncReturnType` doesn't work with arguments

### ISSUE THREAD

**Issue by fregante** [sindresorhus/type-fest#98]
I'm not able to use this type:
```ts
type PromisedStringFunction = (query: string) => Promise<string>;
type ShouldBeAString = AsyncReturnType<PromisedStringFunction>;
```

I get this error:

```log
Type '(query: string) => Promise<string>' does not satisfy the constraint 'AsyncFunction'.
  Types of parameters 'query' and 'args' are incompatible.
    Type 'unknown' is not assignable to type 'string'.ts(2344)
```

I had my own `AsyncReturnType` and it worked well with `any`, not `unknown`

**Comment by buschtoens** [comment]
Can you confirm you're really on the latest version? It works for me:

```ts
type PromiseValue<PromiseType, Otherwise = PromiseType> = PromiseType extends Promise<infer Value> ? Value : Otherwise;
type AsyncFunction = (...args: any[]) => Promise<unknown>;
type AsyncReturnType<Target extends AsyncFunction> = PromiseValue<ReturnType<Target>>;

type PromisedStringFunction = (query: string) => Promise<string>;
type ShouldBeAString = AsyncReturnType<PromisedStringFunction>;
```

[TS Playground](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=6&pc=64#code/C4TwDgpgBACgTgewLYEsDOEBqBDANgVwgB55l0IAVcCAGigHlgALCOAd3KgF5ZFUMqkAHzdeZAdSgQAHsAgA7ACZox-YinkAzVlBwEIIgPy68hKAC4GzVhwwBuAFChIUAIJoQ8gMYAxfN+AUBHlRAAoAOkjsOABzNEtseRAAbQBdAEpuEVI1In8Aa3kENnkhR2dod08vACUIYHw4eUFiCmiY+qlZBWU3D28-AKDS0RzyPUIiOoamlqI22PqhMocnSTGMRQBlYDgNGMGvQOCwgEdCOBBLNF39zK5svnIiG735GJWKqC2mBHxcRQAIQgrh2bxioiq3mmjWa1BIT02YP2h2OpTsQA)

**Comment by fregante** [comment]
Fixed by https://github.com/sindresorhus/type-fest/pull/96

Sorry!
